/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `announcements` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AnnouncementsModule } from './announcements.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AnnouncementsAdminController } from './announcements.controller';
export { AnnouncementsController } from './announcements.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AnnouncementsService } from './announcements.service';
export { AnnouncementForm } from './announcements.service';
export { AnnouncementLevel } from './announcements.service';
export { AnnouncementAudience } from './announcements.service';
export { ICreateAnnouncementInput } from './announcements.service';
