/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `workspace-switch` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { WorkspaceSwitchModule } from './workspace-switch.module';

// ─── Services ─────────────────────────────────────────────────────
export { WorkspaceSwitchAuthService } from './workspace-switch.auth.service';
export { generateSwitchToken } from './workspace-switch.service';
export { hashSwitchToken } from './workspace-switch.service';
export { resolveTtlMs } from './workspace-switch.service';
export { buildSessionRow } from './workspace-switch.service';
export { evaluateConsumption } from './workspace-switch.service';
export { verifyToken } from './workspace-switch.service';
export { computeEffectiveRole } from './workspace-switch.service';
export { coerceRole } from './workspace-switch.service';
export { isGrantActive } from './workspace-switch.service';
export { resolveGrantExpiresAt } from './workspace-switch.service';
export { coerceCreateSwitchInput } from './workspace-switch.service';
export { coerceGrantInput } from './workspace-switch.service';
export { ROLE_RANK } from './workspace-switch.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { CrossOrgRole } from './workspace-switch.types';
export { IWorkspaceSwitchSession } from './workspace-switch.types';
export { ICrossOrgAdminGrant } from './workspace-switch.types';
export { ICreateSwitchInput } from './workspace-switch.types';
export { IConsumeResult } from './workspace-switch.types';
export { IGrantInput } from './workspace-switch.types';
export { IEffectiveRoleResult } from './workspace-switch.types';
