/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `permission-matrix` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { PermissionMatrixModule } from './permission-matrix.module';

// ─── Controllers ──────────────────────────────────────────────────
export { PermissionMatrixController } from './permission-matrix.controller';

// ─── Services ─────────────────────────────────────────────────────
export { PermissionMatrixService } from './permission-matrix.service';

// ─── Guards ───────────────────────────────────────────────────────
export { PermissionGuard } from './permission.guard';
export { PERMISSION_ACTION_META } from './permission.guard';
export { RequirePermission } from './permission.guard';
export { PermissionAction } from './permission.guard';

// ─── Constants ────────────────────────────────────────────────────
export { filterReferencesCurrentUser } from './permission-matrix.constants';
export { PERMISSION_MATRIX_CAPABILITY } from './permission-matrix.constants';
export { CURRENT_USER_SENTINEL } from './permission-matrix.constants';
export { PermissionFilter } from './permission-matrix.constants';
export { IPermissionRoleVo } from './permission-matrix.constants';

// ─── Other public exports ─────────────────────────────────────────
export { applyPermissionFilter } from './permission-filter-merge';
export { applyPermissionFilterToRecordQuery } from './permission-filter-merge';
export { PermissionInterceptor } from './permission.interceptor';
export { PERMISSION_INTERCEPTOR_META } from './permission.interceptor';
export { RequirePermissionFilter } from './permission.interceptor';
