/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `permission-matrix` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { PermissionMatrixModule } from './permission-matrix.module';

// ─── Controllers ──────────────────────────────────────────────────
export { PermissionMatrixController } from './permission-matrix.controller';

// ─── Services ─────────────────────────────────────────────────────
export { PermissionMatrixService } from './permission-matrix.service';

// ─── Guards ───────────────────────────────────────────────────────
export { PermissionGuard, PERMISSION_ACTION_META, RequirePermission, PermissionAction } from './permission.guard';

// ─── Constants ────────────────────────────────────────────────────
export { filterReferencesCurrentUser, PERMISSION_MATRIX_CAPABILITY, CURRENT_USER_SENTINEL, PermissionFilter, IPermissionRoleVo } from './permission-matrix.constants';

// ─── Other public exports ─────────────────────────────────────────
export { applyPermissionFilter, applyPermissionFilterToRecordQuery } from './permission-filter-merge';
export { PermissionInterceptor, PERMISSION_INTERCEPTOR_META, RequirePermissionFilter } from './permission.interceptor';
