/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `billing` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { BillingModule } from './billing.module';

// ─── Controllers ──────────────────────────────────────────────────
export { BillingCheckoutController } from './billing-checkout.controller';
export { BillingController } from './billing.controller';

// ─── Services ─────────────────────────────────────────────────────
export { BillingAuthService } from './billing.auth.service';
export { signWebhook, verifyWebhookSignature, parseEventPayload, resolvePlan, computePlanAmount, canAddSeats, isValidSubscriptionTransition, isInvoiceTerminal, isValidInvoiceTransition, buildSubscriptionRow, applySubscriptionUpdate, buildInvoiceRow, isHandledEvent, buildWebhookEventId, HANDLED_EVENT_TYPES, DEFAULT_EVENT_DISPATCH } from './billing.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PLAN_TABLE, SubscriptionStatus, InvoiceStatus, BillingPlanCode, ISubscription, IInvoice, IWebhookEvent, ICreateSubscriptionInput, IUpdateSubscriptionInput, ICreateInvoiceInput, IResolvedWebhook, BillingEventHandler, IPlanDescriptor } from './billing.types';

// ─── Manual re-exports (edit freely) ──────────────────────────────
export {
  BillingProrationService,
  type IPlanRate,
  type IProrationPeriod,
  type IProrationPreview,
  type ISeatChangePreviewInput,
  type IPlanChangePreviewInput,
} from './billing-proration.service';
export {
  BillingDunningService,
  type DunningStepKind,
  type DunningStepStatus,
  type DunningPlanStatus,
  type IDunningStep,
  type IDunningPlan,
  type IScheduleRecoveryInput,
  type IMarkStepExecutionInput,
} from './billing-dunning.service';
export {
  BillingDunningWorkerService,
  type IProcessDueStepsInput,
  type IProcessDueStepsError,
  type IProcessDueStepsResult,
} from './billing-dunning-worker.service';
export { BillingPortalController } from './billing-portal.controller';
export {
  BillingInvoicePdfService,
  type IRenderInvoicePdfInput,
} from './billing-invoice-pdf.service';
export {
  BillingPortalOrgGuard,
  type IBillingPortalOrgPrincipal,
} from './billing-portal-org.guard';
export {
  BillingMeteredInvoiceWorkerService,
  DEFAULT_WORKER_INTERVAL_MS,
  DEFAULT_WORKER_RATE_CARDS,
  type IProcessDueInvoicesInput,
  type IProcessDueInvoicesError,
  type IProcessDueInvoicesResult,
} from './billing-metered-invoice-worker.service';
export {
  BillingMeteredInvoiceService,
  type IMetricRateCard,
  type IMetricLinePreview,
  type IPreviewMeteredInvoiceInput,
  type IPreviewMeteredInvoiceResult,
  type IMaterializeMeteredInvoiceInput,
  type IMaterializeMeteredInvoiceResult,
} from './billing-metered-invoice.service';
export {
  BillingAddOnService,
  type AddOnMetric,
  type AddOnStatus,
  type IAddOn,
  type IAddOnDescriptor,
  type IActivateAddOnInput,
  type ICancelAddOnInput,
  type IExpireDueInput,
  type IPreviewMonthlyCostInput,
  type IPreviewMonthlyCostResult,
} from './billing-add-on.service';
export {
  BillingUsageLedgerService,
  type BillingUsageMetric,
  type IRecordUsageInput,
  type IUsageEvent,
  type IAggregateInput,
  type IAggregateResult,
  type IOverageTier,
  type IPreviewOverageInput,
  type IOveragePreview,
} from './billing-usage-ledger.service';
// ─── Manual re-exports (R56 cron + portal session helpers) ─────────
export {
  parseCron,
  shouldFire,
  nextFireAt,
  runCronTick,
  CronParseError,
} from './billing-cron';
export type { ICronSchedule, ICronTick, IShouldFireInput } from './billing-cron';
export {
  buildPortalSessionRequest,
  parsePortalSessionResponse,
  validatePortalReturnUrl,
  validateCustomerId,
  createPortalSession,
  PortalValidationError,
  DEFAULT_STRIPE_API_BASE,
  STRIPE_PORTAL_PATH,
} from './billing-portal-session';
export type {
  IBuildPortalRequestInput,
  IStripeHttpRequest,
  IStripePortalSession,
  IPortalFetchLike,
} from './billing-portal-session';
