/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `controller-factory` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Controllers ──────────────────────────────────────────────────
export { ControllerFactoryAuthService } from './controller-factory.auth.service';
export { validateRoute } from './controller-factory.service';
export { validateController } from './controller-factory.service';
export { buildRouteTable } from './controller-factory.service';
export { findController } from './controller-factory.service';
export { findRoute } from './controller-factory.service';
export { totalRoutes } from './controller-factory.service';
export { authedRoutes } from './controller-factory.service';
export { appendController } from './controller-factory.service';
export { MAX_CONTROLLERS } from './controller-factory.types';
export { MAX_ROUTES_PER_CONTROLLER } from './controller-factory.types';
export { CrudVerb } from './controller-factory.types';
export { IRouteSpec } from './controller-factory.types';
export { IControllerSpec } from './controller-factory.types';
export { IRouteTable } from './controller-factory.types';
