/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `controller-factory` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Controllers ──────────────────────────────────────────────────
export { ControllerFactoryAuthService } from './controller-factory.auth.service';
export { validateRoute, validateController, buildRouteTable, findController, findRoute, totalRoutes, authedRoutes, appendController } from './controller-factory.service';
export { MAX_CONTROLLERS, MAX_ROUTES_PER_CONTROLLER, CrudVerb, IRouteSpec, IControllerSpec, IRouteTable } from './controller-factory.types';
