/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `decorators` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Other public exports ─────────────────────────────────────────
export { IS_ALLOW_ANONYMOUS } from './allow-anonymous.decorator';
export { AllowAnonymous } from './allow-anonymous.decorator';
export { AllowAnonymousType } from './allow-anonymous.decorator';
export { BASE_NODE_PERMISSIONS_KEY } from './base-node-permissions.decorator';
export { BaseNodePermissions } from './base-node-permissions.decorator';
export { IS_DISABLED_PERMISSION } from './disabled-permission.decorator';
export { DisabledPermission } from './disabled-permission.decorator';
export { ENSURE_LOGIN } from './ensure-login.decorator';
export { EnsureLogin } from './ensure-login.decorator';
export { PERMISSIONS_KEY } from './permissions.decorator';
export { ANY_PERMISSIONS_KEY } from './permissions.decorator';
export { Permissions } from './permissions.decorator';
export { AnyPermissions } from './permissions.decorator';
export { IS_PUBLIC_KEY } from './public.decorator';
export { Public } from './public.decorator';
export { RESOURCE_META } from './resource_meta.decorator';
export { ResourceMeta } from './resource_meta.decorator';
export { IResourceMeta } from './resource_meta.decorator';
export { IS_TOKEN_ACCESS } from './token.decorator';
export { TokenAccess } from './token.decorator';
