/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `decorators` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Other public exports ─────────────────────────────────────────
export { IS_ALLOW_ANONYMOUS, AllowAnonymous, AllowAnonymousType } from './allow-anonymous.decorator';
export { ALLOW_ADMIN_TOKEN, AllowAdminToken } from './admin-token.decorator';
export { BASE_NODE_PERMISSIONS_KEY, BaseNodePermissions } from './base-node-permissions.decorator';
export { IS_DISABLED_PERMISSION, DisabledPermission } from './disabled-permission.decorator';
export { ENSURE_LOGIN, EnsureLogin } from './ensure-login.decorator';
export { PERMISSIONS_KEY, ANY_PERMISSIONS_KEY, Permissions, AnyPermissions } from './permissions.decorator';
export { IS_PUBLIC_KEY, Public } from './public.decorator';
export { RESOURCE_META, ResourceMeta, IResourceMeta } from './resource_meta.decorator';
export { IS_TOKEN_ACCESS, TokenAccess } from './token.decorator';
