/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `automation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AutomationModule } from './automation.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AutomationAdminController } from './automation-admin.controller';
export { AutomationController } from './automation.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AutomationAiBuilderService } from './automation-ai-builder.service';
export { AutomationRateLimitService, AutomationRateLimitKind } from './automation-rate-limit.service';
export { AutomationService } from './automation.service';
export { IMBridgeService, __test, IMProvider, IIMActionConfig } from './im-bridge.service';
export { WebhookDispatcher, signBody, IWebhookActionConfig } from './webhook-dispatcher.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { AUTOMATION_RUN_STATUSES, AUTOMATION_TRIGGER_TYPES, AUTOMATION_ACTION_TYPES, AutomationTriggerType, AutomationActionType, AutomationRunStatus, AutomationAdminRunStatus, IAutomationRow, IAutomationTriggerRow, IAutomationActionRow, IAutomationRunRow, IAutomationRunStep, IAutomationDetail, IAutomationCreateInput, IAutomationUpdateInput, IAutomationDraft, IAutomationAiDraftInput, IAutomationAiDraftResult, IAutomationTriggerInput, IAutomationCondition } from './automation.types';

// ─── Constants ────────────────────────────────────────────────────
export { AUTOMATION_SCHEDULE_QUEUE, AUTOMATION_SCHEDULE_JOB } from './automation-schedule.constants';

// ─── Other public exports ─────────────────────────────────────────
export { AutomationEventListener } from './automation-event.listener';
export { AutomationScheduleProcessor } from './automation-schedule.processor';
export { listScriptSamples, SCRIPT_SAMPLES, IScriptSample } from './script-samples';
