/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `automation-canvas` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AutomationCanvasAuthService } from './automation-canvas.auth.service';
export { resolveNodeRef, validateCanvasGraph, topoSort, planCanvasExecution, addNode, removeNode, addEdge, removeEdge, moveNode, serializeGraph, summarizeCanvas, groupNodesByKind } from './automation-canvas.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CANVAS_NODES, MAX_CANVAS_EDGES, CANVAS_NODE_ID_RE, CanvasNodeKind, CanvasNodeSpec, CanvasEdgeSpec, CanvasGraphSpec, CanvasValidationCode, CanvasValidationIssue, CanvasValidationResult, CanvasExecutionStep, CanvasExecutionPlan } from './automation-canvas.types';
