/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `automation-canvas` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AutomationCanvasAuthService } from './automation-canvas.auth.service';
export { resolveNodeRef } from './automation-canvas.service';
export { validateCanvasGraph } from './automation-canvas.service';
export { topoSort } from './automation-canvas.service';
export { planCanvasExecution } from './automation-canvas.service';
export { addNode } from './automation-canvas.service';
export { removeNode } from './automation-canvas.service';
export { addEdge } from './automation-canvas.service';
export { removeEdge } from './automation-canvas.service';
export { moveNode } from './automation-canvas.service';
export { serializeGraph } from './automation-canvas.service';
export { summarizeCanvas } from './automation-canvas.service';
export { groupNodesByKind } from './automation-canvas.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CANVAS_NODES } from './automation-canvas.types';
export { MAX_CANVAS_EDGES } from './automation-canvas.types';
export { CANVAS_NODE_ID_RE } from './automation-canvas.types';
export { CanvasNodeKind } from './automation-canvas.types';
export { CanvasNodeSpec } from './automation-canvas.types';
export { CanvasEdgeSpec } from './automation-canvas.types';
export { CanvasGraphSpec } from './automation-canvas.types';
export { CanvasValidationCode } from './automation-canvas.types';
export { CanvasValidationIssue } from './automation-canvas.types';
export { CanvasValidationResult } from './automation-canvas.types';
export { CanvasExecutionStep } from './automation-canvas.types';
export { CanvasExecutionPlan } from './automation-canvas.types';
