/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `org-quota-reservation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OrgQuotaReservationModule } from './org-quota-reservation.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OrgQuotaReservationController } from './org-quota-reservation.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OrgQuotaReservationAuthService } from './org-quota-reservation.auth.service';
export { isReservationStatus, isReservationPriority, maxReservationsPerOrg, defaultReservationTtlMs, priorityRank, validateReservation, normalizeReservation, sweepExpired, totalReserved, releaseReservation, consumeReservation, decideReservation, canReserveMore, canEvict } from './org-quota-reservation.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_RESERVATIONS_PER_ORG, DEFAULT_RESERVATION_TTL_MS, MIN_RESERVATION_AMOUNT, RESERVATION_STATUSES, RESERVATION_PRIORITIES, PRIORITY_RANK, RESERVATION_STATUS_LABELS, ReservationStatus, ReservationPriority, IOrgQuotaReservation, IReservationDecision, IOrgQuotaReservationOptions } from './org-quota-reservation.types';
