/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `org-quota-reservation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { OrgQuotaReservationAuthService } from './org-quota-reservation.auth.service';
export { isReservationStatus } from './org-quota-reservation.service';
export { isReservationPriority } from './org-quota-reservation.service';
export { maxReservationsPerOrg } from './org-quota-reservation.service';
export { defaultReservationTtlMs } from './org-quota-reservation.service';
export { priorityRank } from './org-quota-reservation.service';
export { validateReservation } from './org-quota-reservation.service';
export { normalizeReservation } from './org-quota-reservation.service';
export { sweepExpired } from './org-quota-reservation.service';
export { totalReserved } from './org-quota-reservation.service';
export { releaseReservation } from './org-quota-reservation.service';
export { consumeReservation } from './org-quota-reservation.service';
export { decideReservation } from './org-quota-reservation.service';
export { canReserveMore } from './org-quota-reservation.service';
export { canEvict } from './org-quota-reservation.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_RESERVATIONS_PER_ORG } from './org-quota-reservation.types';
export { DEFAULT_RESERVATION_TTL_MS } from './org-quota-reservation.types';
export { MIN_RESERVATION_AMOUNT } from './org-quota-reservation.types';
export { RESERVATION_STATUSES } from './org-quota-reservation.types';
export { RESERVATION_PRIORITIES } from './org-quota-reservation.types';
export { PRIORITY_RANK } from './org-quota-reservation.types';
export { RESERVATION_STATUS_LABELS } from './org-quota-reservation.types';
export { ReservationStatus } from './org-quota-reservation.types';
export { ReservationPriority } from './org-quota-reservation.types';
export { IOrgQuotaReservation } from './org-quota-reservation.types';
export { IReservationDecision } from './org-quota-reservation.types';
export { IOrgQuotaReservationOptions } from './org-quota-reservation.types';
