/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `base-share` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { BaseShareModule } from './base-share.module';

// ─── Controllers ──────────────────────────────────────────────────
export { BaseShareOpenController } from './base-share-open.controller';
export { BaseShareController } from './base-share.controller';

// ─── Services ─────────────────────────────────────────────────────
export { BaseShareAuthService, IBaseShareInfo, IJwtBaseShareInfo } from './base-share-auth.service';
export { BaseShareService } from './base-share.service';
