/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `webhook-bridge` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { WebhookBridgeAuthService } from './webhook-bridge.auth.service';
export { computeHmacSignature, safeEqualHex, verifyInboundAuth, detectEventType, matchesEventFilter, validateBridge, buildRoutedEvent, buildDispatch } from './webhook-bridge.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { BridgeDirection, BridgeAuthScheme, IBridgeAuthConfig, IWebhookBridge, IInboundEnvelope, AuthFailureReason, IAuthResult, IRoutedEvent, IBridgeDispatch } from './webhook-bridge.types';
