/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `plugin-context-menu` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { PluginContextMenuModule } from './plugin-context-menu.module';

// ─── Controllers ──────────────────────────────────────────────────
export { PluginContextMenuController } from './plugin-context-menu.controller';

// ─── Services ─────────────────────────────────────────────────────
export { PluginContextMenuService } from './plugin-context-menu.service';
