/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `quota-anomaly` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { QuotaAnomalyModule } from './quota-anomaly.module';

// ─── Controllers ──────────────────────────────────────────────────
export { QuotaAnomalyAdminController } from './quota-anomaly.controller';

// ─── Services ─────────────────────────────────────────────────────
export { QuotaAnomalyAuthService } from './quota-anomaly.auth.service';
export { isQuotaMetric, isNotificationChannel, validateSample, buildWindow, appendSample, medianValue, capRatio, burstRatio, severityFromRatios, channelsForSeverity, capChannels, buildReport, evaluateWindow, trimReports } from './quota-anomaly.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { ANOMALY_RATIO_WARNING, ANOMALY_RATIO_CRITICAL, ANOMALY_CAP_RATIO_WARNING, ANOMALY_CAP_RATIO_CRITICAL, MAX_WINDOW_SAMPLES, MAX_CHANNELS_PER_REPORT, ANOMALY_METRICS, ANOMALY_SEVERITIES, ANOMALY_CHANNELS, QuotaMetric, AnomalySeverity, NotificationChannel, IQuotaSample, IQuotaWindow, IAnomalyReport } from './quota-anomaly.types';
