/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `google-sheets-sync` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { GoogleSheetsSyncAuthService } from './google-sheets-sync.auth.service';
export { hashRefreshToken } from './google-sheets-sync.service';
export { stringifyFieldMap } from './google-sheets-sync.service';
export { hashFieldMap } from './google-sheets-sync.service';
export { isValidDirection } from './google-sheets-sync.service';
export { isValidStatusTransition } from './google-sheets-sync.service';
export { deriveAllowedMutations } from './google-sheets-sync.service';
export { resolveConflict } from './google-sheets-sync.service';
export { parseCellValue } from './google-sheets-sync.service';
export { buildMappingRow } from './google-sheets-sync.service';
export { buildSyncRecordRow } from './google-sheets-sync.service';
export { generateChannelId } from './google-sheets-sync.service';
export { buildChannelRow } from './google-sheets-sync.service';
export { foldRun } from './google-sheets-sync.service';
export { DEFAULT_HEADER_ROW } from './google-sheets-sync.service';
export { IMutations } from './google-sheets-sync.service';
export { IRunSummary } from './google-sheets-sync.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SheetsSyncDirection } from './google-sheets-sync.types';
export { SheetsMappingStatus } from './google-sheets-sync.types';
export { SheetsSyncRecordState } from './google-sheets-sync.types';
export { SheetsRunDirection } from './google-sheets-sync.types';
export { SheetsRunStatus } from './google-sheets-sync.types';
export { ISheetsFieldMap } from './google-sheets-sync.types';
export { IGoogleSheetsConnection } from './google-sheets-sync.types';
export { IGoogleSheetsMapping } from './google-sheets-sync.types';
export { IGoogleSheetsSyncRecord } from './google-sheets-sync.types';
export { IGoogleSheetsSyncLog } from './google-sheets-sync.types';
export { IGoogleSheetsWebhookChannel } from './google-sheets-sync.types';
export { ICreateConnectionInput } from './google-sheets-sync.types';
export { ICreateMappingInput } from './google-sheets-sync.types';
export { IRecordSyncStateInput } from './google-sheets-sync.types';
