/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `google-sheets-sync` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { GoogleSheetsSyncAuthService } from './google-sheets-sync.auth.service';
export { hashRefreshToken, stringifyFieldMap, hashFieldMap, isValidDirection, isValidStatusTransition, deriveAllowedMutations, resolveConflict, parseCellValue, buildMappingRow, buildSyncRecordRow, generateChannelId, buildChannelRow, foldRun, DEFAULT_HEADER_ROW, IMutations, IRunSummary } from './google-sheets-sync.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SheetsSyncDirection, SheetsMappingStatus, SheetsSyncRecordState, SheetsRunDirection, SheetsRunStatus, ISheetsFieldMap, IGoogleSheetsConnection, IGoogleSheetsMapping, IGoogleSheetsSyncRecord, IGoogleSheetsSyncLog, IGoogleSheetsWebhookChannel, ICreateConnectionInput, ICreateMappingInput, IRecordSyncStateInput } from './google-sheets-sync.types';
