/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `admin` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AdminOpenApiModule } from './admin-open-api.module';
export { EnterpriseReadinessModule } from './enterprise-readiness.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AdminOpenApiController } from './admin-open-api.controller';
export { EnterpriseReadinessController } from './enterprise-readiness.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AdminOpenApiService } from './admin-open-api.service';
export { AdminTableQueryOpsService } from './admin-table-query-ops.service';
export { EnterpriseReadinessService } from './enterprise-readiness.service';
export { CapabilityDescriptor } from './enterprise-readiness.service';
export { EnterpriseReadinessReport } from './enterprise-readiness.service';
