/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `org-custom-role` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OrgCustomRoleModule } from './org-custom-role.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OrgCustomRoleController } from './org-custom-role.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OrgCustomRoleAuthService } from './org-custom-role.auth.service';
export { isCapability, isScopeKind, isBuiltInRole, maxRoles, maxCaps, maxScopes, validateScope, validateRole, normalizeRole, canRegisterMore, normalizeAssignment, validateAssignment, roleGrants, roleAppliesToBase, resolveInherited, applicableScopes, decideAccess, testHelpers } from './org-custom-role.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CUSTOM_ROLES_PER_ORG, MAX_CAPABILITIES_PER_ROLE, MAX_SCOPES_PER_ROLE, MAX_NAME_LENGTH, MAX_DESCRIPTION_LENGTH, BUILT_IN_ROLE_CAPABILITIES, CUSTOM_ROLE_CAPABILITY_LABELS, BuiltInRole, CustomRoleCapability, RoleScopeKind, IRoleScope, ICustomRole, IRoleAssignment, IOrgCustomRoleOptions } from './org-custom-role.types';
