/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `org-custom-role` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OrgCustomRoleModule } from './org-custom-role.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OrgCustomRoleController } from './org-custom-role.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OrgCustomRoleAuthService } from './org-custom-role.auth.service';
export { isCapability } from './org-custom-role.service';
export { isScopeKind } from './org-custom-role.service';
export { isBuiltInRole } from './org-custom-role.service';
export { maxRoles } from './org-custom-role.service';
export { maxCaps } from './org-custom-role.service';
export { maxScopes } from './org-custom-role.service';
export { validateScope } from './org-custom-role.service';
export { validateRole } from './org-custom-role.service';
export { normalizeRole } from './org-custom-role.service';
export { canRegisterMore } from './org-custom-role.service';
export { normalizeAssignment } from './org-custom-role.service';
export { validateAssignment } from './org-custom-role.service';
export { roleGrants } from './org-custom-role.service';
export { roleAppliesToBase } from './org-custom-role.service';
export { resolveInherited } from './org-custom-role.service';
export { applicableScopes } from './org-custom-role.service';
export { decideAccess } from './org-custom-role.service';
export { testHelpers } from './org-custom-role.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CUSTOM_ROLES_PER_ORG } from './org-custom-role.types';
export { MAX_CAPABILITIES_PER_ROLE } from './org-custom-role.types';
export { MAX_SCOPES_PER_ROLE } from './org-custom-role.types';
export { MAX_NAME_LENGTH } from './org-custom-role.types';
export { MAX_DESCRIPTION_LENGTH } from './org-custom-role.types';
export { BUILT_IN_ROLE_CAPABILITIES } from './org-custom-role.types';
export { CUSTOM_ROLE_CAPABILITY_LABELS } from './org-custom-role.types';
export { BuiltInRole } from './org-custom-role.types';
export { CustomRoleCapability } from './org-custom-role.types';
export { RoleScopeKind } from './org-custom-role.types';
export { IRoleScope } from './org-custom-role.types';
export { ICustomRole } from './org-custom-role.types';
export { IRoleAssignment } from './org-custom-role.types';
export { IOrgCustomRoleOptions } from './org-custom-role.types';
