/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-cost-forecaster` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AiCostForecasterModule, AiCostForecasterUsageLoaderProvider } from './ai-cost-forecaster.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AiCostForecasterController, UsageLoader } from './ai-cost-forecaster.controller';

// ─── Other public exports ─────────────────────────────────────────
export { linearSlope, forecastCredits, UsageRow, ForecastInput, ForecastOutput } from './ai-cost-forecaster';
