/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-cost-forecaster` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AiCostForecasterModule } from './ai-cost-forecaster.module';
export { AiCostForecasterUsageLoaderProvider } from './ai-cost-forecaster.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AiCostForecasterController } from './ai-cost-forecaster.controller';
export { UsageLoader } from './ai-cost-forecaster.controller';

// ─── Other public exports ─────────────────────────────────────────
export { linearSlope } from './ai-cost-forecaster';
export { forecastCredits } from './ai-cost-forecaster';
export { UsageRow } from './ai-cost-forecaster';
export { ForecastInput } from './ai-cost-forecaster';
export { ForecastOutput } from './ai-cost-forecaster';
