/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-exchange-audit` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { DataExchangeAuditAuthService } from './data-exchange-audit.auth.service';
export { validateEvent } from './data-exchange-audit.service';
export { appendEvent } from './data-exchange-audit.service';
export { verifyChain } from './data-exchange-audit.service';
export { queryEvents } from './data-exchange-audit.service';
export { lastHash } from './data-exchange-audit.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { hashEvent } from './data-exchange-audit.types';
export { AUDIT_HASH_ALGO } from './data-exchange-audit.types';
export { MAX_AUDIT_EVENTS_PER_ORG } from './data-exchange-audit.types';
export { MAX_AUDIT_METADATA_BYTES } from './data-exchange-audit.types';
export { AuditAction } from './data-exchange-audit.types';
export { IAuditEvent } from './data-exchange-audit.types';
export { IAuditQuery } from './data-exchange-audit.types';
