/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-exchange-audit` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { DataExchangeAuditAuthService } from './data-exchange-audit.auth.service';
export { validateEvent, appendEvent, verifyChain, queryEvents, lastHash } from './data-exchange-audit.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { hashEvent, AUDIT_HASH_ALGO, MAX_AUDIT_EVENTS_PER_ORG, MAX_AUDIT_METADATA_BYTES, AuditAction, IAuditEvent, IAuditQuery } from './data-exchange-audit.types';
