/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `audit-export` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AuditExportModule } from './audit-export.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AuditExportController } from './audit-export.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AuditExportAuthService } from './audit-export.auth.service';
export { toJsonl, toJson, toCsv, exportAuditEvents, mimeFor, signPayload, SIEM_HEADERS, DEFAULT_BATCH_SIZE } from './audit-export.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { AuditExportFormat, IAuditEventRow, IAuditExportInput, IAuditExportResult, ISiemWebhookInput, ISiemDeliverInput } from './audit-export.types';
