/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `decorators` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Other public exports ─────────────────────────────────────────
export { USE_V2_FEATURE_KEY } from './use-v2-feature.decorator';
export { UseV2Feature } from './use-v2-feature.decorator';
