/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-residency` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { DataResidencyModule } from './data-residency.module';

// ─── Controllers ──────────────────────────────────────────────────
export { DataResidencyController } from './data-residency.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DataResidencyAuthService } from './data-residency.auth.service';
export { isValidRegionCode, parseRegionHeader, normalizeRegionFromHeader, resolveRegionRoute, isValidStatusTransition, buildPolicyRow, buildRegionRow, HEADER_NAME } from './data-residency.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { HEADER_REGION, RegionStatus, RegionCode, IRegion, IDataResidencyPolicy, ISetPolicyInput, IResolvedRegionRoute } from './data-residency.types';
