/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-residency` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { DataResidencyModule } from './data-residency.module';

// ─── Controllers ──────────────────────────────────────────────────
export { DataResidencyController } from './data-residency.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DataResidencyAuthService } from './data-residency.auth.service';
export { isValidRegionCode } from './data-residency.service';
export { parseRegionHeader } from './data-residency.service';
export { normalizeRegionFromHeader } from './data-residency.service';
export { resolveRegionRoute } from './data-residency.service';
export { isValidStatusTransition } from './data-residency.service';
export { buildPolicyRow } from './data-residency.service';
export { buildRegionRow } from './data-residency.service';
export { HEADER_NAME } from './data-residency.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { HEADER_REGION } from './data-residency.types';
export { RegionStatus } from './data-residency.types';
export { RegionCode } from './data-residency.types';
export { IRegion } from './data-residency.types';
export { IDataResidencyPolicy } from './data-residency.types';
export { ISetPolicyInput } from './data-residency.types';
export { IResolvedRegionRoute } from './data-residency.types';
