/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `base-sql-executor` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { BaseSqlExecutorModule } from './base-sql-executor.module';

// ─── Services ─────────────────────────────────────────────────────
export { BaseSqlExecutorService } from './base-sql-executor.service';

// ─── Utilities ────────────────────────────────────────────────────
export { validateRoleOperations } from './utils';
export { checkTableAccess } from './utils';
export { getTableNames } from './utils';

// ─── Other public exports ─────────────────────────────────────────
export { allowedFunctions } from './allowed-functions';
export { BASE_READ_ONLY_ROLE_PREFIX } from './const';
export { BASE_SCHEMA_TABLE_READ_ONLY_ROLE_NAME } from './const';
