/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `compliance-policy-engine` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CompliancePolicyEngineModule } from './compliance-policy-engine.module';

// ─── Controllers ──────────────────────────────────────────────────
export { CompliancePolicyEngineController } from './compliance-policy-engine.controller';

// ─── Services ─────────────────────────────────────────────────────
export { CompliancePolicyEngineAuthService } from './compliance-policy-engine.auth.service';
export { buildRuleId, isRuleIdValid, buildBundle, findRule, filterBySeverity, isRuleValid, evaluateBundle, evaluateRule, shouldBlock, filterViolations, maxSeverity, actionsForViolation, bundleHash, BUILTIN_POLICIES } from './compliance-policy-engine.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { POLICY_RULE_ID_RE, DEFAULT_POLICY_BUNDLE_VERSION, SEVERITY_RANK, PolicySeverity, PolicyAction, PolicyRule, PolicyContext, PolicyViolation, PolicyEvalResult, PolicyBundle } from './compliance-policy-engine.types';
