/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `org-quota` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OrgQuotaModule } from './org-quota.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OrgQuotaController } from './org-quota.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OrgQuotaAuthService } from './org-quota.auth.service';
export { normalizeEnvelope, validateEnvelope, computeRemaining, decideQuota, buildOverage, pickNextBase, applyGrant, emptyFairnessState, decayFairness, aggregateUsage, applyOptions, testHelpers } from './org-quota.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_ORG_SOFT_FRACTION, DEFAULT_ORG_POLICY, MAX_ORG_QUOTA_KINDS, FAIRNESS_DECAY, FAIRNESS_BOOST, ORG_QUOTA_KINDS, ORG_QUOTA_LABELS, QuotaKind, OveragePolicy, GrantDecision, IOrgQuotaEnvelope, IOrgQuotaUsage, IOrgQuotaOverage, IFairnessState, IOrgQuotaCheckResult, IOrgQuotaOptions } from './org-quota.types';
