/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `sdk-platform` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { SdkPlatformAuthService } from './sdk-platform.auth.service';
export { isValidClientId, isValidLanguage, isValidChannel, isValidSecretFormat, isValidVersion, generateClientId, generateClientSecret, generateApiToken, hashSecret, constantTimeEquals, parseScopes, stringifyScopes, tokenHasAnyScope, tokenLastFour, buildAppRow, isTokenExpired, isValidTokenStatusTransition, buildTokenRow, foldUsage, isValidOutcome, IUsageAggregate } from './sdk-platform.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_LANGUAGES, SUPPORTED_CHANNELS, DEFAULT_TOKEN_PREFIX, SdkLanguage, SdkTokenStatus, SdkOutcome, SdkChannel, ISdkApp, ISdkToken, ISdkTokenReveal, ISdkUsageLog, ISdkRelease, IRegisterAppInput, IMintTokenInput, IRecordUsageInput, IPublishReleaseInput } from './sdk-platform.types';
