/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `view-layout-engine` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ViewLayoutEngineAuthService } from './view-layout-engine.auth.service';
export { effectiveViewport, layoutGrid, layoutKanban, layoutGallery, layoutCalendar, layoutForm, layoutMap, layoutTimeline, computeLayout } from './view-layout-engine.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_HEADER_HEIGHT, DEFAULT_ROW_HEIGHT, DEFAULT_GALLERY_CARD_SIZE, DEFAULT_KANBAN_CARD_HEIGHT, DEFAULT_TIMELINE_ROW_HEIGHT, DEFAULT_CALENDAR_DAY_SIZE, ViewportSpec, CellPosition, Rect, GridLayoutCell, GridLayoutSpec, KanbanLayoutColumn, KanbanLayoutSpec, GalleryLayoutCard, GalleryLayoutSpec, CalendarLayoutCell, CalendarLayoutSpec, FormLayoutField, FormLayoutSpec, MapLayoutMarker, MapLayoutSpec, TimelineLayoutBar, TimelineLayoutSpec, ViewLayoutSpec } from './view-layout-engine.types';
