/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `table` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TableModule } from './table.module';

// ─── Services ─────────────────────────────────────────────────────
export { TableDuplicateService } from './table-duplicate.service';
export { TableIndexService } from './table-index.service';
export { TablePermissionService } from './table-permission.service';
export { TableService } from './table.service';

// ─── Other public exports ─────────────────────────────────────────
export { DEFAULT_FIELDS } from './constant';
export { DEFAULT_VIEWS } from './constant';
export { DEFAULT_RECORD_DATA } from './constant';
