/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `compliance-attestation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ComplianceAttestationAuthService } from './compliance-attestation.auth.service';
export { hashStatement, buildAttestationId, isAttestationIdValid, submitAttestation, verifyAttestation, rejectAttestation, isActive, filterByKind, filterByRef, findActive, summarize, needsReAttestation, expireOverdue, daysUntilExpiry, isStatementValid } from './compliance-attestation.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { ATTESTATION_ID_RE, DEFAULT_VALIDITY_DAYS, DEFAULT_RE_ATTEST_DAYS, AttestationKind, AttestationState, Attestation, AttestationRequest, AttestationPolicy, AttestationReport } from './compliance-attestation.types';
