/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `session` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { SessionHandleModule } from './session-handle.module';
export { SessionModule } from './session.module';

// ─── Services ─────────────────────────────────────────────────────
export { SessionHandleService } from './session-handle.service';
export { SessionStoreService } from './session-store.service';
export { SessionService } from './session.service';

// ─── Other public exports ─────────────────────────────────────────
export { SessionSerializer } from './session.serializer';
