/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `oauth-server` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OAuthServerModule } from './oauth-server.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OAuthController } from './oauth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OAuthService } from './oauth.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { OAUTH_SCOPES } from './oauth.types';
export { DEFAULT_ACCESS_TOKEN_TTL_SEC } from './oauth.types';
export { DEFAULT_REFRESH_TOKEN_TTL_SEC } from './oauth.types';
export { DEFAULT_AUTHORIZATION_CODE_TTL_SEC } from './oauth.types';
export { OAuthScope } from './oauth.types';
export { IOAuthApplicationRow } from './oauth.types';
export { IAuthorizeRequest } from './oauth.types';
export { ITokenRequest } from './oauth.types';
export { ITokenResponse } from './oauth.types';
export { ICreateApplicationInput } from './oauth.types';
export { ICreateApplicationResult } from './oauth.types';
