/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `oauth-server` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OAuthServerModule } from './oauth-server.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OAuthController } from './oauth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OAuthService } from './oauth.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { OAUTH_SCOPES, DEFAULT_ACCESS_TOKEN_TTL_SEC, DEFAULT_REFRESH_TOKEN_TTL_SEC, DEFAULT_AUTHORIZATION_CODE_TTL_SEC, OAuthScope, IOAuthApplicationRow, IAuthorizeRequest, ITokenRequest, ITokenResponse, ICreateApplicationInput, ICreateApplicationResult } from './oauth.types';
