/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `api-explorer` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ApiExplorerModule } from './api-explorer.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ApiExplorerAdminController } from './api-explorer.admin.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ApiExplorerAuthService, InMemoryRouteCatalog, DEFAULT_TEABLE_ROUTES, IRouteCatalog } from './api-explorer.auth.service';
export { buildOpenApiSpec, buildExplorerHtml, validateRouteSpec, serializeSpec, IBuildSpecInput, IBuildHtmlInput } from './api-explorer.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { HttpMethod, ParamLocation, IRouteParam, IRouteResponse, IRouteSpec, IJsonSchema, IOpenApiSpec, IOperationObject, ISecurityScheme, IApiExplorerOptions } from './api-explorer.types';

// ─── Other public exports ─────────────────────────────────────────
export { DEFAULT_API_EXPLORER_OPTIONS } from './api-explorer.defaults';
