/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `openapi-static-gen` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { OpenApiStaticGenAuthService } from './openapi-static-gen.auth.service';
export { validateBuildInput } from './openapi-static-gen.service';
export { jsonArtifactPath } from './openapi-static-gen.service';
export { htmlArtifactPath } from './openapi-static-gen.service';
export { sha256 } from './openapi-static-gen.service';
export { buildArtifact } from './openapi-static-gen.service';
export { planBuild } from './openapi-static-gen.service';
export { findArtifact } from './openapi-static-gen.service';
export { hasJsonArtifact } from './openapi-static-gen.service';
export { hasHtmlArtifact } from './openapi-static-gen.service';
export { artifactCount } from './openapi-static-gen.service';
export { capArtifacts } from './openapi-static-gen.service';
export { allHashed } from './openapi-static-gen.service';
export { changedFrom } from './openapi-static-gen.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_BUILD_ARTIFACTS } from './openapi-static-gen.types';
export { MAX_BUILD_BYTES } from './openapi-static-gen.types';
export { BuildArtifactKind } from './openapi-static-gen.types';
export { IStaticBuildArtifact } from './openapi-static-gen.types';
export { IStaticBuildPlan } from './openapi-static-gen.types';
export { IStaticBuildInput } from './openapi-static-gen.types';
