/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `workspace-mirror` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { WorkspaceMirrorModule, WorkspaceMirrorService } from './workspace-mirror.module';

// ─── Controllers ──────────────────────────────────────────────────
export { WorkspaceMirrorController } from './workspace-mirror.controller';

// ─── Services ─────────────────────────────────────────────────────
export { WorkspaceMirrorAuthService } from './workspace-mirror.auth.service';
export { MirrorConfigValidationError, MirrorConfigNotFoundError, WorkspaceMirrorConfigService } from './workspace-mirror.config.service';
export { nextRecordId, validateMirrorConfig, nextSeq, batchRecords, buildBatchResult, computeLag, summarizeLags, pickNextStandby } from './workspace-mirror.service';

// ─── Types / interfaces ───────────────────────────────────────────
export * from './workspace-mirror.types';
