/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AiFieldRecordListenerModule } from './ai-field-record-listener.module';
export { AiModule } from './ai.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AiStreamingController } from './ai-streaming.controller';
export { AiController } from './ai.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AiGatewayModelsService, AI_GATEWAY_MODELS_CACHE_KEY } from './ai-gateway-models.service';
export { AiStreamingService, IStreamChunk, IStreamErrorChunk, IAiStreamEvent } from './ai-streaming.service';
export { AiService, INSTANCE_PROVIDER_NAME, ILanguageModelV2, IResolvedModelMapping } from './ai.service';

// ─── Other public exports ─────────────────────────────────────────
export { renderPromptTemplate, buildAiFieldPrompt, collectAiFieldSourceIds } from './ai-field-prompt.builder';
export { AiFieldRecordListener } from './ai-field-record.listener';
export { TASK_MODEL_MAP } from './constant';
export { modelProviders, getAdaptedProviderOptions, getTaskModelKey } from './util';

// R-AI-MODEL — capability × provider model resolver
export {
  AiModelResolverService,
  AI_MODEL_RESOLVER_MATRIX,
  type AiCapability,
  type AiProviderId,
  type IAiProviderConfig,
  type IAiResolverInput,
  type IAiResolverResult,
} from './ai-model-resolver.service';
