/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `main-bootstrap` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { MainBootstrapAuthService } from './main-bootstrap.auth.service';
export { validateBootstrapInput, buildPlan, transition, isValidTransition, defaultPlan, recordShutdown, requiredStepCount, isStopped, applyShutdown, isStepCompleted } from './main-bootstrap.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_PORT, DEFAULT_SHUTDOWN_TIMEOUT_MS, MAX_STEPS, LifecycleState, IBootstrapInput, IBootstrapStep, IBootstrapPlan, IShutdownSignal } from './main-bootstrap.types';
