ALTER TABLE "automation"
  ADD COLUMN IF NOT EXISTS "draft_config" JSONB,
  ADD COLUMN IF NOT EXISTS "draft_version" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "live_version" INTEGER NOT NULL DEFAULT 1;
