/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `open-api` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TableOpenApiModule } from './table-open-api.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TableController } from './table-open-api.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TableOpenApiV2Service } from './table-open-api-v2.service';
export { TableOpenApiService } from './table-open-api.service';
export { V2TableMutationCacheInvalidatorService } from './v2-table-mutation-cache-invalidator.service';

// ─── Other public exports ─────────────────────────────────────────
export { TableMutationCacheInvalidator } from './table-mutation-cache-invalidator';
export { mapLegacyCreateTableToV2Input } from './table-open-api-v2.mapper';
export { prepareCreateTableRo } from './table.pipe.helper';
export { TablePipe } from './table.pipe';
