/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-usage` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AiUsageModule } from './ai-usage.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AiUsageController } from './ai-usage.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AiUsageAuthService } from './ai-usage.auth.service';
export { normalizeModel, normalizeAction, bucketKey, applyToBucket, foldRecords, summarize, exceedsModelCap, parsePerModelCap, coercePolicy, mergePerModelCap } from './ai-usage.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IAiUsageBucket, IRecordUsageInput, IAiUsageSummary, IAiCreditGrantPolicy } from './ai-usage.types';
