/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-usage` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AiUsageAuthService } from './ai-usage.auth.service';
export { normalizeModel } from './ai-usage.service';
export { normalizeAction } from './ai-usage.service';
export { bucketKey } from './ai-usage.service';
export { applyToBucket } from './ai-usage.service';
export { foldRecords } from './ai-usage.service';
export { summarize } from './ai-usage.service';
export { exceedsModelCap } from './ai-usage.service';
export { parsePerModelCap } from './ai-usage.service';
export { coercePolicy } from './ai-usage.service';
export { mergePerModelCap } from './ai-usage.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IAiUsageBucket } from './ai-usage.types';
export { IRecordUsageInput } from './ai-usage.types';
export { IAiUsageSummary } from './ai-usage.types';
export { IAiCreditGrantPolicy } from './ai-usage.types';
