/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `vector-field` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { VectorFieldAuthService } from './vector-field.auth.service';
export { isValidMetric, isValidDimensions, isValidCollectionName, cosineSimilarity, dotProduct, euclideanDistance, score, hashContent, validateCreateCollection, buildCollectionRow, buildRecordRow, runSimilaritySearch, search, trimHitContent, buildRagPrompt, IRankedHit } from './vector-field.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_METRICS, DEFAULT_TOP_K, MIN_DIMENSIONS, MAX_DIMENSIONS, DistanceMetric, IndexStatus, IVectorCollection, IVectorRecord, ISimilarityHit, ISearchInput, ICreateCollectionInput, IUpsertRecordInput } from './vector-field.types';
