/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `openapi-metadata` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { OpenApiMetadataAuthService } from './openapi-metadata.auth.service';
export { validateOperation, validateParam, buildDocument, filterByVerb, filterByAuth, findOperation, countsByVerb, uniqueResources, mergeDocuments } from './openapi-metadata.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_OPERATIONS, MAX_PARAMS_PER_OPERATION, MAX_RESPONSES_PER_OPERATION, MAX_SCHEMAS, ParamLocation, IParamSpec, IRequestBodySpec, IResponseSpec, IOperationSpec, IOpenApiDocument } from './openapi-metadata.types';
