/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `multi-region-arbitration` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { MultiRegionArbitrationModule } from './multi-region-arbitration.module';

// ─── Controllers ──────────────────────────────────────────────────
export { MultiRegionArbitrationController } from './multi-region-arbitration.controller';

// ─── Services ─────────────────────────────────────────────────────
export { MultiRegionArbitrationAuthService } from './multi-region-arbitration.auth.service';
export { isValidResourceKey, isValidRegionId, isClockWithinSkew, fleetSkew, isSplitBrain, resolveTtl, resolveResolution, validateRequest, isLeaseLive, arbitrateWrite, detectSplitBrain, recordConflict, enqueueReplay, readyReplays, markReplayed, pruneQueue, testHelpers } from './multi-region-arbitration.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_LEASE_TTL_MS, MAX_LEASE_TTL_MS, DEFAULT_MAX_SKEW_MS, DEFAULT_RESOLUTION, MAX_RESOURCE_KEY_LENGTH, MAX_REPLAY_QUEUE_DEPTH, REPLAY_BACKOFF_BASE_MS, REPLAY_BACKOFF_CAP_MS, RESOURCE_KEY_KIND_LABELS, RegionId, LeaseState, ConflictResolution, IWriteLease, IRegionClock, IWriteRequest, ArbitrationDecision, IConflictRecord, IReplayQueueEntry, IMultiRegionArbitrationOptions } from './multi-region-arbitration.types';
