/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `audit-retention` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AuditRetentionModule } from './audit-retention.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AuditRetentionAdminController } from './audit-retention.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AuditRetentionAuthService } from './audit-retention.auth.service';
export { isStorageTarget, defaultHotDays, defaultColdDays, maxHotDays, maxColdDays, validatePolicy, normalizePolicy, decideTier, planSweep, batchEvents, estimateStorageBytes, startJob, finishJob, suggestPolicyForPlan } from './audit-retention.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_HOT_DAYS, DEFAULT_COLD_DAYS, MAX_HOT_DAYS, MAX_COLD_DAYS, MAX_BATCH, STORAGE_TARGETS, RETENTION_TIER_LABELS, RetentionTier, StorageTarget, IAuditRetentionPolicy, IAuditEvent, IRetentionDecision, IRetentionJob, IAuditRetentionOptions } from './audit-retention.types';
