/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-credit` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AiCreditModule } from './ai-credit.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AiCreditController } from './ai-credit.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AiCreditAuthService } from './ai-credit.auth.service';
export { monthBucketFromDate, monthBucketToStart, monthsBetween, applyEntry, summarizeMonth, checkAllowance, buildCheckResult, computeCarryover, coerceAction, AI_CREDIT_ACTIONS } from './ai-credit.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { AiCreditAction, IAiCreditEntry, IAiCreditUsageRow, IAiCreditCheckInput, IAiCreditCheckResult } from './ai-credit.types';
