/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-credit` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AiCreditAuthService } from './ai-credit.auth.service';
export { monthBucketFromDate } from './ai-credit.service';
export { monthBucketToStart } from './ai-credit.service';
export { monthsBetween } from './ai-credit.service';
export { applyEntry } from './ai-credit.service';
export { summarizeMonth } from './ai-credit.service';
export { checkAllowance } from './ai-credit.service';
export { buildCheckResult } from './ai-credit.service';
export { computeCarryover } from './ai-credit.service';
export { coerceAction } from './ai-credit.service';
export { AI_CREDIT_ACTIONS } from './ai-credit.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { AiCreditAction } from './ai-credit.types';
export { IAiCreditEntry } from './ai-credit.types';
export { IAiCreditUsageRow } from './ai-credit.types';
export { IAiCreditCheckInput } from './ai-credit.types';
export { IAiCreditCheckResult } from './ai-credit.types';
