/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `auth` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AuthModule } from './auth.module';
export { PermissionModule } from './permission.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AuthController } from './auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AuthService } from './auth.service';
export { PermissionService } from './permission.service';

// ─── Utilities ────────────────────────────────────────────────────
export { pickUserMe, getTemplateHeader, getBaseShareHeader, getShareViewHeader, IPickUserMe } from './utils';
