/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `conflict-replay` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ConflictReplayModule } from './conflict-replay.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ConflictReplayController } from './conflict-replay.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ConflictReplayAuthService } from './conflict-replay.auth.service';
export { validateEvent, enqueue, canRetry, markAttempt, replay, drain, toAttempt } from './conflict-replay.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CONFLICT_ATTEMPTS, MAX_QUEUE_SIZE, IDEMPOTENCY_DEDUP_WINDOW_MS, ConflictKind, IConflictEvent, IReplayAttempt } from './conflict-replay.types';
