/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `strategies` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Types / interfaces ───────────────────────────────────────────
export { jwtAuthInternalInfoSchema, IPayloadUser, IFromExtractor, IJwtAuthInfo, IWorkflowContext, IJwtAuthInternalInfo, JwtAuthInternalType } from './types';

// ─── Other public exports ─────────────────────────────────────────
export { PassportAccessTokenStrategy } from './access-token.passport';
export { AccessTokenStrategy } from './access-token.strategy';
export { ACCESS_TOKEN_STRATEGY_NAME, JWT_TOKEN_STRATEGY_NAME, TEMPLATE_STRATEGY_NAME, ANONYMOUS_STRATEGY_NAME } from './constant';
export { GithubStrategy } from './github.strategy';
export { GoogleStrategy } from './google.strategy';
export { JwtStrategy } from './jwt.strategy';
export { LocalStrategy } from './local.strategy';
export { OIDCStrategy } from './oidc.strategy';
export { PassportSessionStrategy } from './session.passport';
export { SessionStrategy } from './session.strategy';
