/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `oauth` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OAuthModule } from './oauth.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OAuthServerController } from './oauth-server.controller';
export { OAuthController } from './oauth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OAuthAppInitService } from './oauth-app-init.service';
export { OAuthServerService } from './oauth-server.service';
export { OAuthService } from './oauth.service';
export { PkceService, IPkceAuthorizeParams } from './pkce.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IClientBase, IAuthorizeClient, IExchangeClient, IPkceExchangeClient, ITokenClient, IOAuth2Server, IOAuthStoreOption, IClient, IAuthorizeRequest } from './types';

// ─── Other public exports ─────────────────────────────────────────
export { OAuthTxStore } from './oauth-tx-store';
