/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `byok-kms` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { LocalMasterKeyProvider } from './byok-kms.auth.service';
export { ByokKmsAuthService } from './byok-kms.auth.service';
export { IMasterKeyProvider } from './byok-kms.auth.service';
export { generateAlias } from './byok-kms.service';
export { isValidAlias } from './byok-kms.service';
export { generateDek } from './byok-kms.service';
export { encryptWithDek } from './byok-kms.service';
export { decryptWithDek } from './byok-kms.service';
export { wrapDek } from './byok-kms.service';
export { unwrapDek } from './byok-kms.service';
export { envelopeHash } from './byok-kms.service';
export { isRotationDue } from './byok-kms.service';
export { daysUntilRotation } from './byok-kms.service';
export { parseRotationPolicy } from './byok-kms.service';
export { stringifyRotationPolicy } from './byok-kms.service';
export { buildKeyRow } from './byok-kms.service';
export { normalizeMasterKey } from './byok-kms.service';
export { ALGORITHM } from './byok-kms.service';
export { DEK_BYTES } from './byok-kms.service';
export { IV_BYTES } from './byok-kms.service';
export { TAG_BYTES } from './byok-kms.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { KmsProvider } from './byok-kms.types';
export { KmsKeyStatus } from './byok-kms.types';
export { KmsOperation } from './byok-kms.types';
export { KmsCallerType } from './byok-kms.types';
export { IRotationPolicy } from './byok-kms.types';
export { ICustomerKmsKey } from './byok-kms.types';
export { IKmsAuditEntry } from './byok-kms.types';
export { IRegisterKeyInput } from './byok-kms.types';
export { IEnvelopeEncrypted } from './byok-kms.types';
export { IUnwrappedDataKey } from './byok-kms.types';
