/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `byok-kms` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ByokKmsModule } from './byok-kms.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ByokKmsController } from './byok-kms.controller';

// ─── Services ─────────────────────────────────────────────────────
export { LocalMasterKeyProvider, ByokKmsAuthService, IMasterKeyProvider } from './byok-kms.auth.service';
export { generateAlias, isValidAlias, generateDek, encryptWithDek, decryptWithDek, wrapDek, unwrapDek, envelopeHash, isRotationDue, daysUntilRotation, parseRotationPolicy, stringifyRotationPolicy, buildKeyRow, normalizeMasterKey, ALGORITHM, DEK_BYTES, IV_BYTES, TAG_BYTES } from './byok-kms.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { KmsProvider, KmsKeyStatus, KmsOperation, KmsCallerType, IRotationPolicy, ICustomerKmsKey, IKmsAuditEntry, IRegisterKeyInput, IEnvelopeEncrypted, IUnwrappedDataKey } from './byok-kms.types';
