/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `full-text-search` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { FullTextSearchModule } from './full-text-search.module';

// ─── Controllers ──────────────────────────────────────────────────
export { FullTextSearchController } from './full-text-search.controller';

// ─── Services ─────────────────────────────────────────────────────
export { FullTextSearchAuthService } from './full-text-search.auth.service';
export { normalizeText, tokenize, filterTokens, buildBigrams, buildIndexedDocument, parseQueryString, validateQuery, normalizeQuery, scoreDocument, normalizeScore, findTokenOffset, searchDocuments, buildSearchQuery, shouldIndexField } from './full-text-search.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_SEARCH_LIMIT, MAX_SEARCH_LIMIT, DEFAULT_MATCH_MODE, DEFAULT_SORT, MIN_TOKEN_LENGTH, MAX_TOKEN_LENGTH, MAX_PHRASE_TOKENS, SearchMatchMode, SearchSort, IIndexedField, IIndexDocumentInput, IIndexedDocument, ISearchToken, ISearchQuery, ISearchHit, ISearchResult } from './full-text-search.types';
