/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `automation-action-catalog` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AutomationActionCatalogAuthService } from './automation-action-catalog.auth.service';
export { indexActionCatalog } from './automation-action-catalog.service';
export { getActionSpec } from './automation-action-catalog.service';
export { groupActionsByCategory } from './automation-action-catalog.service';
export { listActionsByCategory } from './automation-action-catalog.service';
export { validateActionConfig } from './automation-action-catalog.service';
export { computeRetryDelay } from './automation-action-catalog.service';
export { isRollbackable } from './automation-action-catalog.service';
export { mergeActionCatalogs } from './automation-action-catalog.service';
export { capActionCatalog } from './automation-action-catalog.service';
export { serializeActionCatalog } from './automation-action-catalog.service';
export { summarizeActionCatalog } from './automation-action-catalog.service';
export { BUILTIN_ACTION_CATALOG } from './automation-action-catalog.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_ACTION_CATALOG_TYPES } from './automation-action-catalog.types';
export { MAX_ACTION_FIELDS_PER_TYPE } from './automation-action-catalog.types';
export { DEFAULT_ACTION_RETRY } from './automation-action-catalog.types';
export { AutomationActionCategory } from './automation-action-catalog.types';
export { IActionFieldSpec } from './automation-action-catalog.types';
export { IActionRetrySpec } from './automation-action-catalog.types';
export { IActionTypeSpec } from './automation-action-catalog.types';
export { IActionCatalog } from './automation-action-catalog.types';
export { IActionValidationIssue } from './automation-action-catalog.types';
export { IActionValidationResult } from './automation-action-catalog.types';
