/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `base-query` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { BaseQueryService } from './base-query.service';
