/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `services` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ComputedDependencyCollectorService, ICellBasicContext, IComputedImpactByTable, IComputedCollectResult, IFieldChangeSource } from './computed-dependency-collector.service';
export { ComputedEvaluatorService } from './computed-evaluator.service';
export { ComputedOrchestratorService } from './computed-orchestrator.service';
export { PersistedComputedBackfillService } from './persisted-computed-backfill.service';
export { RecordComputedUpdateService } from './record-computed-update.service';

// ─── Other public exports ─────────────────────────────────────────
export { RecordIdBatchStrategy, AutoNumberCursorStrategy, IComputedRowResult, PaginationBatchHandler, IPaginationContext, IRecordPaginationStrategy } from './computed-pagination.strategy';
export { buildResultImpact, IImpactGroup, IImpactMap, IResultImpact } from './computed-utils';
export { LinkCascadeResolver, ILinkEdge, IExplicitLinkSeed, IAllTableLinkSeed } from './link-cascade-resolver';
