/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `template-space-init` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { TemplateSpaceInitService, TEMPLATE_SPACE_ID } from './template-space.init.service';
