/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `org-ban-list` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { OrgBanListModule } from './org-ban-list.module';

// ─── Controllers ──────────────────────────────────────────────────
export { OrgBanListAdminController } from './org-ban-list.controller';

// ─── Services ─────────────────────────────────────────────────────
export { OrgBanListAuthService } from './org-ban-list.auth.service';
export { isBanEntryKind, isBanListMode, maxBanEntriesPerOrg, validateEntry, normalizeEntry, isEffective, decideForCandidate, appendAudit, buildAudit, revokeEntry, remainingLifetimeMs } from './org-ban-list.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_BAN_ENTRIES_PER_ORG, MAX_AUDIT_PER_ENTRY, BAN_ENTRY_VALUE_MAX, BAN_KINDS, BAN_MODES, BAN_KIND_LABELS, BanEntryKind, BanListMode, IBanEntry, IBanAudit } from './org-ban-list.types';
