/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-db-connection` feature module.
 */
export { DataDbConnectionModule } from './data-db-connection.module';
export { DataDbConnectionController } from './data-db-connection.controller';
export { DataDbConnectionService } from './data-db-connection.service';
export type {
  IDataDbConnection,
  DataDbConnectionKind,
} from './data-db-connection.types';
