#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/dotenv-flow-cli@1.1.1/node_modules/dotenv-flow-cli/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/dotenv-flow-cli@1.1.1/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/dotenv-flow-cli@1.1.1/node_modules/dotenv-flow-cli/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/dotenv-flow-cli@1.1.1/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/dotenv-flow-cli@1.1.1/node_modules/dotenv-flow-cli/cli.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/dotenv-flow-cli@1.1.1/node_modules/dotenv-flow-cli/cli.js" "$@"
fi
