#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/dist/bin/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/dist/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/dist/bin/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/dist/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/dist/bin/next" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.0_@playwright+test@1.57.0_react-dom@18._llhtesdt5w5ceq2y3ygllg6any/node_modules/next/dist/bin/next" "$@"
fi
