#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/profiling-node/scripts/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/profiling-node/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/profiling-node/scripts/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/profiling-node/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/profiling-node/scripts/prune-profiler-binaries.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/@sentry+profiling-node@10.22.0/node_modules/@sentry/profiling-node/scripts/prune-profiler-binaries.js" "$@"
fi
