#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/dist/bin/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/dist/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/dist/bin/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/dist/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/transliteration@2.3.5/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/dist/bin/slugify" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/transliteration@2.3.5/node_modules/transliteration/dist/bin/slugify" "$@"
fi
