#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules/ts-node/dist/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules/ts-node/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules/ts-node/dist/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules/ts-node/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules/ts-node/dist/bin-script.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/ts-node@10.9.2_@swc+core@1.13.3_@swc+helpers@0.5.17__@types+node@22.18.0_typescript@5.4.3/node_modules/ts-node/dist/bin-script.js" "$@"
fi
