#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/vitest@4.0.17_@opentelemetry+api@1.9.0_@types+node@22.18.0_happy-dom@15.11.6_jiti@2.6.1_jsdom_ijbsfg3tsdsrqshif2jtriex2e/node_modules/vitest/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/vitest@4.0.17_@opentelemetry+api@1.9.0_@types+node@22.18.0_happy-dom@15.11.6_jiti@2.6.1_jsdom_ijbsfg3tsdsrqshif2jtriex2e/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/louloulin/appx/teable/node_modules/.pnpm/vitest@4.0.17_@opentelemetry+api@1.9.0_@types+node@22.18.0_happy-dom@15.11.6_jiti@2.6.1_jsdom_ijbsfg3tsdsrqshif2jtriex2e/node_modules/vitest/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/vitest@4.0.17_@opentelemetry+api@1.9.0_@types+node@22.18.0_happy-dom@15.11.6_jiti@2.6.1_jsdom_ijbsfg3tsdsrqshif2jtriex2e/node_modules:/Users/louloulin/appx/teable/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/vitest@4.0.17_@opentelemetry+api@1.9.0_@types+node@22.18.0_happy-dom@15.11.6_jiti@2.6.1_jsdom_ijbsfg3tsdsrqshif2jtriex2e/node_modules/vitest/vitest.mjs" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/vitest@4.0.17_@opentelemetry+api@1.9.0_@types+node@22.18.0_happy-dom@15.11.6_jiti@2.6.1_jsdom_ijbsfg3tsdsrqshif2jtriex2e/node_modules/vitest/vitest.mjs" "$@"
fi
