/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `risk-control` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { RiskControlModule } from './risk-control.module';

// ─── Services ─────────────────────────────────────────────────────
export { RiskControlService } from './risk-control.service';
export { IRiskCheckType } from './risk-control.service';
