/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `map-view` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { MapViewModule } from './map-view.module';

// ─── Controllers ──────────────────────────────────────────────────
export { MapViewAuthController } from './map-view.auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { MapViewAuthService } from './map-view.auth.service';
export { isGeoSource, isValidLatLng, haversineKm, parseCombined, resolveMarker, applyRegionFilter, countryOf, inBoundingBox, inPolygon, clusterMarkers, averagePoint, pixelsToKm, validateConfig, IRowLike } from './map-view.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_MAP_ZOOM, DEFAULT_CLUSTER_RADIUS, MAX_MARKERS, IGeoPoint, GeoSource, IMapViewConfig, IMapMarker, IMapCluster, IBoundingBox, IMapRegionFilter } from './map-view.types';
