/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `map-view` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { MapViewModule } from './map-view.module';

// ─── Controllers ──────────────────────────────────────────────────
export { MapViewAuthController } from './map-view.auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { MapViewAuthService } from './map-view.auth.service';
export { isGeoSource } from './map-view.service';
export { isValidLatLng } from './map-view.service';
export { haversineKm } from './map-view.service';
export { parseCombined } from './map-view.service';
export { resolveMarker } from './map-view.service';
export { applyRegionFilter } from './map-view.service';
export { countryOf } from './map-view.service';
export { inBoundingBox } from './map-view.service';
export { inPolygon } from './map-view.service';
export { clusterMarkers } from './map-view.service';
export { averagePoint } from './map-view.service';
export { pixelsToKm } from './map-view.service';
export { validateConfig } from './map-view.service';
export { IRowLike } from './map-view.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_MAP_ZOOM } from './map-view.types';
export { DEFAULT_CLUSTER_RADIUS } from './map-view.types';
export { MAX_MARKERS } from './map-view.types';
export { IGeoPoint } from './map-view.types';
export { GeoSource } from './map-view.types';
export { IMapViewConfig } from './map-view.types';
export { IMapMarker } from './map-view.types';
export { IMapCluster } from './map-view.types';
export { IBoundingBox } from './map-view.types';
export { IMapRegionFilter } from './map-view.types';
