/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `e2e-test-utils` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { E2ETestUtilsAuthService } from './e2e-test-utils.auth.service';
export { validateFixture } from './e2e-test-utils.service';
export { validateOrg } from './e2e-test-utils.service';
export { validateCall } from './e2e-test-utils.service';
export { composeHeaders } from './e2e-test-utils.service';
export { buildCall } from './e2e-test-utils.service';
export { runAssertion } from './e2e-test-utils.service';
export { deepEqual } from './e2e-test-utils.service';
export { emptyResult } from './e2e-test-utils.service';
export { findUser } from './e2e-test-utils.service';
export { tokenFor } from './e2e-test-utils.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_USERS_PER_FIXTURE } from './e2e-test-utils.types';
export { MAX_FIXTURES } from './e2e-test-utils.types';
export { MAX_HEADER_COUNT } from './e2e-test-utils.types';
export { ITestUser } from './e2e-test-utils.types';
export { ITestOrg } from './e2e-test-utils.types';
export { ITestFixture } from './e2e-test-utils.types';
export { IApiCallInput } from './e2e-test-utils.types';
export { IApiCallResult } from './e2e-test-utils.types';
export { IAssertionInput } from './e2e-test-utils.types';
export { IAssertionResult } from './e2e-test-utils.types';
