/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `e2e-test-utils` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { E2ETestUtilsAuthService } from './e2e-test-utils.auth.service';
export { validateFixture, validateOrg, validateCall, composeHeaders, buildCall, runAssertion, deepEqual, emptyResult, findUser, tokenFor } from './e2e-test-utils.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_USERS_PER_FIXTURE, MAX_FIXTURES, MAX_HEADER_COUNT, ITestUser, ITestOrg, ITestFixture, IApiCallInput, IApiCallResult, IAssertionInput, IAssertionResult } from './e2e-test-utils.types';
