/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `conversion-pipeline` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ConversionPipelineAuthService } from './conversion-pipeline.auth.service';
export { validatePipeline, validateStep, matchesFilter, runStep, runPipeline, appendPipeline, reorderSteps } from './conversion-pipeline.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_STEPS_PER_PIPELINE, MAX_PIPELINES_PER_ORG, IPipelineFilter, IPipelineStep, IPipeline, IStepExecution, IPipelineRun } from './conversion-pipeline.types';
