/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `calculation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CalculationModule } from './calculation.module';

// ─── Services ─────────────────────────────────────────────────────
export { BatchService, IOpsData } from './batch.service';
export { FieldCalculationService, ITopoOrdersContext } from './field-calculation.service';
export { LinkService, IFkRecordMap, IFkRecordItem, IRecordMapByTableId, IFieldMapByTableId, ILinkCellContext } from './link.service';
export { ReferenceService, ITopoItem, ITopoItemWithRecords, IGraphItem, IRecordMap, IRecordItem, IRecordData, IRelatedRecordItem, ITopoLinkOrder } from './reference.service';
export { SystemFieldService } from './system-field.service';
