/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `seat-metering` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { SeatMeteringModule } from './seat-metering.module';

// ─── Controllers ──────────────────────────────────────────────────
export { SeatMeteringController } from './seat-metering.controller';

// ─── Services ─────────────────────────────────────────────────────
export { SeatMeteringAuthService } from './seat-metering.auth.service';
export { isSeatTier, isSeatStatus, unitPriceCents, validateAssignment, countsAsSeat, activeFraction, proratedSeats, buildCycle, nextCycle, maxSeatsPerOrg, totalActiveSeats, sumCycles, prorationUnit } from './seat-metering.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SEAT_PRICES_CENTS, SEAT_MAX_PER_ORG, SEAT_CYCLE_DAYS, SEAT_PRORATION_DENOMINATOR, SEAT_TIERS, SEAT_STATUSES, SeatTier, SeatStatus, ISeatAssignment, ISeatCycle } from './seat-metering.types';
