/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `seat-metering` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { SeatMeteringAuthService } from './seat-metering.auth.service';
export { isSeatTier } from './seat-metering.service';
export { isSeatStatus } from './seat-metering.service';
export { unitPriceCents } from './seat-metering.service';
export { validateAssignment } from './seat-metering.service';
export { countsAsSeat } from './seat-metering.service';
export { activeFraction } from './seat-metering.service';
export { proratedSeats } from './seat-metering.service';
export { buildCycle } from './seat-metering.service';
export { nextCycle } from './seat-metering.service';
export { maxSeatsPerOrg } from './seat-metering.service';
export { totalActiveSeats } from './seat-metering.service';
export { sumCycles } from './seat-metering.service';
export { prorationUnit } from './seat-metering.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SEAT_PRICES_CENTS } from './seat-metering.types';
export { SEAT_MAX_PER_ORG } from './seat-metering.types';
export { SEAT_CYCLE_DAYS } from './seat-metering.types';
export { SEAT_PRORATION_DENOMINATOR } from './seat-metering.types';
export { SEAT_TIERS } from './seat-metering.types';
export { SEAT_STATUSES } from './seat-metering.types';
export { SeatTier } from './seat-metering.types';
export { SeatStatus } from './seat-metering.types';
export { ISeatAssignment } from './seat-metering.types';
export { ISeatCycle } from './seat-metering.types';
