/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `guard` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Guards ───────────────────────────────────────────────────────
export { ShareAuthGuard } from './auth.guard';
export { ShareAuthLocalGuard } from './share-auth-local.guard';

// ─── Other public exports ─────────────────────────────────────────
export { SHARE_JWT_STRATEGY } from './constant';
export { IS_SHARE_LINK_VIEW, ShareLinkView } from './link-view.decorator';
export { IS_SHARE_SUBMIT_KEY, ShareSubmit } from './submit.decorator';
