/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `integration-connector` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { IntegrationConnectorAuthService } from './integration-connector.auth.service';
export { isValidProviderCode, resolveBundledProvider, generateWebhookSecret, hashPayload, signCatchHook, verifyCatchHookSignature, isValidInstallStatusTransition, buildInstallRow, applyInstallUpdate, buildCatchHookUrl, isDuplicateDelivery, resolveProvider } from './integration-connector.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_PROVIDERS, IntegrationCategory, IntegrationAuthType, IntegrationWebhookStyle, InstallStatus, EventDirection, DeliveryStatus, IIntegrationProvider, IIntegrationInstall, IIntegrationEventLog, ICreateInstallInput, IUpdateInstallInput, ICatchHookDelivery } from './integration-connector.types';
