/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `airtable-sync` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AirtableSyncAuthService } from './airtable-sync.auth.service';
export { hashFieldMap, parseFieldMap, stringifyFieldMap, isValidDirection, isValidStatusTransition, buildMappingRow, applyMappingUpdate, resolveConflict, deriveAllowedMutations, foldSyncRecords, isFieldMapStale, buildSyncRecordId } from './airtable-sync.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_SYNC_DIRECTIONS, SyncDirection, MappingStatus, SyncRecordState, SyncRunDirection, SyncRunStatus, IAirtableFieldMap, IAirtableConnection, IAirtableTableMapping, IAirtableSyncRecord, IAirtableSyncLog, ICreateConnectionInput, ICreateMappingInput, IUpdateMappingInput, ISyncCandidate, ISyncDiffSummary } from './airtable-sync.types';
