/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `license` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { LicenseModule } from './license.module';

// ─── Controllers ──────────────────────────────────────────────────
export { LicenseActivationController } from './license-activation.controller';
export { LicenseCapabilityController } from './license-capability.controller';

// ─── Services ─────────────────────────────────────────────────────
export { LicenseCapabilityService } from './license-capability.service';
export { LicenseCapability } from './license-capability.service';
export { LicenseService } from './license.service';

// ─── Guards ───────────────────────────────────────────────────────
export { LicenseCapabilityGuard } from './license-capability.guard';

// ─── Constants ────────────────────────────────────────────────────
export { NO_LICENSE_SENTINEL } from './license.constants';
export { ILicenseClaims } from './license.constants';
export { IResolvedLicense } from './license.constants';
