/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `agent-orchestrator` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AgentOrchestratorModule, __testing__buildCuppyTools } from './agent-orchestrator.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AgentOrchestratorController } from './agent-orchestrator.controller';
export { CuppyController } from './cuppy.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AgentOrchestratorService, ILlmCallResult, ILlmClient, IPromptRouter } from './agent-orchestrator.service';

// ─── Other public exports ─────────────────────────────────────────
export { ConversationStore, InMemoryAdapterRegistry, ConversationId, UserId, InboundMessage, OutboundReply, Tool, ConversationContext, IMAdapter, AdapterRegistry } from './agent-orchestrator';
export { BuiltInEchoLlm, IEchoLlmArgs, IEchoLlmResult, ICuppyEchoLlm } from './built-in-echo-llm';
