/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `license-key-self` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { LicenseKeySelfModule } from './license-key-self.module';

// ─── Controllers ──────────────────────────────────────────────────
export { LicenseKeySelfAdminController } from './license-key-self.admin.controller';

// ─── Services ─────────────────────────────────────────────────────
export { LicenseKeySelfAuthService } from './license-key-self.auth.service';
export { isLicenseTier } from './license-key-self.service';
export { tierRank } from './license-key-self.service';
export { changeDirection } from './license-key-self.service';
export { isReachable } from './license-key-self.service';
export { validateTierChange } from './license-key-self.service';
export { cooldownStatus } from './license-key-self.service';
export { prorationPreview } from './license-key-self.service';
export { buildAudit } from './license-key-self.service';
export { nextCooldownFrom } from './license-key-self.service';
export { appendAudit } from './license-key-self.service';

// ─── Guards ───────────────────────────────────────────────────────
export { LicenseKeySelfAdminGuard } from './license-key-self.admin.guard';

// ─── Types / interfaces ───────────────────────────────────────────
export { LICENSE_TIERS } from './license-key-self.types';
export { LICENSE_TIER_RANK } from './license-key-self.types';
export { LICENSE_COOLDOWN_MS } from './license-key-self.types';
export { LICENSE_MAX_SCHEDULE_MS } from './license-key-self.types';
export { LICENSE_PRORATION_CYCLE_DAYS } from './license-key-self.types';
export { LICENSE_TIER_CENTS } from './license-key-self.types';
export { LicenseTier } from './license-key-self.types';
export { TierChangeDirection } from './license-key-self.types';
export { ITierChangeRequest } from './license-key-self.types';
export { ITierChangeAudit } from './license-key-self.types';
export { IProrationPreview } from './license-key-self.types';
export { ICooldownStatus } from './license-key-self.types';
