/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `grid-pro-view` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { GridProViewModule } from './grid-pro-view.module';

// ─── Controllers ──────────────────────────────────────────────────
export { GridProViewAuthController } from './grid-pro-view.auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { GridProViewAuthService } from './grid-pro-view.auth.service';
export { renderGridPro, scrollOffsetForRow, windowCells, withinRowCap, columnSummary, findCell, buildSpec } from './grid-pro-view.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { GRID_PRO_DEFAULT_ROW_HEIGHT, GRID_PRO_DEFAULT_HEADER_HEIGHT, GRID_PRO_MAX_ROWS, GridProCellData, GridProCellRender, GridProViewSpec, GridProRenderResult } from './grid-pro-view.types';
