/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `grid-pro-view` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { GridProViewModule } from './grid-pro-view.module';

// ─── Controllers ──────────────────────────────────────────────────
export { GridProViewAuthController } from './grid-pro-view.auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { GridProViewAuthService } from './grid-pro-view.auth.service';
export { renderGridPro } from './grid-pro-view.service';
export { scrollOffsetForRow } from './grid-pro-view.service';
export { windowCells } from './grid-pro-view.service';
export { withinRowCap } from './grid-pro-view.service';
export { columnSummary } from './grid-pro-view.service';
export { findCell } from './grid-pro-view.service';
export { buildSpec } from './grid-pro-view.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { GRID_PRO_DEFAULT_ROW_HEIGHT } from './grid-pro-view.types';
export { GRID_PRO_DEFAULT_HEADER_HEIGHT } from './grid-pro-view.types';
export { GRID_PRO_MAX_ROWS } from './grid-pro-view.types';
export { GridProCellData } from './grid-pro-view.types';
export { GridProCellRender } from './grid-pro-view.types';
export { GridProViewSpec } from './grid-pro-view.types';
export { GridProRenderResult } from './grid-pro-view.types';
