/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `risk-policy` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { RiskPolicyAuthService } from './risk-policy.auth.service';
export { isRiskBand } from './risk-policy.service';
export { isRiskAction } from './risk-policy.service';
export { isRiskSignalKind } from './risk-policy.service';
export { maxRulesPerPolicy } from './risk-policy.service';
export { maxSignalsPerRule } from './risk-policy.service';
export { maxScore } from './risk-policy.service';
export { minScore } from './risk-policy.service';
export { bandFromScore } from './risk-policy.service';
export { validateSignal } from './risk-policy.service';
export { validateRule } from './risk-policy.service';
export { validatePolicy } from './risk-policy.service';
export { normalizePolicy } from './risk-policy.service';
export { totalWeight } from './risk-policy.service';
export { ruleFires } from './risk-policy.service';
export { evaluate } from './risk-policy.service';
export { shouldAudit } from './risk-policy.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { RISK_BANDS } from './risk-policy.types';
export { RISK_ACTIONS } from './risk-policy.types';
export { RISK_SIGNAL_KINDS } from './risk-policy.types';
export { BAND_THRESHOLDS } from './risk-policy.types';
export { MAX_RULES_PER_POLICY } from './risk-policy.types';
export { MAX_SIGNALS_PER_RULE } from './risk-policy.types';
export { MAX_WEIGHT } from './risk-policy.types';
export { DEFAULT_RISK_SCORE_FLOOR } from './risk-policy.types';
export { DEFAULT_RISK_SCORE_CEIL } from './risk-policy.types';
export { RISK_BAND_LABELS } from './risk-policy.types';
export { RISK_ACTION_LABELS } from './risk-policy.types';
export { RiskAction } from './risk-policy.types';
export { RiskBand } from './risk-policy.types';
export { RiskSignalKind } from './risk-policy.types';
export { IRiskSignal } from './risk-policy.types';
export { IRiskRule } from './risk-policy.types';
export { IRiskPolicy } from './risk-policy.types';
export { IRiskDecision } from './risk-policy.types';
