/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `risk-policy` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { RiskPolicyModule } from './risk-policy.module';

// ─── Controllers ──────────────────────────────────────────────────
export { RiskPolicyAdminController } from './risk-policy.controller';

// ─── Services ─────────────────────────────────────────────────────
export { RiskPolicyAuthService } from './risk-policy.auth.service';
export { isRiskBand, isRiskAction, isRiskSignalKind, maxRulesPerPolicy, maxSignalsPerRule, maxScore, minScore, bandFromScore, validateSignal, validateRule, validatePolicy, normalizePolicy, totalWeight, ruleFires, evaluate, shouldAudit } from './risk-policy.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { RISK_BANDS, RISK_ACTIONS, RISK_SIGNAL_KINDS, BAND_THRESHOLDS, MAX_RULES_PER_POLICY, MAX_SIGNALS_PER_RULE, MAX_WEIGHT, DEFAULT_RISK_SCORE_FLOOR, DEFAULT_RISK_SCORE_CEIL, RISK_BAND_LABELS, RISK_ACTION_LABELS, RiskAction, RiskBand, RiskSignalKind, IRiskSignal, IRiskRule, IRiskPolicy, IRiskDecision } from './risk-policy.types';
