/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `operations` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Other public exports ─────────────────────────────────────────
export { ConvertFieldV2Operation } from './convert-field-v2.operation';
export { ConvertFieldOperation } from './convert-field.operation';
export { IConvertFieldPayload } from './convert-field.operation';
export { CreateFieldsOperation } from './create-fields.operation';
export { ICreateFieldsPayload } from './create-fields.operation';
export { CreateRecordsOperation } from './create-records.operation';
export { ICreateRecordsPayload } from './create-records.operation';
export { CreateViewOperation } from './create-view.operation';
export { ICreateViewPayload } from './create-view.operation';
export { DeleteFieldsOperation } from './delete-fields.operation';
export { IDeleteFieldsPayload } from './delete-fields.operation';
export { DeleteRecordsOperation } from './delete-records.operation';
export { IDeleteRecordsPayload } from './delete-records.operation';
export { DeleteViewOperation } from './delete-view.operation';
export { IDeleteViewPayload } from './delete-view.operation';
export { PasteSelectionOperation } from './paste-selection.operation';
export { IPasteSelectionPayload } from './paste-selection.operation';
export { UpdateRecordsOrderOperation } from './update-records-order.operation';
export { IUpdateRecordsOrderPayload } from './update-records-order.operation';
export { UpdateRecordsOperation } from './update-records.operation';
export { IUpdateRecordsPayload } from './update-records.operation';
export { UpdateViewOperation } from './update-view.operation';
export { IUpdateViewPayload } from './update-view.operation';
