/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `saml` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { SamlModule } from './saml.module';

// ─── Controllers ──────────────────────────────────────────────────
export { SamlController } from './saml.controller';

// ─── Services ─────────────────────────────────────────────────────
export { SamlAuthService } from './saml.auth.service';
export { buildAuthnRequest, buildRedirectUrl, buildMetadataXml, parseSamlResponse, extractEmailFromAssertion, extractDisplayName, hashAuthnRequest, deflateSamlRequest, IBuildAuthnRequestInput } from './saml.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { ISamlProviderRow, ISamlLoginInput, ISamlLoginResult, ISamlAssertion, ISamlMetadata } from './saml.types';
