/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `kms-encryption` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { KmsEncryptionAuthService } from './kms-encryption.auth.service';
export { isValidAlgorithm, isValidKeyState, randomBytes, validateCreateKeyInput, validateEncryptInput, byteLengthUtf8, toBase64, fromBase64, makeIv, makeDek, encryptWithDek, decryptWithDek, buildEnvelope, parseEnvelope, pickEncryptionKey, authTagBytes, canDecryptWith, IKmsProvider } from './kms-encryption.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_ENCRYPTION_ALGORITHM, DEFAULT_IV_BYTES, DEFAULT_AUTH_TAG_BITS, DEFAULT_DEK_BYTES, MAX_PLAINTEXT_BYTES, KEY_ID_PREFIX, EncryptionAlgorithm, KeyState, IEncryptionKey, IEncryptionEnvelope, IEncryptInput, ICreateKeyInput } from './kms-encryption.types';
