/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `email-domain-claim` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { EmailDomainClaimModule } from './email-domain-claim.module';

// ─── Controllers ──────────────────────────────────────────────────
export { EmailDomainClaimController } from './email-domain-claim.controller';

// ─── Services ─────────────────────────────────────────────────────
export { EmailDomainClaimAuthService } from './email-domain-claim.auth.service';
export { isClaimStatus, isClaimMode, defaultTokenLength, maxDomainsPerOrg, normalizeDomain, validateDomain, generateToken, renderVerificationRecord, parseVerificationValue, validateClaim, normalizeClaim, applyDnsCheck, matchCandidate, shouldAutoJoin, makeAuditEntry, countVerified, canClaimMore } from './email-domain-claim.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_TOKEN_LENGTH, MAX_DOMAINS_PER_ORG, MAX_DNS_CHECK_AGE_MS, MIN_DOMAIN_LENGTH, MAX_DOMAIN_LENGTH, CLAIM_STATUSES, CLAIM_MODES, DOMAIN_VERIFICATION_PREFIX, CLAIM_STATUS_LABELS, CLAIM_MODE_LABELS, ClaimStatus, ClaimMode, DnsRecordKind, IEmailDomainClaim, IClaimAuditEntry, IAutoJoinCandidate, IEmailDomainClaimOptions } from './email-domain-claim.types';
