/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `email-domain-claim` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { EmailDomainClaimModule } from './email-domain-claim.module';

// ─── Services ─────────────────────────────────────────────────────
export { EmailDomainClaimAuthService } from './email-domain-claim.auth.service';
export { isClaimStatus } from './email-domain-claim.service';
export { isClaimMode } from './email-domain-claim.service';
export { defaultTokenLength } from './email-domain-claim.service';
export { maxDomainsPerOrg } from './email-domain-claim.service';
export { normalizeDomain } from './email-domain-claim.service';
export { validateDomain } from './email-domain-claim.service';
export { generateToken } from './email-domain-claim.service';
export { renderVerificationRecord } from './email-domain-claim.service';
export { parseVerificationValue } from './email-domain-claim.service';
export { validateClaim } from './email-domain-claim.service';
export { normalizeClaim } from './email-domain-claim.service';
export { applyDnsCheck } from './email-domain-claim.service';
export { matchCandidate } from './email-domain-claim.service';
export { shouldAutoJoin } from './email-domain-claim.service';
export { makeAuditEntry } from './email-domain-claim.service';
export { countVerified } from './email-domain-claim.service';
export { canClaimMore } from './email-domain-claim.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_TOKEN_LENGTH } from './email-domain-claim.types';
export { MAX_DOMAINS_PER_ORG } from './email-domain-claim.types';
export { MAX_DNS_CHECK_AGE_MS } from './email-domain-claim.types';
export { MIN_DOMAIN_LENGTH } from './email-domain-claim.types';
export { MAX_DOMAIN_LENGTH } from './email-domain-claim.types';
export { CLAIM_STATUSES } from './email-domain-claim.types';
export { CLAIM_MODES } from './email-domain-claim.types';
export { DOMAIN_VERIFICATION_PREFIX } from './email-domain-claim.types';
export { CLAIM_STATUS_LABELS } from './email-domain-claim.types';
export { CLAIM_MODE_LABELS } from './email-domain-claim.types';
export { ClaimStatus } from './email-domain-claim.types';
export { ClaimMode } from './email-domain-claim.types';
export { DnsRecordKind } from './email-domain-claim.types';
export { IEmailDomainClaim } from './email-domain-claim.types';
export { IClaimAuditEntry } from './email-domain-claim.types';
export { IAutoJoinCandidate } from './email-domain-claim.types';
export { IEmailDomainClaimOptions } from './email-domain-claim.types';
