/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `stripe-webhook` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { StripeWebhookAuthService } from './stripe-webhook.auth.service';
export { isStripeEventKind } from './stripe-webhook.service';
export { validateSignature } from './stripe-webhook.service';
export { mapEventToAction } from './stripe-webhook.service';
export { matchLineItem } from './stripe-webhook.service';
export { reconcileInvoice } from './stripe-webhook.service';
export { summarizeEntries } from './stripe-webhook.service';
export { applyReconciledEntries } from './stripe-webhook.service';
export { dedupeEvents } from './stripe-webhook.service';
export { capEntries } from './stripe-webhook.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { STRIPE_EVENT_KINDS } from './stripe-webhook.types';
export { RECONCILIATION_STATUSES } from './stripe-webhook.types';
export { RECONCILIATION_TOLERANCE_CENTS } from './stripe-webhook.types';
export { STRIPE_WEBHOOK_TOLERANCE_SECONDS } from './stripe-webhook.types';
export { MAX_RECONCILIATION_ENTRIES } from './stripe-webhook.types';
export { StripeEventKind } from './stripe-webhook.types';
export { ReconciliationStatus } from './stripe-webhook.types';
export { IStripeLineItem } from './stripe-webhook.types';
export { IStripeInvoice } from './stripe-webhook.types';
export { IStripeEvent } from './stripe-webhook.types';
export { IReconciliationEntry } from './stripe-webhook.types';
export { IReconciliationSummary } from './stripe-webhook.types';
export { IInternalBillableLine } from './stripe-webhook.types';
export { ReconciliationAction } from './stripe-webhook.types';
