/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `stripe-webhook` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { StripeWebhookAuthService } from './stripe-webhook.auth.service';
export { isStripeEventKind, validateSignature, mapEventToAction, matchLineItem, reconcileInvoice, summarizeEntries, applyReconciledEntries, dedupeEvents, capEntries } from './stripe-webhook.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { STRIPE_EVENT_KINDS, RECONCILIATION_STATUSES, RECONCILIATION_TOLERANCE_CENTS, STRIPE_WEBHOOK_TOLERANCE_SECONDS, MAX_RECONCILIATION_ENTRIES, StripeEventKind, ReconciliationStatus, IStripeLineItem, IStripeInvoice, IStripeEvent, IReconciliationEntry, IReconciliationSummary, IInternalBillableLine, ReconciliationAction } from './stripe-webhook.types';
