/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `view-permission` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ViewPermissionModule } from './view-permission.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ViewPermissionController } from './view-permission.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ViewPermissionService } from './view-permission.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { VIEW_PERMISSIONS } from './view-permission.types';
export { ViewPermissionLevel } from './view-permission.types';
export { ViewSubjectKind } from './view-permission.types';
export { IViewPermissionRow } from './view-permission.types';
export { IViewPermissionInput } from './view-permission.types';
export { IResolveArgs } from './view-permission.types';
export { IViewPermissionService } from './view-permission.types';
