/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `env-config` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { EnvConfigAuthService } from './env-config.auth.service';
export { validateEnvSpec, resolveOne, resolveAll, required, optional, boolEnv, numberEnv, banner } from './env-config.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_ENV_SPECS, MAX_ENV_VALUE_LENGTH, EnvKind, IEnvSpec, IEnvReport } from './env-config.types';
