/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `storage-metering` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { StorageMeteringModule } from './storage-metering.module';

// ─── Controllers ──────────────────────────────────────────────────
export { StorageMeteringController } from './storage-metering.controller';

// ─── Services ─────────────────────────────────────────────────────
export { StorageMeteringAuthService } from './storage-metering.auth.service';
export { isStorageKind, validateSample, emptyByKind, attributeSamples, normalizeAttribution, bytesToGb, billableCents, billableLine, sumBillable, appendSample, latestPerKind, attributionFromLatest } from './storage-metering.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { STORAGE_CENTS_PER_GB, STORAGE_BYTES_PER_GB, STORAGE_KINDS, STORAGE_MAX_KINDS_PER_BASE, STORAGE_MAX_SAMPLES_PER_BASE, StorageKind, IStorageSample, IStorageAttribution, IStorageBillableLine } from './storage-metering.types';
