/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `backup` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { BackupModule } from './backup.module';

// ─── Controllers ──────────────────────────────────────────────────
export { BackupController } from './backup.controller';

// ─── Services ─────────────────────────────────────────────────────
export { InMemoryBackupStore } from './backup.service';
export { BackupService } from './backup.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MergeMode } from './backup.types';
export { IBackupManifest } from './backup.types';
export { ICreateBackupInput } from './backup.types';
export { IRestoreInput } from './backup.types';
export { ISnapshotRow } from './backup.types';
export { IRestoreLogRow } from './backup.types';
export { IBackupStore } from './backup.types';
