/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `backup` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { BackupModule } from './backup.module';

// ─── Controllers ──────────────────────────────────────────────────
export { BackupController } from './backup.controller';

// ─── Services ─────────────────────────────────────────────────────
export { InMemoryBackupStore, BackupService } from './backup.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MergeMode, IBackupManifest, ICreateBackupInput, IRestoreInput, ISnapshotRow, IRestoreLogRow, IBackupStore } from './backup.types';
