/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `computed-outbox-trigger` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ComputedOutboxWakeupConsumerModule } from './computed-outbox-wakeup-consumer.module';
export { ComputedOutboxWakeupProducerModule } from './computed-outbox-wakeup-producer.module';
export { createRoleAwareWakeupPublisher } from './computed-outbox-wakeup-producer.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ComputedOutboxAdminController } from './computed-outbox-admin.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ComputedOutboxAnomalyService } from './computed-outbox-anomaly.service';
export { buildComputedOutboxAnomalyGroupKey } from './computed-outbox-anomaly.service';
export { groupComputedOutboxAnomalies } from './computed-outbox-anomaly.service';
export { ComputedOutboxAnomaly } from './computed-outbox-anomaly.service';
export { ComputedOutboxAnomalyGroup } from './computed-outbox-anomaly.service';
export { ComputedOutboxBaseAdmissionLeaseLostError } from './computed-outbox-base-admission.service';
export { ComputedOutboxBaseAdmissionService } from './computed-outbox-base-admission.service';
export { ComputedOutboxBaseAdmissionResult } from './computed-outbox-base-admission.service';
export { ComputedOutboxBaseAdmissionPermit } from './computed-outbox-base-admission.service';
export { ComputedOutboxMonitorService } from './computed-outbox-monitor.service';
export { ComputedOutboxMonitorSnapshot } from './computed-outbox-monitor.service';
export { ComputedOutboxRedriveService } from './computed-outbox-redrive.service';

// ─── Constants ────────────────────────────────────────────────────
export { COMPUTED_OUTBOX_WAKEUP_QUEUE } from './constants';
export { COMPUTED_OUTBOX_WAKEUP_JOB } from './constants';
export { COMPUTED_OUTBOX_WAKEUP_PUBLISHER } from './constants';
export { COMPUTED_OUTBOX_COMPLETED_RETENTION_COUNT } from './constants';
export { COMPUTED_OUTBOX_RECENT_COMPLETED_LIMIT } from './constants';
export { COMPUTED_OUTBOX_RECENT_FAILED_LIMIT } from './constants';
export { COMPUTED_OUTBOX_ANOMALY_GROUP_SAMPLE_LIMIT } from './constants';
export { COMPUTED_OUTBOX_ANOMALY_FETCH_CAP } from './constants';

// ─── Other public exports ─────────────────────────────────────────
export { BullMqComputedOutboxWakeupProcessor } from './bullmq-computed-outbox-wakeup.processor';
export { BullMqComputedOutboxWakeupPublisher } from './bullmq-computed-outbox-wakeup.publisher';
export { ComputedOutboxWakeupPublishTimeoutError } from './bullmq-computed-outbox-wakeup.publisher';
export { ComputedOutboxWakeupRecoveryInProgressError } from './bullmq-computed-outbox-wakeup.publisher';
export { ComputedOutboxTriggerMetrics } from './computed-outbox-trigger.metrics';
export { ComputedOutboxConsumeOutcome } from './computed-outbox-trigger.metrics';
export { ComputedOutboxPublishOutcome } from './computed-outbox-trigger.metrics';
export { ComputedOutboxPublishSkipReason } from './computed-outbox-trigger.metrics';
export { ComputedOutboxRuntimeSnapshot } from './computed-outbox-trigger.metrics';
export { ComputedOutboxWakeupHandler } from './computed-outbox-wakeup.handler';
export { ComputedOutboxWakeupHandlerOutcome } from './computed-outbox-wakeup.handler';
export { IComputedOutboxWakeupAppPublisher } from './computed-outbox-wakeup.publisher';
export { computedOutboxWakeupWireSchema } from './computed-outbox-wakeup.wire';
export { ComputedOutboxWakeupWire } from './computed-outbox-wakeup.wire';
export * from './map-with-concurrency';
