/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `computed-outbox-trigger` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ComputedOutboxWakeupConsumerModule } from './computed-outbox-wakeup-consumer.module';
export { ComputedOutboxWakeupProducerModule, createRoleAwareWakeupPublisher } from './computed-outbox-wakeup-producer.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ComputedOutboxAdminController } from './computed-outbox-admin.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ComputedOutboxAnomalyService, buildComputedOutboxAnomalyGroupKey, groupComputedOutboxAnomalies, ComputedOutboxAnomaly, ComputedOutboxAnomalyGroup } from './computed-outbox-anomaly.service';
export { ComputedOutboxBaseAdmissionLeaseLostError, ComputedOutboxBaseAdmissionService, ComputedOutboxBaseAdmissionResult, ComputedOutboxBaseAdmissionPermit } from './computed-outbox-base-admission.service';
export { ComputedOutboxMonitorService, ComputedOutboxMonitorSnapshot } from './computed-outbox-monitor.service';
export { ComputedOutboxRedriveService } from './computed-outbox-redrive.service';

// ─── Constants ────────────────────────────────────────────────────
export { COMPUTED_OUTBOX_WAKEUP_QUEUE, COMPUTED_OUTBOX_WAKEUP_JOB, COMPUTED_OUTBOX_WAKEUP_PUBLISHER, COMPUTED_OUTBOX_COMPLETED_RETENTION_COUNT, COMPUTED_OUTBOX_RECENT_COMPLETED_LIMIT, COMPUTED_OUTBOX_RECENT_FAILED_LIMIT, COMPUTED_OUTBOX_ANOMALY_GROUP_SAMPLE_LIMIT, COMPUTED_OUTBOX_ANOMALY_FETCH_CAP } from './constants';

// ─── Other public exports ─────────────────────────────────────────
export { BullMqComputedOutboxWakeupProcessor } from './bullmq-computed-outbox-wakeup.processor';
export { BullMqComputedOutboxWakeupPublisher, ComputedOutboxWakeupPublishTimeoutError, ComputedOutboxWakeupRecoveryInProgressError } from './bullmq-computed-outbox-wakeup.publisher';
export { ComputedOutboxTriggerMetrics, ComputedOutboxConsumeOutcome, ComputedOutboxPublishOutcome, ComputedOutboxPublishSkipReason, ComputedOutboxRuntimeSnapshot } from './computed-outbox-trigger.metrics';
export { ComputedOutboxWakeupHandler, ComputedOutboxWakeupHandlerOutcome } from './computed-outbox-wakeup.handler';
export { IComputedOutboxWakeupAppPublisher } from './computed-outbox-wakeup.publisher';
export { computedOutboxWakeupWireSchema, ComputedOutboxWakeupWire } from './computed-outbox-wakeup.wire';
export * from './map-with-concurrency';
