/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `base` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { BaseModule } from './base.module';

// ─── Controllers ──────────────────────────────────────────────────
export { BaseController } from './base.controller';

// ─── Services ─────────────────────────────────────────────────────
export { BaseDataDbMoveService } from './base-data-db-move.service';
export { BaseDuplicateV2Service } from './base-duplicate-v2.service';
export { BaseDuplicateService } from './base-duplicate.service';
export { BaseExportV2Service } from './base-export-v2.service';
export { BaseExportService } from './base-export.service';
export { BaseImportService, formatBaseImportError, IBaseImportProgress, BaseImportProgressCallback } from './base-import.service';
export { BASE_META_MOVE_SERVICE, IBaseMetaMoveService } from './base-meta-move.service';
export { BaseService } from './base.service';
export { DbConnectionService } from './db-connection.service';

// ─── Constants ────────────────────────────────────────────────────
export { activeBaseDataDbMoveJobStates, cancelableBaseDataDbMoveJobStates, baseDataDbMovingErrorCode, baseDataDbMoveProgressWeights, IBaseDataDbMovePhase } from './base-data-db-move.constants';

// ─── Utilities ────────────────────────────────────────────────────
export { isCrossSpaceReferenceAllowed, parseFieldJson, extractForeignTableId, collectCrossSpaceAffectedFieldIds, computeCrossSpaceFieldLevels, sortByConversionDepth, ICrossSpaceFieldInput, ICollectCrossSpaceAffectedArgs } from './cross-space-detection.util';
export { replaceExpressionFieldIds, replaceJsonStringFieldIds, replaceStringByMap, replaceTimeZoneDeep, replaceWorkflowTimeZoneDeep, adaptStructureTimeZone, replaceDefaultUrl, mergeLinkFieldTableMaps, ILinkFieldTableInfo, ILinkFieldTableMap } from './utils';

// ─── Other public exports ─────────────────────────────────────────
export { BatchProcessor } from './BatchProcessor.class';
export { EXCLUDE_SYSTEM_FIELDS, DEFAULT_EXPRESSION } from './constant';
