/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `timeline-view` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TimelineViewModule } from './timeline-view.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TimelineViewAuthController } from './timeline-view.auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TimelineViewAuthService } from './timeline-view.auth.service';
export { isValidDependencyType, isValidProgress, daysBetween, addDays, validateTimelineView, buildTimelineViewRow, buildTaskRow, buildDependencyRow, detectCycle, computeCriticalPath, renderGanttBars, DEPENDENCY_TYPES, IGanttBar } from './timeline-view.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MS_PER_DAY, DEFAULT_PROGRESS, DependencyType, ITimelineTask, ITimelineDependency, ITimelineView, ICriticalPathTask, ICriticalPathResult, ICreateTimelineViewInput, ICreateTaskInput, ICreateDependencyInput } from './timeline-view.types';
