/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `timeline-view` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TimelineViewModule } from './timeline-view.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TimelineViewAuthController } from './timeline-view.auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TimelineViewAuthService } from './timeline-view.auth.service';
export { isValidDependencyType } from './timeline-view.service';
export { isValidProgress } from './timeline-view.service';
export { daysBetween } from './timeline-view.service';
export { addDays } from './timeline-view.service';
export { validateTimelineView } from './timeline-view.service';
export { buildTimelineViewRow } from './timeline-view.service';
export { buildTaskRow } from './timeline-view.service';
export { buildDependencyRow } from './timeline-view.service';
export { detectCycle } from './timeline-view.service';
export { computeCriticalPath } from './timeline-view.service';
export { renderGanttBars } from './timeline-view.service';
export { DEPENDENCY_TYPES } from './timeline-view.service';
export { IGanttBar } from './timeline-view.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MS_PER_DAY } from './timeline-view.types';
export { DEFAULT_PROGRESS } from './timeline-view.types';
export { DependencyType } from './timeline-view.types';
export { ITimelineTask } from './timeline-view.types';
export { ITimelineDependency } from './timeline-view.types';
export { ITimelineView } from './timeline-view.types';
export { ICriticalPathTask } from './timeline-view.types';
export { ICriticalPathResult } from './timeline-view.types';
export { ICreateTimelineViewInput } from './timeline-view.types';
export { ICreateTaskInput } from './timeline-view.types';
export { ICreateDependencyInput } from './timeline-view.types';
