/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `record-history-retention` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { PrismaSubscriberLookup } from './record-history-retention.auth.service';
export { RecordHistoryRetentionAuthService } from './record-history-retention.auth.service';
export { ISubscriberLookup } from './record-history-retention.auth.service';
export { resolveRetention } from './record-history-retention.service';
export { isExpired } from './record-history-retention.service';
export { suggestCron } from './record-history-retention.service';
export { listPolicies } from './record-history-retention.service';
export { describeResolution } from './record-history-retention.service';
export { PLAN_RETENTION_POLICIES } from './record-history-retention.service';
export { DEFAULT_PURGE_CRON } from './record-history-retention.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PlanTier } from './record-history-retention.types';
export { IPlanRetentionPolicy } from './record-history-retention.types';
export { ISubscriberContext } from './record-history-retention.types';
export { IResolvedRetention } from './record-history-retention.types';
export { IRetentionQueryResult } from './record-history-retention.types';
