/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `record-history-retention` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { PrismaSubscriberLookup, RecordHistoryRetentionAuthService, ISubscriberLookup } from './record-history-retention.auth.service';
export { resolveRetention, isExpired, suggestCron, listPolicies, describeResolution, PLAN_RETENTION_POLICIES, DEFAULT_PURGE_CRON } from './record-history-retention.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PlanTier, IPlanRetentionPolicy, ISubscriberContext, IResolvedRetention, IRetentionQueryResult } from './record-history-retention.types';
