/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-field` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AiFieldAuthService } from './ai-field.auth.service';
export { isValidOperation, isValidModel, isValidStatusTransition, validateConfig, stringifyConfig, hashConfig, estimateTokens, renderPrompt, buildDefaultPrompt, buildAiFieldRow, guardOutput, foldRuns, buildRunRow, parseSourceFieldIds, parseConfig, buildTemplateRow, DEFAULT_TEMPLATES } from './ai-field.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_OPERATIONS, SUPPORTED_MODELS, AiFieldOperation, AiFieldStatus, AiRunStatus, IClassifyConfig, ISummarizeConfig, ITranslateConfig, AiFieldConfig, IAiField, IAiFieldRun, IAiFieldTemplate, ICreateAiFieldInput, IUpdateAiFieldInput, IRunAiFieldInput, IAiRunResult, IUsageAggregate, ICreateTemplateInput } from './ai-field.types';
