/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `open-api` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { UndoRedoModule } from './undo-redo.module';

// ─── Controllers ──────────────────────────────────────────────────
export { UndoRedoController } from './undo-redo.controller';

// ─── Services ─────────────────────────────────────────────────────
export { UndoRedoService, X_TEABLE_UNDO_REDO_ENGINE_HEADER, IUndoRedoEngine } from './undo-redo.service';

// ─── Other public exports ─────────────────────────────────────────
export { UNDO_REDO_ENGINE_PREFERENCE_TTL_SECONDS, buildUndoRedoEnginePreferenceKey } from './undo-redo-engine-preference';
