/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `approval-workflow` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ApprovalWorkflowModule } from './approval-workflow.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ApprovalWorkflowController } from './approval-workflow.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ApprovalWorkflowAuthService } from './approval-workflow.auth.service';
export { isValidStrategy, isValidStatus, isValidDecision, validateWorkflowInput, validateRequestInput, validateCastInput, computeProgress, isApproverFor, hasAlreadyDecided, computeExpiresAt, isExpiredBy } from './approval-workflow.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_APPROVER_LIMIT, DEFAULT_EXPIRES_HOURS, ApprovalStrategy, ApprovalStatus, ApprovalDecision, IApprovalWorkflow, IApprovalRequest, IApprovalDecisionRow, ICreateWorkflowInput, ICreateRequestInput, ICastDecisionInput, IWorkflowProgress } from './approval-workflow.types';
