/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `approval-workflow` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ApprovalWorkflowModule } from './approval-workflow.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ApprovalWorkflowController } from './approval-workflow.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ApprovalWorkflowAuthService } from './approval-workflow.auth.service';
export { isValidStrategy } from './approval-workflow.service';
export { isValidStatus } from './approval-workflow.service';
export { isValidDecision } from './approval-workflow.service';
export { validateWorkflowInput } from './approval-workflow.service';
export { validateRequestInput } from './approval-workflow.service';
export { validateCastInput } from './approval-workflow.service';
export { computeProgress } from './approval-workflow.service';
export { isApproverFor } from './approval-workflow.service';
export { hasAlreadyDecided } from './approval-workflow.service';
export { computeExpiresAt } from './approval-workflow.service';
export { isExpiredBy } from './approval-workflow.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_APPROVER_LIMIT } from './approval-workflow.types';
export { DEFAULT_EXPIRES_HOURS } from './approval-workflow.types';
export { ApprovalStrategy } from './approval-workflow.types';
export { ApprovalStatus } from './approval-workflow.types';
export { ApprovalDecision } from './approval-workflow.types';
export { IApprovalWorkflow } from './approval-workflow.types';
export { IApprovalRequest } from './approval-workflow.types';
export { IApprovalDecisionRow } from './approval-workflow.types';
export { ICreateWorkflowInput } from './approval-workflow.types';
export { ICreateRequestInput } from './approval-workflow.types';
export { ICastDecisionInput } from './approval-workflow.types';
export { IWorkflowProgress } from './approval-workflow.types';
