/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `openapi-ui` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { OpenApiUiAuthService } from './openapi-ui.auth.service';
export { escapeHtml, renderEndpoint, renderHeader, groupByVerb, renderOperationsSection, renderSchemasSection, renderBootstrapScript, renderPage, renderHtmlDocument, validateEndpointMarkup, isSafeRelativePath } from './openapi-ui.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_UI_SECTIONS, MAX_UI_ENDPOINT_BYTES, IExplorerSection, IExplorerPage, IRenderedEndpoint, IRenderedHeader } from './openapi-ui.types';
