/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `openapi-ui` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { OpenApiUiAuthService } from './openapi-ui.auth.service';
export { escapeHtml } from './openapi-ui.service';
export { renderEndpoint } from './openapi-ui.service';
export { renderHeader } from './openapi-ui.service';
export { groupByVerb } from './openapi-ui.service';
export { renderOperationsSection } from './openapi-ui.service';
export { renderSchemasSection } from './openapi-ui.service';
export { renderBootstrapScript } from './openapi-ui.service';
export { renderPage } from './openapi-ui.service';
export { renderHtmlDocument } from './openapi-ui.service';
export { validateEndpointMarkup } from './openapi-ui.service';
export { isSafeRelativePath } from './openapi-ui.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_UI_SECTIONS } from './openapi-ui.types';
export { MAX_UI_ENDPOINT_BYTES } from './openapi-ui.types';
export { IExplorerSection } from './openapi-ui.types';
export { IExplorerPage } from './openapi-ui.types';
export { IRenderedEndpoint } from './openapi-ui.types';
export { IRenderedHeader } from './openapi-ui.types';
