/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `attachments` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AttachmentsCropModule } from './attachments-crop.module';
export { AttachmentsStorageModule } from './attachments-storage.module';
export { AttachmentsTableModule } from './attachments-table.module';
export { AttachmentsModule } from './attachments.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AttachmentsController } from './attachments.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AttachmentsStorageService } from './attachments-storage.service';
export { AttachmentsTableService } from './attachments-table.service';
export { AttachmentsService } from './attachments.service';

// ─── Utilities ────────────────────────────────────────────────────
export { getExtensionPreview } from './utils';
export { resolveThumbnailMimetype } from './utils';

// ─── Other public exports ─────────────────────────────────────────
export { AttachmentsCropQueueProcessor } from './attachments-crop.processor';
export { ATTACHMENTS_CROP_QUEUE } from './attachments-crop.processor';
export { ATTACHMENT_SM_THUMBNAIL_HEIGHT } from './constant';
export { ATTACHMENT_LG_THUMBNAIL_HEIGHT } from './constant';
export { ATTACHMENT_THUMBNAIL_DEFAULT_MIMETYPE } from './constant';
export * from './pdf-thumbnail';
