/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `byok-llm` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ByokLlmModule } from './byok-llm.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ByokLlmController } from './byok-llm.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ByokLlmAuthService } from './byok-llm.auth.service';
export { fingerprintKey, suggestAlias, validateProviderKey, normalizeProviderKey, canRegisterMore, buildUsageRow, aggregateOrgUsage, computeHealth, routeRequest, hashAttempt, shouldMarkExhausted, ALL_LLM_PROVIDERS, testHelpers } from './byok-llm.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_MIN_REMAINING_TOKENS, MAX_LLM_KEYS_PER_ORG, DEFAULT_HEALTH_WINDOW_MS, DEFAULT_HEALTH_MIN_REQUESTS, LLM_PROVIDER_LABELS, LlmProvider, LlmKeyStatus, LlmIsolationMode, ILlmProviderKey, ILlmUsageRow, ILlmCallAttempt, ILlmHealthSnapshot, ILlmRoutingDecision, ILlmRoutingOptions } from './byok-llm.types';
