/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `trash` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TrashModule } from './trash.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TrashController } from './trash.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TrashService } from './trash.service';
export { V2RecordTrashService } from './v2-record-trash.service';
export { V2FieldTrashRepository, V2RecordsDeletedTableTrashProjection, V2RecordsDeletedAttachmentProjection, V2TableTrashedProjection, V2TableRestoredProjection, V2TableTrashService } from './v2-table-trash.service';

// ─── Other public exports ─────────────────────────────────────────
export { resolveV2TrashRecordDisplayName, IV2TrashRecordSnapshotLike } from './v2-trash-record-name';
