/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `airtable-import` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AirtableImportModule } from './airtable-import.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AirtableImportController } from './airtable-import.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AirtableImportService, IAirtableImportProgress, IAirtableImportProgressReporter } from './airtable-import.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IAirtableBaseItem, IAirtableListBasesResponse, IAirtableSelectChoice, IAirtableFieldResult, IAirtableFieldOptions, IAirtableField, IAirtableView, IAirtableTable, IAirtableBaseSchemaResponse, IAirtableAttachment, IAirtableCollaborator, IAirtableRecord, IAirtableListRecordsResponse, IAirtableApiError } from './airtable.types';

// ─── Other public exports ─────────────────────────────────────────
export { AirtableApiError, AirtableIteratorExpiredError, AirtableApiClient, IAirtableAccessTokenProvider } from './airtable-api.client';
export { translateAirtableFormula, IFormulaTranslation } from './airtable-formula-translator';
export { AirtableLinkRowSpill, ISpilledLinkRow, ISpillStorage } from './airtable-link-spill';
export { convertAirtableCellValue, convertCollaboratorCellValue, extractLinkedRecordIds, IResolvedSpaceUser } from './airtable-record-converter';
export { mapAirtableRollupAggregation } from './airtable-rollup-mapper';
export { buildAirtableImportPlan, IAirtableCellConverter, IAiPromptPart, IPlannedDirectField, IPlannedLinkField, IPlannedLookupField, IPlannedCountField, IPlannedFormulaField, IPlannedRollupField, IPlannedViewSource, IAirtableTablePlan, IAirtableImportPlan } from './airtable-schema-mapper';
export { AirtableShareError, AirtableShareClient, IAirtableShareErrorReason, IAirtableShareSession, IAirtableFilterLeaf, IAirtableFilterGroup, IAirtableSort, IAirtableGroupLevel, IAirtableViewConfig, IAirtableRollupSource } from './airtable-share.client';
export { AIRTABLE_IMPORT_TOKEN_RESOLVER, IAirtableImportTokenResolver } from './airtable-token-resolver';
export { mapAirtableFilter, mapAirtableViewConfig, IImportFieldMeta, IViewConfigMapperContext, IMappedViewConfig } from './airtable-view-config-mapper';
