/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `airtable-import` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AirtableImportModule } from './airtable-import.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AirtableImportController } from './airtable-import.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AirtableImportService } from './airtable-import.service';
export { IAirtableImportProgress } from './airtable-import.service';
export { IAirtableImportProgressReporter } from './airtable-import.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IAirtableBaseItem } from './airtable.types';
export { IAirtableListBasesResponse } from './airtable.types';
export { IAirtableSelectChoice } from './airtable.types';
export { IAirtableFieldResult } from './airtable.types';
export { IAirtableFieldOptions } from './airtable.types';
export { IAirtableField } from './airtable.types';
export { IAirtableView } from './airtable.types';
export { IAirtableTable } from './airtable.types';
export { IAirtableBaseSchemaResponse } from './airtable.types';
export { IAirtableAttachment } from './airtable.types';
export { IAirtableCollaborator } from './airtable.types';
export { IAirtableRecord } from './airtable.types';
export { IAirtableListRecordsResponse } from './airtable.types';
export { IAirtableApiError } from './airtable.types';

// ─── Other public exports ─────────────────────────────────────────
export { AirtableApiError } from './airtable-api.client';
export { AirtableIteratorExpiredError } from './airtable-api.client';
export { AirtableApiClient } from './airtable-api.client';
export { IAirtableAccessTokenProvider } from './airtable-api.client';
export { translateAirtableFormula } from './airtable-formula-translator';
export { IFormulaTranslation } from './airtable-formula-translator';
export { AirtableLinkRowSpill } from './airtable-link-spill';
export { ISpilledLinkRow } from './airtable-link-spill';
export { ISpillStorage } from './airtable-link-spill';
export { convertAirtableCellValue } from './airtable-record-converter';
export { convertCollaboratorCellValue } from './airtable-record-converter';
export { extractLinkedRecordIds } from './airtable-record-converter';
export { IResolvedSpaceUser } from './airtable-record-converter';
export { mapAirtableRollupAggregation } from './airtable-rollup-mapper';
export { buildAirtableImportPlan } from './airtable-schema-mapper';
export { IAirtableCellConverter } from './airtable-schema-mapper';
export { IAiPromptPart } from './airtable-schema-mapper';
export { IPlannedDirectField } from './airtable-schema-mapper';
export { IPlannedLinkField } from './airtable-schema-mapper';
export { IPlannedLookupField } from './airtable-schema-mapper';
export { IPlannedCountField } from './airtable-schema-mapper';
export { IPlannedFormulaField } from './airtable-schema-mapper';
export { IPlannedRollupField } from './airtable-schema-mapper';
export { IPlannedViewSource } from './airtable-schema-mapper';
export { IAirtableTablePlan } from './airtable-schema-mapper';
export { IAirtableImportPlan } from './airtable-schema-mapper';
export { AirtableShareError } from './airtable-share.client';
export { AirtableShareClient } from './airtable-share.client';
export { IAirtableShareErrorReason } from './airtable-share.client';
export { IAirtableShareSession } from './airtable-share.client';
export { IAirtableFilterLeaf } from './airtable-share.client';
export { IAirtableFilterGroup } from './airtable-share.client';
export { IAirtableSort } from './airtable-share.client';
export { IAirtableGroupLevel } from './airtable-share.client';
export { IAirtableViewConfig } from './airtable-share.client';
export { IAirtableRollupSource } from './airtable-share.client';
export { AIRTABLE_IMPORT_TOKEN_RESOLVER } from './airtable-token-resolver';
export { IAirtableImportTokenResolver } from './airtable-token-resolver';
export { mapAirtableFilter } from './airtable-view-config-mapper';
export { mapAirtableViewConfig } from './airtable-view-config-mapper';
export { IImportFieldMeta } from './airtable-view-config-mapper';
export { IViewConfigMapperContext } from './airtable-view-config-mapper';
export { IMappedViewConfig } from './airtable-view-config-mapper';
