/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `chat` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ChatModule } from './chat.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ChatController } from './chat.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ChatService } from './chat.service';

// ─── Other public exports ─────────────────────────────────────────
export { CompletionRo } from './chart-completion.ro';
