/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `audit-log-query` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AuditLogQueryAuthService } from './audit-log-query.auth.service';
export { isAuditField, isAuditOp, walkClauses, validateQuery, clauseIn, andOf, notOf, getFieldValue, matchesClause, matchesNode, evaluateQuery, buildSqlWhere, normalizeQuery } from './audit-log-query.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_AUDIT_LIMIT, MAX_AUDIT_LIMIT, AUDIT_FIELDS, AuditField, AuditOp, AuditValue, IAuditClause, IAuditNot, IAuditAnd, IAuditNode, IAuditSort, IAuditQuery, IAuditLogRow, IAuditQueryResult } from './audit-log-query.types';
