/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-builder-feedback` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AiBuilderFeedbackAuthService } from './ai-builder-feedback.auth.service';
export { computeEditDiff, diffToSignatures, buildFeedbackRow, groupByModelEntityType, parseGroupKey, aggregateBucket, isTrusted, rankMetrics, summarize, pickPreferredModel, metricToTemplateScore, isScoreImprovement, applyFeedbackToPrompt, buildTemplateId } from './ai-builder-feedback.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { outcomeFromStatus, DEFAULT_MIN_SAMPLE_SIZE, DEFAULT_EDIT_MAGNITUDE_WEIGHT, MAX_PROMPT_TEMPLATE_SCORE, MIN_PROMPT_TEMPLATE_SCORE, FeedbackOutcome, IProposalFeedback, IAiBuilderFeedbackMetrics, IPromptTemplateScore, IFeedbackSummary, IEditDiff, IProposalLike, IBuilderViewProposalLite, IAggregateFeedbackOptions, EditSignatureKind, IEditSignature } from './ai-builder-feedback.types';
