/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `scim` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ScimModule } from './scim.module';

// ─── Controllers ──────────────────────────────────────────────────
export { ScimAdminController } from './scim-admin.controller';
export { ScimController } from './scim.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ScimAuthService } from './scim.auth.service';
export { ScimService, generateScimToken, hashScimToken, parseBearerHeader, userToScim, scimToUserPatch, groupToScim, toListResponse, matchesFilter } from './scim.service';

// ─── Guards ───────────────────────────────────────────────────────
export { ScimAuthGuard } from './scim-auth.guard';

// ─── Types / interfaces ───────────────────────────────────────────
export { IScimTokenRow, IScimUser, IScimGroup, IScimListResponse, IScimAuthContext } from './scim.types';
