/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `module-wiring` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ModuleWiringAuthService } from './module-wiring.auth.service';
export { validateEntry, buildManifest, isComplete, coverageStats, diffManifests, patchEntry } from './module-wiring.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { FEATURE_MODULE_NAMES, MAX_MODULES, FeatureModule, IModuleEntry, IWiringManifest } from './module-wiring.types';
