/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `module-wiring` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ModuleWiringAuthService } from './module-wiring.auth.service';
export { validateEntry } from './module-wiring.service';
export { buildManifest } from './module-wiring.service';
export { isComplete } from './module-wiring.service';
export { coverageStats } from './module-wiring.service';
export { diffManifests } from './module-wiring.service';
export { patchEntry } from './module-wiring.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { FEATURE_MODULE_NAMES } from './module-wiring.types';
export { MAX_MODULES } from './module-wiring.types';
export { FeatureModule } from './module-wiring.types';
export { IModuleEntry } from './module-wiring.types';
export { IWiringManifest } from './module-wiring.types';
