/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `interceptor-guard` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { InterceptorGuardAuthService } from './interceptor-guard.auth.service';
export { validateAuth, isAuthorized, buildError, statusFor, buildAudit, shouldDeny, outcomeFor } from './interceptor-guard.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_PRINCIPAL_LENGTH, MAX_TRACE_ID_LENGTH, MAX_AUDIT_CONTEXT_KEYS, ROLE_ADMIN, ROLE_OWNER, AuditAction, ErrorCode, IAuthContext, IErrorEnvelope, IAuditRecord } from './interceptor-guard.types';
