/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `open-api` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { MailSenderOpenApiModule } from './mail-sender-open-api.module';
export { MailSenderMergeModule } from './mail-sender.merge.module';

// ─── Controllers ──────────────────────────────────────────────────
export { MailSenderOpenApiController } from './mail-sender-open-api.controller';

// ─── Services ─────────────────────────────────────────────────────
export { MailSenderOpenApiService } from './mail-sender-open-api.service';

// ─── Other public exports ─────────────────────────────────────────
export { MailSenderMergeProcessor } from './mail-sender.merge.processor';
export { MAIL_SENDER_QUEUE } from './mail-sender.merge.processor';
