/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `field` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { FieldModule } from './field.module';

// ─── Services ─────────────────────────────────────────────────────
export { FieldService } from './field.service';

// ─── Other public exports ─────────────────────────────────────────
export { ID_FIELD_NAME, VERSION_FIELD_NAME, AUTO_NUMBER_FIELD_NAME, CREATED_TIME_FIELD_NAME, LAST_MODIFIED_TIME_FIELD_NAME, CREATED_BY_FIELD_NAME, LAST_MODIFIED_BY_FIELD_NAME, preservedDbFieldNames, systemDbFieldNames, systemFieldTypes, IVisualTableDefaultField } from './constant';
export { isSystemUserField, filterFieldsByProjection, filterFieldsByView } from './fields-utils';
export { FIELD_RESTORE_RECORD_CHUNK_SIZE, compactFieldRestoreRecords, restoreFieldRecordValues, IFieldRestoreRecord } from './restore-field-record-values';
export { dbType2knexFormat, SchemaType } from './util';
