/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `space` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { SpaceDataDbCopyModule } from './space-data-db-copy.module';
export { SpaceDataDbMigrationGuardModule } from './space-data-db-migration-guard.module';
export { SpaceModule } from './space.module';

// ─── Controllers ──────────────────────────────────────────────────
export { SpaceController } from './space.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DataDbBaselineService } from './data-db-baseline.service';
export { DataDbBindingService } from './data-db-binding.service';
export { DataDbMigrationService, dataDbMigrationsToken, DATA_DB_MIGRATION_TABLE, IDataDbMigration } from './data-db-migration.service';
export { DataDbPreflightService, DATA_DB_PREFLIGHT_CLIENT_FACTORY, maskDatabaseUrl, fingerprintDatabaseUrl, fingerprintDataDbConnection, getDatabaseUrlDisplayParts, replaceDatabaseUrlDatabase, dataDbKnexClientFactory, IDataDbPreflightClient, IDataDbPreflightTransaction, IDataDbDatabaseIdentity, IDataDbPreflightClientFactory } from './data-db-preflight.service';
export { SpaceDataDbCopyService, REQUIRED_POSTGRES_COPY_TOOLS, REQUIRED_PGCOPYDB_COPY_TOOLS, PG_RESTORE_LIST_STDOUT_LIMIT, parsePsqlCopyRowCount, parsePsqlInsertRowCount, postgresCopyToolsForStrategy, pgRestoreListEntryMatchesForeignKey, filterPgRestoreListForForeignKeys, ISpaceDataDbBaseSchemaCopyStrategy, ISpaceDataDbSharedTableCopyStrategy, ISpaceDataDbExcludedForeignKey, ISpaceDataDbFilteredRestoreList, ISpaceDataDbBaseSchemaCopyResult, ISpaceDataDbSharedTableCopyResult, ISpaceDataDbPostgresFdwSharedTableCopyResult } from './space-data-db-copy.service';
export { SpaceDataDbMigrationGuardService } from './space-data-db-migration-guard.service';
export { SpaceDataDbMigrationWorkerService } from './space-data-db-migration-worker.service';
export { SpaceDataDbMigrationService, spaceDataDbStatfsToken, ISpaceDataDbStatfs } from './space-data-db-migration.service';
export { SpaceDataDbProcessError, SpaceDataDbProcessPipelineError, SpaceDataDbProcessCanceledError, SpaceDataDbProcessPipelineCanceledError, SpaceDataDbProcessRunnerService, SPACE_DATA_DB_PROCESS_SPAWN, ISpaceDataDbProcessSpawn, ISpaceDataDbProcessRunOptions, ISpaceDataDbProcessRunResult, ISpaceDataDbProcessPipelineResult } from './space-data-db-process-runner.service';
export { SpaceService } from './space.service';

// ─── Constants ────────────────────────────────────────────────────
export { migrateSpaceTargetMode, spaceDataDbAdminOnlyErrorCode, spaceDataDbAdminOnlyMessage, activeSpaceDataDbMigrationStates, preCopyCancelableSpaceDataDbMigrationStates, cancelableSpaceDataDbMigrationStates, spaceDataDbMigratingErrorCode, spaceDataDbMigrationActiveErrorCode, spaceDataDbMigrationCanceledErrorCode, spaceDataDbMigrationCancelConflictErrorCode, spaceDataDbTargetConflictErrorCode, spaceDataDbTargetCleanupFailedErrorCode, spaceDataDbTargetExtensionMissingErrorCode, spaceDataDbLargeMigrationConfirmationRequiredErrorCode, spaceDataDbRollbackUnsafeErrorCode, spaceDataDbValidationMismatchErrorCode, spaceDataDbInventoryChangedErrorCode, spaceDataDbRelatedSpacesRequiredErrorCode, spaceDataDbTempDiskInsufficientErrorCode, spaceDataDbTargetDiskInsufficientErrorCode, spaceDataDbPostgresToolUnavailableErrorCode, spaceDataDbComputedDrainTimeoutErrorCode, spaceDataDbSchemaOperationDrainTimeoutErrorCode, spaceDataDbBackgroundWriterDrainTimeoutErrorCode, spaceDataDbStaleActiveJobErrorCode } from './space-data-db-migration.constants';

// ─── Other public exports ─────────────────────────────────────────
export { generateByokProviderName, normalizeSpaceAIIntegrationConfig } from './ai-integration-config';
export { generateDataDbInternalSchema, resolveDataDbInternalSchema, quoteDataDbIdentifier, withDataDbInternalSchemaParam } from './data-db-internal-schema';
export { encryptDataDbUrl, decryptDataDbUrl } from './data-db-url-secret';
export { postgresToolUrl, buildBaseSchemaRestoreListPlan, buildBaseSchemaRestorePlan, buildBaseSchemaDumpRestorePlan, buildBaseSchemaDumpStreamRestorePlan, buildBaseSchemaPgcopydbPlan, buildSharedTableCopyPlan, buildSharedTablePsqlCopyPlan, buildSharedTablePostgresFdwCopyPlan, buildMigrationSharedTablePsqlCopyPlans, buildMigrationSharedTablePostgresFdwCopyPlans, ISpaceDataDbProcessPlan, ISpaceDataDbProcessPipelinePlan, ISpaceDataDbDumpRestorePlan, ISpaceDataDbDumpStreamRestorePlan, ISpaceDataDbPgcopydbPlan, ISharedTableCopyPlan, ISharedTablePsqlCopyPlan, ISharedTablePostgresFdwCopyPlan } from './space-data-db-copy-plan';
export { SpaceDataDbMigrationProgressTracker, spaceDataDbMigrationStages, buildSpaceDataDbMigrationPercent, isTerminalSpaceDataDbMigrationPhase, ISpaceDataDbMigrationStageKey, ISpaceDataDbMigrationStage, ISpaceDataDbMigrationProgressDetail, ISpaceDataDbWeightedMigrationProgress } from './space-data-db-migration-progress';
export { resolveSpaceDataDbRelatedSpaces, ISpaceDataDbRelatedSpaces, ISpaceDataDbRelatedSpaceInfo, ISpaceDataDbRelatedSpaceLink } from './space-data-db-related-spaces';
