/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `space` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { SpaceDataDbCopyModule } from './space-data-db-copy.module';
export { SpaceDataDbMigrationGuardModule } from './space-data-db-migration-guard.module';
export { SpaceModule } from './space.module';

// ─── Controllers ──────────────────────────────────────────────────
export { SpaceController } from './space.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DataDbBaselineService } from './data-db-baseline.service';
export { DataDbBindingService } from './data-db-binding.service';
export { DataDbMigrationService } from './data-db-migration.service';
export { dataDbMigrationsToken } from './data-db-migration.service';
export { DATA_DB_MIGRATION_TABLE } from './data-db-migration.service';
export { IDataDbMigration } from './data-db-migration.service';
export { DataDbPreflightService } from './data-db-preflight.service';
export { DATA_DB_PREFLIGHT_CLIENT_FACTORY } from './data-db-preflight.service';
export { maskDatabaseUrl } from './data-db-preflight.service';
export { fingerprintDatabaseUrl } from './data-db-preflight.service';
export { fingerprintDataDbConnection } from './data-db-preflight.service';
export { getDatabaseUrlDisplayParts } from './data-db-preflight.service';
export { replaceDatabaseUrlDatabase } from './data-db-preflight.service';
export { dataDbKnexClientFactory } from './data-db-preflight.service';
export { IDataDbPreflightClient } from './data-db-preflight.service';
export { IDataDbPreflightTransaction } from './data-db-preflight.service';
export { IDataDbDatabaseIdentity } from './data-db-preflight.service';
export { IDataDbPreflightClientFactory } from './data-db-preflight.service';
export { SpaceDataDbCopyService } from './space-data-db-copy.service';
export { REQUIRED_POSTGRES_COPY_TOOLS } from './space-data-db-copy.service';
export { REQUIRED_PGCOPYDB_COPY_TOOLS } from './space-data-db-copy.service';
export { PG_RESTORE_LIST_STDOUT_LIMIT } from './space-data-db-copy.service';
export { parsePsqlCopyRowCount } from './space-data-db-copy.service';
export { parsePsqlInsertRowCount } from './space-data-db-copy.service';
export { postgresCopyToolsForStrategy } from './space-data-db-copy.service';
export { pgRestoreListEntryMatchesForeignKey } from './space-data-db-copy.service';
export { filterPgRestoreListForForeignKeys } from './space-data-db-copy.service';
export { ISpaceDataDbBaseSchemaCopyStrategy } from './space-data-db-copy.service';
export { ISpaceDataDbSharedTableCopyStrategy } from './space-data-db-copy.service';
export { ISpaceDataDbExcludedForeignKey } from './space-data-db-copy.service';
export { ISpaceDataDbFilteredRestoreList } from './space-data-db-copy.service';
export { ISpaceDataDbBaseSchemaCopyResult } from './space-data-db-copy.service';
export { ISpaceDataDbSharedTableCopyResult } from './space-data-db-copy.service';
export { ISpaceDataDbPostgresFdwSharedTableCopyResult } from './space-data-db-copy.service';
export { SpaceDataDbMigrationGuardService } from './space-data-db-migration-guard.service';
export { SpaceDataDbMigrationWorkerService } from './space-data-db-migration-worker.service';
export { SpaceDataDbMigrationService } from './space-data-db-migration.service';
export { spaceDataDbStatfsToken } from './space-data-db-migration.service';
export { ISpaceDataDbStatfs } from './space-data-db-migration.service';
export { SpaceDataDbProcessError } from './space-data-db-process-runner.service';
export { SpaceDataDbProcessPipelineError } from './space-data-db-process-runner.service';
export { SpaceDataDbProcessCanceledError } from './space-data-db-process-runner.service';
export { SpaceDataDbProcessPipelineCanceledError } from './space-data-db-process-runner.service';
export { SpaceDataDbProcessRunnerService } from './space-data-db-process-runner.service';
export { SPACE_DATA_DB_PROCESS_SPAWN } from './space-data-db-process-runner.service';
export { ISpaceDataDbProcessSpawn } from './space-data-db-process-runner.service';
export { ISpaceDataDbProcessRunOptions } from './space-data-db-process-runner.service';
export { ISpaceDataDbProcessRunResult } from './space-data-db-process-runner.service';
export { ISpaceDataDbProcessPipelineResult } from './space-data-db-process-runner.service';
export { SpaceService } from './space.service';

// ─── Constants ────────────────────────────────────────────────────
export { migrateSpaceTargetMode } from './space-data-db-migration.constants';
export { spaceDataDbAdminOnlyErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbAdminOnlyMessage } from './space-data-db-migration.constants';
export { activeSpaceDataDbMigrationStates } from './space-data-db-migration.constants';
export { preCopyCancelableSpaceDataDbMigrationStates } from './space-data-db-migration.constants';
export { cancelableSpaceDataDbMigrationStates } from './space-data-db-migration.constants';
export { spaceDataDbMigratingErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbMigrationActiveErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbMigrationCanceledErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbMigrationCancelConflictErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbTargetConflictErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbTargetCleanupFailedErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbTargetExtensionMissingErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbLargeMigrationConfirmationRequiredErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbRollbackUnsafeErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbValidationMismatchErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbInventoryChangedErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbRelatedSpacesRequiredErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbTempDiskInsufficientErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbTargetDiskInsufficientErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbPostgresToolUnavailableErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbComputedDrainTimeoutErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbSchemaOperationDrainTimeoutErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbBackgroundWriterDrainTimeoutErrorCode } from './space-data-db-migration.constants';
export { spaceDataDbStaleActiveJobErrorCode } from './space-data-db-migration.constants';

// ─── Other public exports ─────────────────────────────────────────
export { generateByokProviderName } from './ai-integration-config';
export { normalizeSpaceAIIntegrationConfig } from './ai-integration-config';
export { generateDataDbInternalSchema } from './data-db-internal-schema';
export { resolveDataDbInternalSchema } from './data-db-internal-schema';
export { quoteDataDbIdentifier } from './data-db-internal-schema';
export { withDataDbInternalSchemaParam } from './data-db-internal-schema';
export { encryptDataDbUrl } from './data-db-url-secret';
export { decryptDataDbUrl } from './data-db-url-secret';
export { postgresToolUrl } from './space-data-db-copy-plan';
export { buildBaseSchemaRestoreListPlan } from './space-data-db-copy-plan';
export { buildBaseSchemaRestorePlan } from './space-data-db-copy-plan';
export { buildBaseSchemaDumpRestorePlan } from './space-data-db-copy-plan';
export { buildBaseSchemaDumpStreamRestorePlan } from './space-data-db-copy-plan';
export { buildBaseSchemaPgcopydbPlan } from './space-data-db-copy-plan';
export { buildSharedTableCopyPlan } from './space-data-db-copy-plan';
export { buildSharedTablePsqlCopyPlan } from './space-data-db-copy-plan';
export { buildSharedTablePostgresFdwCopyPlan } from './space-data-db-copy-plan';
export { buildMigrationSharedTablePsqlCopyPlans } from './space-data-db-copy-plan';
export { buildMigrationSharedTablePostgresFdwCopyPlans } from './space-data-db-copy-plan';
export { ISpaceDataDbProcessPlan } from './space-data-db-copy-plan';
export { ISpaceDataDbProcessPipelinePlan } from './space-data-db-copy-plan';
export { ISpaceDataDbDumpRestorePlan } from './space-data-db-copy-plan';
export { ISpaceDataDbDumpStreamRestorePlan } from './space-data-db-copy-plan';
export { ISpaceDataDbPgcopydbPlan } from './space-data-db-copy-plan';
export { ISharedTableCopyPlan } from './space-data-db-copy-plan';
export { ISharedTablePsqlCopyPlan } from './space-data-db-copy-plan';
export { ISharedTablePostgresFdwCopyPlan } from './space-data-db-copy-plan';
export { SpaceDataDbMigrationProgressTracker } from './space-data-db-migration-progress';
export { spaceDataDbMigrationStages } from './space-data-db-migration-progress';
export { buildSpaceDataDbMigrationPercent } from './space-data-db-migration-progress';
export { isTerminalSpaceDataDbMigrationPhase } from './space-data-db-migration-progress';
export { ISpaceDataDbMigrationStageKey } from './space-data-db-migration-progress';
export { ISpaceDataDbMigrationStage } from './space-data-db-migration-progress';
export { ISpaceDataDbMigrationProgressDetail } from './space-data-db-migration-progress';
export { ISpaceDataDbWeightedMigrationProgress } from './space-data-db-migration-progress';
export { resolveSpaceDataDbRelatedSpaces } from './space-data-db-related-spaces';
export { ISpaceDataDbRelatedSpaces } from './space-data-db-related-spaces';
export { ISpaceDataDbRelatedSpaceInfo } from './space-data-db-related-spaces';
export { ISpaceDataDbRelatedSpaceLink } from './space-data-db-related-spaces';
