/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `presence` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { PresenceModule } from './presence.module';

// ─── Services ─────────────────────────────────────────────────────
export { PresenceAuthService } from './presence.auth.service';
export { isValidScope, isValidStatus, isValidColor, validateJoinInput, validateCursor, validateCursorShape, validateTickInput, validateUpdateStatusInput, validateQueryInput, deriveStatusOnTick, computeExpiresAt, isSessionExpired, filterByQuery, liveSessions, diffSessions, applyJoinPolicy, IPresenceDiff } from './presence.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_HEARTBEAT_TTL_MS, DEFAULT_CURSOR_COLOR_PATTERN, DEFAULT_DISPLAY_NAME_MAX_LENGTH, DEFAULT_MAX_SESSIONS_PER_USER_PER_SCOPE, PresenceScope, PresenceStatus, ICursorState, IPresenceSession, IJoinPresenceInput, IUpdateCursorInput, IUpdateStatusInput, ITickInput, IPresenceQueryInput } from './presence.types';
