/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `smtp` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { SmtpModule } from './smtp.module';

// ─── Controllers ──────────────────────────────────────────────────
export { SmtpController } from './smtp.controller';

// ─── Services ─────────────────────────────────────────────────────
export { SmtpService } from './smtp.service';
export { __test } from './smtp.service';
export { ISocketLike } from './smtp.service';
export { ICreateConnection } from './smtp.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { ISmtpConfig } from './smtp.types';
export { ISendMailInput } from './smtp.types';
export { ISendMailResult } from './smtp.types';
export { IBuildMessageParts } from './smtp.types';
