/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `field-calculate` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { FieldCalculateModule } from './field-calculate.module';

// ─── Services ─────────────────────────────────────────────────────
export { FieldConvertingLinkService } from './field-converting-link.service';
export { FieldConvertingService } from './field-converting.service';
export { FieldCreatingService } from './field-creating.service';
export { FieldDeletingService } from './field-deleting.service';
export { FieldSupplementService } from './field-supplement.service';
export { FieldViewSyncService } from './field-view-sync.service';
export { FormulaFieldService } from './formula-field.service';
export { LinkFieldQueryService } from './link-field-query.service';
