/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `v2` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { V2Module } from './v2.module';

// ─── Controllers ──────────────────────────────────────────────────
export { V2OpenApiController } from './v2-openapi.controller';
export { V2Controller } from './v2.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TableQuerySearchVectorRuntimeService, tableQuerySearchVectorRuntimeEnv, tableQuerySearchAccessPathRuntimeEnv, resolveTableQuerySearchVectorRuntimeMode, toRecordSearchAccessPathFromConfig, hasSearchValueForSearchVectorRuntime, SearchVectorConfigRow, TableQuerySearchVectorRuntimeMode } from './table-query-search-vector-runtime.service';
export { V2ActionTriggerService, IActionTriggerData } from './v2-action-trigger.service';
export { V2AttachmentUrlSignerService } from './v2-attachment-url-signer.service';
export { V2TableBaseNodeProjection, V2BaseNodeCompatService } from './v2-base-node-compat.service';
export { V2CollaboratorNotificationDispatcher, V2RecordCreatedCollaboratorNotificationProjection, V2RecordsBatchCreatedCollaboratorNotificationProjection, V2RecordUpdatedCollaboratorNotificationProjection, V2RecordsBatchUpdatedCollaboratorNotificationProjection, V2CollaboratorNotificationService } from './v2-collaborator-notification.service';
export { V2ContainerService } from './v2-container.service';
export { V2FieldDeleteCompatCompletion, V2FieldDeleteSnapshotSink, V2FieldDeleteCompatService } from './v2-field-delete-compat.service';
export { V2RecordChangedValueDecoratorService } from './v2-record-changed-value-decorator.service';
export { V2RecordUpdatedHistoryProjection, V2RecordsBatchCreatedHistoryProjection, V2RecordsBatchUpdatedHistoryProjection, V2RecordHistoryService } from './v2-record-history.service';
export { V2SchemaOperationRunnerService } from './v2-schema-operation-runner.service';
export { V2UserRenamePropagationService, IUserRenamePropagationRequest } from './v2-user-rename-propagation.service';
export { V2ViewCompatService } from './v2-view-compat.service';

// ─── Other public exports ─────────────────────────────────────────
export { TableQuerySearchMetricsService } from './table-query-search-observability';
export { CommandBusTracingMiddleware } from './v2-command-bus-tracing.middleware';
export { V2ExecutionContextFactory } from './v2-execution-context.factory';
export { PinoLoggerAdapter } from './v2-logger.adapter';
export { V2_PROJECTION_REGISTRAR_METADATA, V2ProjectionRegistrar, isV2ProjectionRegistrar, IV2ProjectionRegistrar } from './v2-projection-registrar';
export { QueryBusTracingMiddleware } from './v2-query-bus-tracing.middleware';
export { OpenTelemetryTracer, V2_CODE_OWNERSHIP_ATTRIBUTE, V2_CODE_PATH_ATTRIBUTE, V2_CODE_LAYER_ATTRIBUTE } from './v2-tracer.adapter';
