/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `v2` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { V2Module } from './v2.module';

// ─── Controllers ──────────────────────────────────────────────────
export { V2OpenApiController } from './v2-openapi.controller';
export { V2Controller } from './v2.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TableQuerySearchVectorRuntimeService } from './table-query-search-vector-runtime.service';
export { tableQuerySearchVectorRuntimeEnv } from './table-query-search-vector-runtime.service';
export { tableQuerySearchAccessPathRuntimeEnv } from './table-query-search-vector-runtime.service';
export { resolveTableQuerySearchVectorRuntimeMode } from './table-query-search-vector-runtime.service';
export { toRecordSearchAccessPathFromConfig } from './table-query-search-vector-runtime.service';
export { hasSearchValueForSearchVectorRuntime } from './table-query-search-vector-runtime.service';
export { SearchVectorConfigRow } from './table-query-search-vector-runtime.service';
export { TableQuerySearchVectorRuntimeMode } from './table-query-search-vector-runtime.service';
export { V2ActionTriggerService } from './v2-action-trigger.service';
export { IActionTriggerData } from './v2-action-trigger.service';
export { V2AttachmentUrlSignerService } from './v2-attachment-url-signer.service';
export { V2TableBaseNodeProjection } from './v2-base-node-compat.service';
export { V2BaseNodeCompatService } from './v2-base-node-compat.service';
export { V2CollaboratorNotificationDispatcher } from './v2-collaborator-notification.service';
export { V2RecordCreatedCollaboratorNotificationProjection } from './v2-collaborator-notification.service';
export { V2RecordsBatchCreatedCollaboratorNotificationProjection } from './v2-collaborator-notification.service';
export { V2RecordUpdatedCollaboratorNotificationProjection } from './v2-collaborator-notification.service';
export { V2RecordsBatchUpdatedCollaboratorNotificationProjection } from './v2-collaborator-notification.service';
export { V2CollaboratorNotificationService } from './v2-collaborator-notification.service';
export { V2ContainerService } from './v2-container.service';
export { V2FieldDeleteCompatCompletion } from './v2-field-delete-compat.service';
export { V2FieldDeleteSnapshotSink } from './v2-field-delete-compat.service';
export { V2FieldDeleteCompatService } from './v2-field-delete-compat.service';
export { V2RecordChangedValueDecoratorService } from './v2-record-changed-value-decorator.service';
export { V2RecordUpdatedHistoryProjection } from './v2-record-history.service';
export { V2RecordsBatchCreatedHistoryProjection } from './v2-record-history.service';
export { V2RecordsBatchUpdatedHistoryProjection } from './v2-record-history.service';
export { V2RecordHistoryService } from './v2-record-history.service';
export { V2SchemaOperationRunnerService } from './v2-schema-operation-runner.service';
export { V2UserRenamePropagationService } from './v2-user-rename-propagation.service';
export { IUserRenamePropagationRequest } from './v2-user-rename-propagation.service';
export { V2ViewCompatService } from './v2-view-compat.service';

// ─── Other public exports ─────────────────────────────────────────
export { TableQuerySearchMetricsService } from './table-query-search-observability';
export { CommandBusTracingMiddleware } from './v2-command-bus-tracing.middleware';
export { V2ExecutionContextFactory } from './v2-execution-context.factory';
export { PinoLoggerAdapter } from './v2-logger.adapter';
export { V2_PROJECTION_REGISTRAR_METADATA } from './v2-projection-registrar';
export { V2ProjectionRegistrar } from './v2-projection-registrar';
export { isV2ProjectionRegistrar } from './v2-projection-registrar';
export { IV2ProjectionRegistrar } from './v2-projection-registrar';
export { QueryBusTracingMiddleware } from './v2-query-bus-tracing.middleware';
export { OpenTelemetryTracer } from './v2-tracer.adapter';
export { V2_CODE_OWNERSHIP_ATTRIBUTE } from './v2-tracer.adapter';
export { V2_CODE_PATH_ATTRIBUTE } from './v2-tracer.adapter';
export { V2_CODE_LAYER_ATTRIBUTE } from './v2-tracer.adapter';
