/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `e2e-fixture-replay` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { E2eFixtureReplayAuthService } from './e2e-fixture-replay.auth.service';
export { deriveSessionId, planReplaySteps, validateReplayRequest, startSession, markReplaying, applyStepResult, finalize, summarize, isTerminal, capSteps, findStep, stepsByOp, allPassed, userCount, hasToken, findUser } from './e2e-fixture-replay.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_REPLAY_STEPS, MAX_REPLAY_SESSIONS, ReplayStatus, IReplayStep, IFixtureReplaySession, IReplaySummary, IReplayRequest } from './e2e-fixture-replay.types';
