/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `e2e-fixture-replay` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { E2eFixtureReplayAuthService } from './e2e-fixture-replay.auth.service';
export { deriveSessionId } from './e2e-fixture-replay.service';
export { planReplaySteps } from './e2e-fixture-replay.service';
export { validateReplayRequest } from './e2e-fixture-replay.service';
export { startSession } from './e2e-fixture-replay.service';
export { markReplaying } from './e2e-fixture-replay.service';
export { applyStepResult } from './e2e-fixture-replay.service';
export { finalize } from './e2e-fixture-replay.service';
export { summarize } from './e2e-fixture-replay.service';
export { isTerminal } from './e2e-fixture-replay.service';
export { capSteps } from './e2e-fixture-replay.service';
export { findStep } from './e2e-fixture-replay.service';
export { stepsByOp } from './e2e-fixture-replay.service';
export { allPassed } from './e2e-fixture-replay.service';
export { userCount } from './e2e-fixture-replay.service';
export { hasToken } from './e2e-fixture-replay.service';
export { findUser } from './e2e-fixture-replay.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_REPLAY_STEPS } from './e2e-fixture-replay.types';
export { MAX_REPLAY_SESSIONS } from './e2e-fixture-replay.types';
export { ReplayStatus } from './e2e-fixture-replay.types';
export { IReplayStep } from './e2e-fixture-replay.types';
export { IFixtureReplaySession } from './e2e-fixture-replay.types';
export { IReplaySummary } from './e2e-fixture-replay.types';
export { IReplayRequest } from './e2e-fixture-replay.types';
