/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `sdk-codegen-py` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { SdkCodegenPyAuthService } from './sdk-codegen-py.auth.service';
export { jsTypeToPy, pathToFString, schemaToDataclass, opToAsyncMethod, groupByTagPy, generatePySdk } from './sdk-codegen-py.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SDK_PY_DEFAULT_PACKAGE, SDK_PY_DEFAULT_VERSION, SDK_PY_MIN_PYTHON, OpenApiOperationPy, OpenApiSchemaPy, OpenApiDocumentPy, GeneratedPyFile, PyCodegenResult } from './sdk-codegen-py.types';
