/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `local-auth` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { LocalAuthModule } from './local-auth.module';

// ─── Controllers ──────────────────────────────────────────────────
export { LocalAuthController } from './local-auth.controller';

// ─── Services ─────────────────────────────────────────────────────
export { LocalAuthService } from './local-auth.service';
