/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `query-builder` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { RecordQueryBuilderModule } from './record-query-builder.module';

// ─── Services ─────────────────────────────────────────────────────
export { RecordQueryBuilderService } from './record-query-builder.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IFieldSelectName } from './field-select.type';

// ─── Utilities ────────────────────────────────────────────────────
export { getTableAliasFromTable, getLinkUsesJunctionTable, getOrderedFieldsByProjection, isDateLikeField } from './record-query-builder.util';

// ─── Other public exports ─────────────────────────────────────────
export { FieldCteVisitor } from './field-cte-visitor';
export { FieldFormattingVisitor } from './field-formatting-visitor';
export { FieldSelectVisitor } from './field-select-visitor';
export { FormulaSupportGeneratedColumnValidator } from './formula-support-generated-column-validator';
export { validateFormulaSupport } from './formula-validation';
export { IPrepareViewParams, ICreateRecordQueryBuilderOptions, ICreateRecordAggregateBuilderOptions, IRecordQueryBuilder, IRecordQueryFieldCteMap, IRecordSelectionMap, IReadonlyRecordSelectionMap, IRecordQueryContext, IRecordQueryFilterContext, IRecordQuerySortContext, IRecordQueryGroupContext, IRecordQueryAggregateContext, IReadonlyQueryBuilderState, IMutableQueryBuilderState } from './record-query-builder.interface';
export { RecordQueryBuilderManager, ScopedSelectionState, asReadonlyState } from './record-query-builder.manager';
export { InjectRecordQueryBuilder, InjectRecordQueryDialect, RecordQueryDialectProvider } from './record-query-builder.provider';
export { RECORD_QUERY_BUILDER_SYMBOL } from './record-query-builder.symbol';
export { RECORD_QUERY_DIALECT_SYMBOL, IRecordQueryDialectProvider } from './record-query-dialect.interface';
export { GeneratedColumnSqlConversionVisitor, SelectColumnSqlConversionVisitor, IFormulaConversionContext, ISelectFormulaConversionContext, IFormulaConversionResult, IGeneratedColumnQueryInterface, ISelectQueryInterface, IGeneratedColumnQuerySupportValidator } from './sql-conversion.visitor';
