/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `query-builder` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { RecordQueryBuilderModule } from './record-query-builder.module';

// ─── Services ─────────────────────────────────────────────────────
export { RecordQueryBuilderService } from './record-query-builder.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IFieldSelectName } from './field-select.type';

// ─── Utilities ────────────────────────────────────────────────────
export { getTableAliasFromTable } from './record-query-builder.util';
export { getLinkUsesJunctionTable } from './record-query-builder.util';
export { getOrderedFieldsByProjection } from './record-query-builder.util';
export { isDateLikeField } from './record-query-builder.util';

// ─── Other public exports ─────────────────────────────────────────
export { FieldCteVisitor } from './field-cte-visitor';
export { FieldFormattingVisitor } from './field-formatting-visitor';
export { FieldSelectVisitor } from './field-select-visitor';
export { FormulaSupportGeneratedColumnValidator } from './formula-support-generated-column-validator';
export { validateFormulaSupport } from './formula-validation';
export { IPrepareViewParams } from './record-query-builder.interface';
export { ICreateRecordQueryBuilderOptions } from './record-query-builder.interface';
export { ICreateRecordAggregateBuilderOptions } from './record-query-builder.interface';
export { IRecordQueryBuilder } from './record-query-builder.interface';
export { IRecordQueryFieldCteMap } from './record-query-builder.interface';
export { IRecordSelectionMap } from './record-query-builder.interface';
export { IReadonlyRecordSelectionMap } from './record-query-builder.interface';
export { IRecordQueryContext } from './record-query-builder.interface';
export { IRecordQueryFilterContext } from './record-query-builder.interface';
export { IRecordQuerySortContext } from './record-query-builder.interface';
export { IRecordQueryGroupContext } from './record-query-builder.interface';
export { IRecordQueryAggregateContext } from './record-query-builder.interface';
export { IReadonlyQueryBuilderState } from './record-query-builder.interface';
export { IMutableQueryBuilderState } from './record-query-builder.interface';
export { RecordQueryBuilderManager } from './record-query-builder.manager';
export { ScopedSelectionState } from './record-query-builder.manager';
export { asReadonlyState } from './record-query-builder.manager';
export { InjectRecordQueryBuilder } from './record-query-builder.provider';
export { InjectRecordQueryDialect } from './record-query-builder.provider';
export { RecordQueryDialectProvider } from './record-query-builder.provider';
export { RECORD_QUERY_BUILDER_SYMBOL } from './record-query-builder.symbol';
export { RECORD_QUERY_DIALECT_SYMBOL } from './record-query-dialect.interface';
export { IRecordQueryDialectProvider } from './record-query-dialect.interface';
export { GeneratedColumnSqlConversionVisitor } from './sql-conversion.visitor';
export { SelectColumnSqlConversionVisitor } from './sql-conversion.visitor';
export { IFormulaConversionContext } from './sql-conversion.visitor';
export { ISelectFormulaConversionContext } from './sql-conversion.visitor';
export { IFormulaConversionResult } from './sql-conversion.visitor';
export { IGeneratedColumnQueryInterface } from './sql-conversion.visitor';
export { ISelectQueryInterface } from './sql-conversion.visitor';
export { IGeneratedColumnQuerySupportValidator } from './sql-conversion.visitor';
