/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `view-config-panel-api` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ViewConfigPanelApiAuthService } from './view-config-panel-api.auth.service';
export { buildPanelResponse, hashMetadata, applyPatches, processPatchRequest, canEdit, diffMetadata } from './view-config-panel-api.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { ViewConfigPanelRequest, ViewConfigPanelColumnSection, ViewConfigPanelFilterSection, ViewConfigPanelSortSection, ViewConfigPanelGroupSection, ViewConfigPanelCondFormatSection, ViewConfigPanelSection, ViewConfigPanelResponse, ViewConfigPanelPatchRequest, ViewConfigPanelPatchResponse, ViewConfigPanelError } from './view-config-panel-api.types';
