/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `db-connector` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { DbConnectorModule } from './db-connector.module';

// ─── Controllers ──────────────────────────────────────────────────
export { DbConnectorController } from './db-connector.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DbConnectorAuthService } from './db-connector.auth.service';
export { isValidKind, isValidSyncMode, isValidSyncStatus, validateCreateInput, validateConfigShape, isValidSchedule, validateStartSyncInput, canStartSync, deriveSyncStatus, resolvePageSize, testConnectionConfig, isTerminalStatus, isManualRunAllowed } from './db-connector.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_CONNECTOR_NAME_MAX_LENGTH, DEFAULT_SCHEDULE_MAX_LENGTH, DEFAULT_PAGE_SIZE, DbConnectorKind, DbConnectorSyncStatus, DbConnectorSyncMode, IDbConnector, IDbConnectorSync, ICreateConnectorInput, ITestConnectionInput, ITestConnectionResult, IStartSyncInput } from './db-connector.types';
