/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `view-metadata-schema` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ViewMetadataSchemaAuthService } from './view-metadata-schema.auth.service';
export { emptyViewMetadata, validateViewMetadata, addColumn, removeColumn, reorderColumns, setColumnWidth, toggleColumnHidden, toggleColumnPinned, addFilter, addSort, addGroup, addCondFormat, listVisibleColumns, listPinnedColumns, totalWidth, serializeViewMetadata, summarizeViewMetadata, migrateViewMetadata } from './view-metadata-schema.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_VIEW_COLUMNS, MAX_VIEW_FILTERS, MAX_VIEW_SORTS, MAX_VIEW_GROUPS, MAX_VIEW_COND_FORMATS, VIEW_NAME_RE, ViewKind, ViewLayoutDirection, ViewColumnSpec, ViewFilterSpec, ViewSortSpec, ViewGroupSpec, ViewCondFormatSpec, ViewMetadataSpec, ViewMetadataValidationIssue, ViewMetadataValidationResult } from './view-metadata-schema.types';
