/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `billing-pdf-export` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { BillingPdfExportAuthService } from './billing-pdf-export.auth.service';
export { validateInvoice } from './billing-pdf-export.service';
export { buildSummary } from './billing-pdf-export.service';
export { formatCents } from './billing-pdf-export.service';
export { escapePdfText } from './billing-pdf-export.service';
export { paginateLines } from './billing-pdf-export.service';
export { buildPdf } from './billing-pdf-export.service';
export { renderInvoicePdf } from './billing-pdf-export.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { CURRENCY_CODES } from './billing-pdf-export.types';
export { PDF_PAGE_WIDTH_PT } from './billing-pdf-export.types';
export { PDF_PAGE_HEIGHT_PT } from './billing-pdf-export.types';
export { PDF_MARGIN_PT } from './billing-pdf-export.types';
export { PDF_LINE_HEIGHT_PT } from './billing-pdf-export.types';
export { PDF_MAX_LINES_PER_PAGE } from './billing-pdf-export.types';
export { DEFAULT_TAX_BPS } from './billing-pdf-export.types';
export { PDF_TITLE } from './billing-pdf-export.types';
export { CurrencyCode } from './billing-pdf-export.types';
export { IBillingLineItem } from './billing-pdf-export.types';
export { IBillingInvoice } from './billing-pdf-export.types';
export { IBillingSummary } from './billing-pdf-export.types';
export { IPdfDoc } from './billing-pdf-export.types';
export { IPdfRenderResult } from './billing-pdf-export.types';
