/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `billing-pdf-export` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { BillingPdfExportAuthService } from './billing-pdf-export.auth.service';
export { validateInvoice, buildSummary, formatCents, escapePdfText, paginateLines, buildPdf, renderInvoicePdf } from './billing-pdf-export.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { CURRENCY_CODES, PDF_PAGE_WIDTH_PT, PDF_PAGE_HEIGHT_PT, PDF_MARGIN_PT, PDF_LINE_HEIGHT_PT, PDF_MAX_LINES_PER_PAGE, DEFAULT_TAX_BPS, PDF_TITLE, CurrencyCode, IBillingLineItem, IBillingInvoice, IBillingSummary, IPdfDoc, IPdfRenderResult } from './billing-pdf-export.types';
