/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `cross-base-federation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CrossBaseFederationModule } from './cross-base-federation.module';

// ─── Controllers ──────────────────────────────────────────────────
export { CrossBaseFederationController } from './cross-base-federation.controller';

// ─── Services ─────────────────────────────────────────────────────
export { CrossBaseFederationAuthService } from './cross-base-federation.auth.service';
export { isFederationStatus } from './cross-base-federation.service';
export { isFederationSourceKind } from './cross-base-federation.service';
export { isFederationRefreshMode } from './cross-base-federation.service';
export { defaultRefreshIntervalSeconds } from './cross-base-federation.service';
export { maxSourcesPerView } from './cross-base-federation.service';
export { validateView } from './cross-base-federation.service';
export { normalizeView } from './cross-base-federation.service';
export { validateSource } from './cross-base-federation.service';
export { normalizeSource } from './cross-base-federation.service';
export { nextRefreshAt } from './cross-base-federation.service';
export { stalenessSeconds } from './cross-base-federation.service';
export { shouldRefreshNow } from './cross-base-federation.service';
export { startRefresh } from './cross-base-federation.service';
export { finishRefresh } from './cross-base-federation.service';
export { consumeEvents } from './cross-base-federation.service';
export { aliasMap } from './cross-base-federation.service';
export { hasSources } from './cross-base-federation.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_REFRESH_INTERVAL_SECONDS } from './cross-base-federation.types';
export { MIN_REFRESH_INTERVAL_SECONDS } from './cross-base-federation.types';
export { MAX_REFRESH_INTERVAL_SECONDS } from './cross-base-federation.types';
export { MAX_SOURCES_PER_VIEW } from './cross-base-federation.types';
export { MAX_FIELDS_PER_SOURCE } from './cross-base-federation.types';
export { MAX_EVENTS_PER_REFRESH } from './cross-base-federation.types';
export { FEDERATION_STATUSES } from './cross-base-federation.types';
export { FEDERATION_SOURCE_KINDS } from './cross-base-federation.types';
export { FEDERATION_REFRESH_MODES } from './cross-base-federation.types';
export { FEDERATION_STATUS_LABELS } from './cross-base-federation.types';
export { FederationStatus } from './cross-base-federation.types';
export { FederationSourceKind } from './cross-base-federation.types';
export { FederationRefreshMode } from './cross-base-federation.types';
export { IFederationSource } from './cross-base-federation.types';
export { IFederationView } from './cross-base-federation.types';
export { IFederationEvent } from './cross-base-federation.types';
export { IFederationRefresh } from './cross-base-federation.types';
export { ICrossBaseFederationOptions } from './cross-base-federation.types';
