/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `cross-base-federation` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CrossBaseFederationModule } from './cross-base-federation.module';

// ─── Controllers ──────────────────────────────────────────────────
export { CrossBaseFederationController } from './cross-base-federation.controller';

// ─── Services ─────────────────────────────────────────────────────
export { CrossBaseFederationAuthService } from './cross-base-federation.auth.service';
export { isFederationStatus, isFederationSourceKind, isFederationRefreshMode, defaultRefreshIntervalSeconds, maxSourcesPerView, validateView, normalizeView, validateSource, normalizeSource, nextRefreshAt, stalenessSeconds, shouldRefreshNow, startRefresh, finishRefresh, consumeEvents, aliasMap, hasSources } from './cross-base-federation.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_REFRESH_INTERVAL_SECONDS, MIN_REFRESH_INTERVAL_SECONDS, MAX_REFRESH_INTERVAL_SECONDS, MAX_SOURCES_PER_VIEW, MAX_FIELDS_PER_SOURCE, MAX_EVENTS_PER_REFRESH, FEDERATION_STATUSES, FEDERATION_SOURCE_KINDS, FEDERATION_REFRESH_MODES, FEDERATION_STATUS_LABELS, FederationStatus, FederationSourceKind, FederationRefreshMode, IFederationSource, IFederationView, IFederationEvent, IFederationRefresh, ICrossBaseFederationOptions } from './cross-base-federation.types';
