/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `tenant-replay` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TenantReplayModule } from './tenant-replay.module';

// ─── Services ─────────────────────────────────────────────────────
export { TenantReplayService } from './tenant-replay.service';
export { TenantSnapshotService } from './tenant-snapshot.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IAnonymizePolicy, IReplayOptions, ITableRecordStats, IBaseSnapshot, ITableSnapshot, IUserSnapshot, ITenantSnapshot, IReplayError, IReplayCounts, IReplayReport } from './tenant-replay.types';

// ─── Utilities ────────────────────────────────────────────────────
export { SYSTEM_USER_ID, REPLAY_RUN_TAG_PREFIX, buildReplayClsStore, scrubEmail, scrubName, anonymizeUser, anonymizeSnapshot, structuredCloneSafe } from './tenant-anonymize.util';
