/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `open-api` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { FieldOpenApiModule } from './field-open-api.module';

// ─── Controllers ──────────────────────────────────────────────────
export { FieldOpenApiController } from './field-open-api.controller';

// ─── Services ─────────────────────────────────────────────────────
export { FieldOpenApiV2Service } from './field-open-api-v2.service';
export { FieldOpenApiService, ILegacyDeleteFieldsPayloadSnapshot } from './field-open-api.service';
