/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `totp` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TotpModule } from './totp.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TotpController } from './totp.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TotpAuthService } from './totp.auth.service';
export { generateSecret } from './totp.service';
export { base32Encode } from './totp.service';
export { base32Decode } from './totp.service';
export { currentCounter } from './totp.service';
export { hotp } from './totp.service';
export { totp } from './totp.service';
export { verifyCode } from './totp.service';
export { buildOtpauthUri } from './totp.service';
export { generateBackupCodes } from './totp.service';
export { hashBackupCode } from './totp.service';
export { nextWindowAt } from './totp.service';
export { DEFAULT_PERIOD } from './totp.service';
export { DEFAULT_DIGITS } from './totp.service';
export { DEFAULT_ALGORITHM } from './totp.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { TotpAlgorithm } from './totp.types';
export { ITotpFactorRow } from './totp.types';
export { ITotpEnrollmentChallenge } from './totp.types';
export { ITotpVerifyInput } from './totp.types';
export { ITotpVerifyResult } from './totp.types';
