/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `view-conditional-format-engine` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ViewConditionalFormatEngineAuthService } from './view-conditional-format-engine.auth.service';
export { evaluateRule, applyRules, firstMatch, countMatches, isRuleValid, filterValid } from './view-conditional-format-engine.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { FORMAT_COLORS, FORMAT_ICONS, FormatRule, FormatCellInput, FormatStyleDirective, FormatResult } from './view-conditional-format-engine.types';
