/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `integrity` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { IntegrityModule } from './integrity.module';

// ─── Controllers ──────────────────────────────────────────────────
export { IntegrityV2Controller } from './integrity-v2.controller';
export { IntegrityController } from './integrity.controller';

// ─── Services ─────────────────────────────────────────────────────
export { ForeignKeyIntegrityService } from './foreign-key.service';
export { IntegrityV2Service } from './integrity-v2.service';
export { LinkFieldIntegrityService } from './link-field.service';
export { LinkIntegrityService } from './link-integrity.service';
export { UniqueIndexService } from './unique-index.service';
