/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `template` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { TemplateOpenApiModule } from './template-open-api.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TemplateAdminController } from './template-admin.controller';
export { TemplateOpenApiController } from './template-open-api.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TemplateOpenApiService } from './template-open-api.service';
export { TemplatePermalinkService } from './template-permalink.service';
