/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `sdk-signature-verify` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { SdkSignatureVerifyAuthService } from './sdk-signature-verify.auth.service';
export { digest, sign, verify, signArtifact, verifyArtifact, buildBundle, verifyBundle, isAlgorithmSupported, makeTestKey } from './sdk-signature-verify.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SIG_ALGORITHMS, SignatureKeyPair, SignatureBlob, SignedArtifact, VerifyResult, BundleEntry, VerificationBundle, BundleVerifyResult } from './sdk-signature-verify.types';
