/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `canary` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CanaryModule } from './canary.module';

// ─── Controllers ──────────────────────────────────────────────────
export { CanaryController } from './canary.controller';

// ─── Services ─────────────────────────────────────────────────────
export { CanaryService, IV2Decision, IBaseV2DecisionContext } from './canary.service';

// ─── Other public exports ─────────────────────────────────────────
export { X_TEABLE_V2_HEADER, X_TEABLE_V2_REASON_HEADER, X_TEABLE_V2_FEATURE_HEADER, TEABLE_REQUEST_ATTRIBUTION, getV2Attribution, setV2AttributionOnSentryScope, setV2AttributionOnCurrentSentryScopes, getV2AttributionSpanAttributes, getV2AttributionLogContext, setV2AttributionHeaders, IV2Attribution } from './v2-attribution';
