/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `quota` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { QuotaModule } from './quota.module';

// ─── Controllers ──────────────────────────────────────────────────
export { QuotaController } from './quota.controller';

// ─── Services ─────────────────────────────────────────────────────
export { QuotaService } from './quota.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IQuotaCheckResult, IConsumeContext, IUsageMetricSnapshot, ISpaceUsageReport, ISetSpaceQuotaInput } from './quota.types';

// ─── Constants ────────────────────────────────────────────────────
export { isUnlimited, KB, MB, GB, TB, PLAN_LIMITS, METRIC_TO_COLUMN, PERIODIC_METRICS, UNLIMITED, IPlanLimits } from './quota.constants';

// ─── Other public exports ─────────────────────────────────────────
export { QuotaExceededException } from './quota.exception';
export { QuotaEnforcementInterceptor, quotaEnforcementEnabled, quotaEnforcementPermissive, setQuotaResolver, QuotaResolver } from './quota.interceptor';
