/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `quota` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { QuotaModule } from './quota.module';

// ─── Controllers ──────────────────────────────────────────────────
export { QuotaController } from './quota.controller';

// ─── Services ─────────────────────────────────────────────────────
export { QuotaService } from './quota.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IQuotaCheckResult } from './quota.types';
export { IConsumeContext } from './quota.types';
export { IUsageMetricSnapshot } from './quota.types';
export { ISpaceUsageReport } from './quota.types';
export { ISetSpaceQuotaInput } from './quota.types';

// ─── Constants ────────────────────────────────────────────────────
export { isUnlimited } from './quota.constants';
export { KB } from './quota.constants';
export { MB } from './quota.constants';
export { GB } from './quota.constants';
export { TB } from './quota.constants';
export { PLAN_LIMITS } from './quota.constants';
export { METRIC_TO_COLUMN } from './quota.constants';
export { PERIODIC_METRICS } from './quota.constants';
export { UNLIMITED } from './quota.constants';
export { IPlanLimits } from './quota.constants';

// ─── Other public exports ─────────────────────────────────────────
export { QuotaExceededException } from './quota.exception';
export { QuotaEnforcementInterceptor } from './quota.interceptor';
export { quotaEnforcementEnabled } from './quota.interceptor';
export { quotaEnforcementPermissive } from './quota.interceptor';
export { setQuotaResolver } from './quota.interceptor';
export { QuotaResolver } from './quota.interceptor';
