/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `plugin` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { PluginProxyModule } from './plugin-proxy.module';
export { NextPluginModule } from './plugin.module';

// ─── Other public exports ─────────────────────────────────────────
export { PluginProxyMiddleware } from './plugin-proxy.middleware';
