/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `ai-builder` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AiBuilderModule } from './ai-builder.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AiBuilderController } from './ai-builder.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AiBuilderAuthService, LLM_PROVIDER, testOnly } from './ai-builder.auth.service';
export { OfflineBuilderProvider, inferFieldType, sanitizePrompt, isValidFieldType, isValidViewType, repairJson, validateProposal, isValidStatusTransition, stringifyProposal, hashProposal, buildProposalRow, extractTitle, buildPromptForLlm, parseAndValidateProposal, normalizeProposal, MAX_PROMPT_LENGTH, MIN_PROMPT_LENGTH, ILlmProvider } from './ai-builder.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_FIELD_TYPES, SUPPORTED_VIEW_TYPES, BuilderEntityType, BuilderProposalStatus, BuilderFieldType, IBuilderFieldProposal, IBuilderTableProposal, IBuilderViewProposal, IBuilderProposal, BuilderProposal, IBuilderProposalRow, ICreateBuilderProposalInput, IApproveBuilderProposalInput } from './ai-builder.types';

// ─── Other public exports ─────────────────────────────────────────
export { AiServiceBuilderProvider } from './ai-service-builder.provider';
