/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-masking` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { DataMaskingModule } from './data-masking.module';

// ─── Controllers ──────────────────────────────────────────────────
export { DataMaskingController } from './data-masking.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DataMaskingAuthService } from './data-masking.auth.service';
export { isValidStrategy, isValidScope, isValidRole, validateCreateInput, validatePartialRule, validateRegexRule, applyPolicy, applyStrategy, applyPolicies, viewerMaySee } from './data-masking.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_PARTIAL_KEEP_PREFIX, DEFAULT_PARTIAL_KEEP_SUFFIX, DEFAULT_PARTIAL_MASK, HASH_PREFIX, MaskingStrategy, MaskingScope, MaskingRole, IRegexRule, IPartialRule, IMaskingPolicy, IMaskedFieldRow, ICreatePolicyInput } from './data-masking.types';
