/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-masking` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { DataMaskingModule } from './data-masking.module';

// ─── Controllers ──────────────────────────────────────────────────
export { DataMaskingController } from './data-masking.controller';

// ─── Services ─────────────────────────────────────────────────────
export { DataMaskingAuthService } from './data-masking.auth.service';
export { isValidStrategy } from './data-masking.service';
export { isValidScope } from './data-masking.service';
export { isValidRole } from './data-masking.service';
export { validateCreateInput } from './data-masking.service';
export { validatePartialRule } from './data-masking.service';
export { validateRegexRule } from './data-masking.service';
export { applyPolicy } from './data-masking.service';
export { applyStrategy } from './data-masking.service';
export { applyPolicies } from './data-masking.service';
export { viewerMaySee } from './data-masking.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_PARTIAL_KEEP_PREFIX } from './data-masking.types';
export { DEFAULT_PARTIAL_KEEP_SUFFIX } from './data-masking.types';
export { DEFAULT_PARTIAL_MASK } from './data-masking.types';
export { HASH_PREFIX } from './data-masking.types';
export { MaskingStrategy } from './data-masking.types';
export { MaskingScope } from './data-masking.types';
export { MaskingRole } from './data-masking.types';
export { IRegexRule } from './data-masking.types';
export { IPartialRule } from './data-masking.types';
export { IMaskingPolicy } from './data-masking.types';
export { IMaskedFieldRow } from './data-masking.types';
export { ICreatePolicyInput } from './data-masking.types';
