/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `pdf-export` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { PdfExportAuthService } from './pdf-export.auth.service';
export { renderTablePdf } from './pdf-export.auth.service';
export { renderSummaryPdf } from './pdf-export.auth.service';
export { effectivePageSize } from './pdf-export.service';
export { buildTableLayout } from './pdf-export.service';
export { buildDocument } from './pdf-export.service';
export { paginateTable } from './pdf-export.service';
export { flipOrientation } from './pdf-export.service';
export { ITableDraft } from './pdf-export.service';
export { IDocumentDraft } from './pdf-export.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PAGE_SIZES } from './pdf-export.types';
export { PageOrientation } from './pdf-export.types';
export { IPageSize } from './pdf-export.types';
export { IPdfDocumentOptions } from './pdf-export.types';
export { IPdfTextBlock } from './pdf-export.types';
export { IPdfRectBlock } from './pdf-export.types';
export { IPdfLineBlock } from './pdf-export.types';
export { IPdfTableRow } from './pdf-export.types';
export { IPdfTableBlock } from './pdf-export.types';
export { IPdfBlock } from './pdf-export.types';
export { IPdfPage } from './pdf-export.types';
export { IPdfBuildResult } from './pdf-export.types';
