/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `pdf-export` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { PdfExportAuthService, renderTablePdf, renderSummaryPdf } from './pdf-export.auth.service';
export { effectivePageSize, buildTableLayout, buildDocument, paginateTable, flipOrientation, ITableDraft, IDocumentDraft } from './pdf-export.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PAGE_SIZES, PageOrientation, IPageSize, IPdfDocumentOptions, IPdfTextBlock, IPdfRectBlock, IPdfLineBlock, IPdfTableRow, IPdfTableBlock, IPdfBlock, IPdfPage, IPdfBuildResult } from './pdf-export.types';
