/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `mail-sender` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { MailSenderModule } from './mail-sender.module';
export { MailSenderModuleOptions } from './mail-sender.module';

// ─── Services ─────────────────────────────────────────────────────
export { MailSenderService } from './mail-sender.service';

// ─── Other public exports ─────────────────────────────────────────
export { truncateMailName } from './mail-helpers';
export { helpers } from './mail-helpers';
export { verifyTransport } from './mail-helpers';
export { buildEmailFrom } from './mail-helpers';
export { ISendMailOptions } from './mail-helpers';
