/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `compliance-evidence-collector` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ComplianceEvidenceCollectorAuthService } from './compliance-evidence-collector.auth.service';
export { buildEvidenceId } from './compliance-evidence-collector.service';
export { hashContent } from './compliance-evidence-collector.service';
export { isEvidenceIdValid } from './compliance-evidence-collector.service';
export { filterRecords } from './compliance-evidence-collector.service';
export { collectEvidence } from './compliance-evidence-collector.service';
export { groupByControl } from './compliance-evidence-collector.service';
export { presentEvidence } from './compliance-evidence-collector.service';
export { totals } from './compliance-evidence-collector.service';
export { isFresh } from './compliance-evidence-collector.service';
export { dropStale } from './compliance-evidence-collector.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { EVIDENCE_ID_RE } from './compliance-evidence-collector.types';
export { DEFAULT_EVIDENCE_WINDOW_DAYS } from './compliance-evidence-collector.types';
export { DEFAULT_MAX_PER_CONTROL } from './compliance-evidence-collector.types';
export { EvidenceRecord } from './compliance-evidence-collector.types';
export { EvidenceCollectorOptions } from './compliance-evidence-collector.types';
export { CollectionResult } from './compliance-evidence-collector.types';
export { EvidenceQuery } from './compliance-evidence-collector.types';
