/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `last-visit` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { LastVisitModule } from './last-visit.module';

// ─── Controllers ──────────────────────────────────────────────────
export { LastVisitController } from './last-visit.controller';

// ─── Services ─────────────────────────────────────────────────────
export { LastVisitService } from './last-visit.service';
