/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `supertest-helper` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { SupertestHelperAuthService } from './supertest-helper.auth.service';
export { newTraceId } from './supertest-helper.service';
export { validateRequest } from './supertest-helper.service';
export { buildHeaders } from './supertest-helper.service';
export { buildAssertionPath } from './supertest-helper.service';
export { isExpectedStatus } from './supertest-helper.service';
export { isBearerAuth } from './supertest-helper.service';
export { countByStatus } from './supertest-helper.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_HEADER_KEYS } from './supertest-helper.types';
export { MAX_HEADER_VALUE_LENGTH } from './supertest-helper.types';
export { MAX_PATH_LENGTH } from './supertest-helper.types';
export { MAX_BODY_BYTES } from './supertest-helper.types';
export { HttpVerb } from './supertest-helper.types';
export { IHttpRequest } from './supertest-helper.types';
export { IHttpResponse } from './supertest-helper.types';
export { IAppInvoker } from './supertest-helper.types';
export { IHttpHeadersInput } from './supertest-helper.types';
export { IRouteHit } from './supertest-helper.types';
export { IRunSummary } from './supertest-helper.types';
