/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `user` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { UserModule } from './user.module';

// ─── Controllers ──────────────────────────────────────────────────
export { UserController } from './user.controller';

// ─── Services ─────────────────────────────────────────────────────
export { UserService } from './user.service';
