/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `widget-market` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { WidgetMarketAuthService } from './widget-market.auth.service';
export { isWidgetKind, isAggregationFn, newWidgetInstanceId, validateWidgetInstance, defaultPosition, aggregate, pivot, topN, renderWidget, IRowLike } from './widget-market.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { findWidgetDefinition, DEFAULT_WIDGET_WIDTH, DEFAULT_WIDGET_HEIGHT, MAX_WIDGET_INSTANCES_PER_DASHBOARD, WIDGET_DEFINITIONS, WidgetKind, AggregationFn, IWidgetDataBinding, IWidgetDefinition, IWidgetInstance, IWidgetSeriesPoint, IWidgetRenderResult } from './widget-market.types';
