/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `audit` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AuditSourceModule } from './audit.module';

// ─── Controllers ──────────────────────────────────────────────────
export { AuditLogController, AuditOperationsSummaryController, parseAuditFilter } from './audit-log.controller';

// ─── Services ─────────────────────────────────────────────────────
export { AuditLogService, IAuditLogFilter, IAuditLogPage, IAuditLogSummary, IAuditLogRow } from './audit-log.service';

// ─── Other public exports ─────────────────────────────────────────
export { AuditLogListener } from './audit-log.listener';
export { AuditScope, IAuditAction, IAuditOperation, INewAuditOperationInput, IEmitAtomicAuditInput } from './audit-scope';
export { Audit, IAuditCtx, IAuditEmitDirective, IAuditResolved, IAuditDeclarativeConfig, IAuditResolverFn, IAuditConfig } from './audit.decorator';
export { RecordAuditListener } from './record-audit.listener';
