/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `record-history-cold` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { RecordHistoryColdCoreModule, RecordHistoryColdModule } from './record-history-cold.module';

// ─── Services ─────────────────────────────────────────────────────
export { RecordHistoryColdReadService, encodeColdCursor, decodeColdCursor, IMergedHistoryRow, ICollectHistoryRowsInput, ICollectHistoryRowsResult } from './record-history-cold-read.service';
export { ColdReadDeadlineError, RecordHistoryColdStorageService } from './record-history-cold-storage.service';
export { RecordHistoryCompactorService, ICompactMonthResult } from './record-history-compactor.service';
export { RecordHistoryFlusherService, nextReadBatchLimit, IColdFlushOptions, ITableFlushResult, IColdFlushRunResult } from './record-history-flusher.service';

// ─── Other public exports ─────────────────────────────────────────
export { BucketMergeFeeder } from './bucket-merge-feeder';
export { SortMemoryBudget, ExternalRowSorter, approxColdRowBytes } from './external-sort';
export { RECORD_HISTORY_COLD_VERSION, STATS_SET_CAP, hasZstd, partFileSuffix, createPartCompressor, createPartDecompressor, coldRootDir, tablePrefix, monthPrefix, statsKey, buildPartKey, parsePartKey, bucketOfDate, bucketId, serializeHeader, serializeRow, coldTruncatedMarker, truncateColdValue, truncateColdRow, serializeFooter, createRowHasher, parsePartLine, compareRowAsc, buildRecordBloom, bloomMightContain, compareRowByTimeDesc, IColdHistoryRow, IPartBucket, IPartHeader, IPartFooter, IParsedPartKey, IRecordBloom, IPartStatsEntry, ITableColdStats, IParsedPartLine } from './part-codec';
export { PartWriter, IPartStore, IPartWriterOptions, IPartWriteMetrics } from './part-writer';
export { recordHistoryColdConfig, mapWithConcurrency, IRecordHistoryColdConfig } from './record-history-cold.config';
export { RecordHistoryColdProcessor, RECORD_HISTORY_COLD_QUEUE } from './record-history-cold.processor';
