/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `utils` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Other public exports ─────────────────────────────────────────
export { changeToOp } from './changes';
export { formatChangesToOps } from './changes';
export { mergeDuplicateChange } from './changes';
export { ICellChange } from './changes';
export { ICellContext } from './changes';
export { composeOpMaps } from './compose-maps';
export { IOpsMap } from './compose-maps';
export { isLinkCellValue } from './detect-link';
export { hasCycle } from './dfs';
export { prependStartFieldIds } from './dfs';
export { getTopoOrders } from './dfs';
export { topoOrderWithStart } from './dfs';
export { filterDirectedGraph } from './dfs';
export { pruneGraph } from './dfs';
export { ITopoItem } from './dfs';
export { IGraphItem } from './dfs';
export { nameConsole } from './name-console';
