/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `scheduled-import` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ScheduledImportAuthService } from './scheduled-import.auth.service';
export { validateJob } from './scheduled-import.service';
export { checkpoint } from './scheduled-import.service';
export { planChunks } from './scheduled-import.service';
export { chunkCount } from './scheduled-import.service';
export { appendJob } from './scheduled-import.service';
export { chooseChunkSize } from './scheduled-import.service';
export { isExpired } from './scheduled-import.service';
export { isFinished } from './scheduled-import.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CHUNK_ROWS } from './scheduled-import.types';
export { MIN_CHUNK_ROWS } from './scheduled-import.types';
export { DEFAULT_CHUNK_ROWS } from './scheduled-import.types';
export { MAX_JOBS_PER_ORG } from './scheduled-import.types';
export { MAX_TOTAL_ROWS } from './scheduled-import.types';
export { ImportFormat } from './scheduled-import.types';
export { ImportDirection } from './scheduled-import.types';
export { IImportJob } from './scheduled-import.types';
export { IImportCheckpoint } from './scheduled-import.types';
