/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `scheduled-import` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ScheduledImportAuthService } from './scheduled-import.auth.service';
export { validateJob, checkpoint, planChunks, chunkCount, appendJob, chooseChunkSize, isExpired, isFinished } from './scheduled-import.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_CHUNK_ROWS, MIN_CHUNK_ROWS, DEFAULT_CHUNK_ROWS, MAX_JOBS_PER_ORG, MAX_TOTAL_ROWS, ImportFormat, ImportDirection, IImportJob, IImportCheckpoint } from './scheduled-import.types';
