/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `field-type-map` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { FieldTypeMapAuthService } from './field-type-map.auth.service';
export { isFieldDataKind, defaultMatrix, lookupMap, isLossy, validateMap, coerce, setMap } from './field-type-map.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { FIELD_DATA_KINDS, MAX_FIELD_MAPS, FieldDataKind, FieldConversion, IFieldTypeMap } from './field-type-map.types';
