/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `sdk-codegen-js` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { SdkCodegenJsAuthService } from './sdk-codegen-js.auth.service';
export { groupByTag, pathToColonForm, schemaToInterface, opToMethod, generateSdk, tsTypeOf } from './sdk-codegen-js.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SDK_JS_DEFAULT_PACKAGE_NAME, SDK_JS_DEFAULT_VERSION, OpenApiOperation, OpenApiParameter, OpenApiSchema, OpenApiDocument, GeneratedSdkFile, SdkCodegenResult } from './sdk-codegen-js.types';
