/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `replica-router` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { ReplicaRouterAuthService } from './replica-router.auth.service';
export { isValidKind, isValidStatus, isValidPolicy, validateReplicaInput, buildReplicaRow, regionHash, pickNearest, pickRoundRobin, foldHealthCheck, decideRoute, lagBucket, POLICY_DESCRIPTIONS } from './replica-router.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { DEFAULT_MAX_LAG_MS, DEFAULT_WEIGHT, ReplicaKind, ReplicaStatus, RoutingPolicy, IReadReplica, IReadRouteLog, IRegisterReplicaInput, IRouteDecision, IHealthCheck } from './replica-router.types';
