/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `webhook-canvas` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { WebhookCanvasAuthService } from './webhook-canvas.auth.service';
export { validateWebhookCanvas, topoSortWebhook, planWebhookExecution, addWebhookNode, removeWebhookNode, addWebhookEdge, removeWebhookEdge, moveWebhookNode, serializeWebhookCanvas, summarizeWebhookCanvas, groupWebhookNodesByKind } from './webhook-canvas.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_WEBHOOK_CANVAS_NODES, MAX_WEBHOOK_CANVAS_EDGES, WEBHOOK_NODE_ID_RE, WebhookNodeKind, WebhookNodeSpec, WebhookEdgeSpec, WebhookCanvasSpec, WebhookValidationCode, WebhookValidationIssue, WebhookValidationResult, WebhookExecutionStep, WebhookExecutionPlan } from './webhook-canvas.types';
