/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `app-module-wiring` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { AppModuleWiringAuthService } from './app-module-wiring.auth.service';
export { validateWire } from './app-module-wiring.service';
export { buildManifest } from './app-module-wiring.service';
export { findWire } from './app-module-wiring.service';
export { mergeManifests } from './app-module-wiring.service';
export { filterByCategory } from './app-module-wiring.service';
export { filterByRound } from './app-module-wiring.service';
export { requiredNames } from './app-module-wiring.service';
export { hasAllRequired } from './app-module-wiring.service';
export { installOrder } from './app-module-wiring.service';
export { count } from './app-module-wiring.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { STAGES_90_TO_94_MODULES } from './app-module-wiring.types';
export { MAX_MODULES } from './app-module-wiring.types';
export { WireCategory } from './app-module-wiring.types';
export { IModuleWire } from './app-module-wiring.types';
export { IWiringManifest } from './app-module-wiring.types';
