/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `federated-sso` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { FederatedSsoAuthService } from './federated-sso.auth.service';
export { sortProviders } from './federated-sso.service';
export { emailDomain } from './federated-sso.service';
export { discoverProvider } from './federated-sso.service';
export { validateOidcConfig } from './federated-sso.service';
export { validateSamlConfig } from './federated-sso.service';
export { validateProvider } from './federated-sso.service';
export { buildSession } from './federated-sso.service';
export { oidcAuthorizeUrl } from './federated-sso.service';
export { samlLoginUrl } from './federated-sso.service';
export { DEFAULT_SSO_SESSION_TTL_SECONDS } from './federated-sso.service';
export { OIDC_DEFAULT_SCOPES } from './federated-sso.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SsoProtocol } from './federated-sso.types';
export { IOidcProviderConfig } from './federated-sso.types';
export { ISamlProviderConfig } from './federated-sso.types';
export { ISsoProvider } from './federated-sso.types';
export { ISsoDiscoveryRequest } from './federated-sso.types';
export { ISsoDiscoveryResult } from './federated-sso.types';
export { IFederatedSession } from './federated-sso.types';
