/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `generic-connector` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { GenericConnectorModule } from './generic-connector.module';

// ─── Controllers ──────────────────────────────────────────────────
export { GenericConnectorController } from './generic-connector.controller';

// ─── Services ─────────────────────────────────────────────────────
export { GenericConnectorService } from './generic-connector.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { GenericAdapterType } from './generic-connector.types';
export { GenericSourceSpec } from './generic-connector.types';
export { GenericRecord } from './generic-connector.types';
export { GenericFetchResult } from './generic-connector.types';
export { GenericAdapterInfo } from './generic-connector.types';
export { GenericConnectionProbe } from './generic-connector.types';

// ─── Other public exports ─────────────────────────────────────────
export { registerAdapter } from './generic-connector.adapters';
export { getAdapter } from './generic-connector.adapters';
export { listAdapterTypes } from './generic-connector.adapters';
export { listAdapterInfos } from './generic-connector.adapters';
export { jsonEndpointAdapter } from './generic-connector.adapters';
export { restApiAdapter } from './generic-connector.adapters';
export { csvUrlAdapter } from './generic-connector.adapters';
export { GenericAdapterFn } from './generic-connector.adapters';
