/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `generic-connector` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { GenericConnectorModule } from './generic-connector.module';

// ─── Controllers ──────────────────────────────────────────────────
export { GenericConnectorController } from './generic-connector.controller';

// ─── Services ─────────────────────────────────────────────────────
export { GenericConnectorService } from './generic-connector.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { GenericAdapterType, GenericSourceSpec, GenericRecord, GenericFetchResult, GenericAdapterInfo, GenericConnectionProbe } from './generic-connector.types';

// ─── Other public exports ─────────────────────────────────────────
export { registerAdapter, getAdapter, listAdapterTypes, listAdapterInfos, jsonEndpointAdapter, restApiAdapter, csvUrlAdapter, GenericAdapterFn } from './generic-connector.adapters';
