/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `page-designer` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { PageDesignerAuthService } from './page-designer.auth.service';
export { generatePageToken, hashPageToken, validateSlug, validateBlock, validateBlocks, validateCreateInput, renumberBlocks, resolveVisibility, parseBlocks, stringifyBlocks, parseTheme, stringifyTheme, isTokenActive, verifyToken, buildPageRow, applyUpdate, SLUG_REGEX, SUPPORTED_BLOCK_TYPES, SUPPORTED_VISIBILITY } from './page-designer.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PageBlockType, PageVisibility, IPageBlockBase, IPageViewBlock, IPageHeadingBlock, IPageTextBlock, IPageButtonBlock, IPageFilterBlock, IPageDividerBlock, IPageImageBlock, IPageBlock, IPageDefinition, IPageToken, ICreatePageInput, IUpdatePageInput, IResolvedVisibility } from './page-designer.types';
