/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `page-designer` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { PageDesignerAuthService } from './page-designer.auth.service';
export { generatePageToken } from './page-designer.service';
export { hashPageToken } from './page-designer.service';
export { validateSlug } from './page-designer.service';
export { validateBlock } from './page-designer.service';
export { validateBlocks } from './page-designer.service';
export { validateCreateInput } from './page-designer.service';
export { renumberBlocks } from './page-designer.service';
export { resolveVisibility } from './page-designer.service';
export { parseBlocks } from './page-designer.service';
export { stringifyBlocks } from './page-designer.service';
export { parseTheme } from './page-designer.service';
export { stringifyTheme } from './page-designer.service';
export { isTokenActive } from './page-designer.service';
export { verifyToken } from './page-designer.service';
export { buildPageRow } from './page-designer.service';
export { applyUpdate } from './page-designer.service';
export { SLUG_REGEX } from './page-designer.service';
export { SUPPORTED_BLOCK_TYPES } from './page-designer.service';
export { SUPPORTED_VISIBILITY } from './page-designer.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { PageBlockType } from './page-designer.types';
export { PageVisibility } from './page-designer.types';
export { IPageBlockBase } from './page-designer.types';
export { IPageViewBlock } from './page-designer.types';
export { IPageHeadingBlock } from './page-designer.types';
export { IPageTextBlock } from './page-designer.types';
export { IPageButtonBlock } from './page-designer.types';
export { IPageFilterBlock } from './page-designer.types';
export { IPageDividerBlock } from './page-designer.types';
export { IPageImageBlock } from './page-designer.types';
export { IPageBlock } from './page-designer.types';
export { IPageDefinition } from './page-designer.types';
export { IPageToken } from './page-designer.types';
export { ICreatePageInput } from './page-designer.types';
export { IUpdatePageInput } from './page-designer.types';
export { IResolvedVisibility } from './page-designer.types';
