/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `data-exchange` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { DataExchangeAuthService } from './data-exchange.auth.service';
export { escapeCsvCell, buildCsv, parseCsv, buildJson, parseJson, buildXlsxBase64, exportTable, validateRows, IJsonEnvelope } from './data-exchange.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_IMPORT_ROWS, MAX_CELL_BYTES, ExportFormat, ImportFormat, IColumn, IRow, ITableData, IExportResult, IImportSummary, IRowStore } from './data-exchange.types';
