/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `plugins` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { StorageModule } from './storage.module';

// ─── Types / interfaces ───────────────────────────────────────────
export { IPresignParams, IPresignRes, IObjectMeta, ILocalFileUpload, IRespHeaders, IListObjectsOptions, IListedObject, IListObjectsResult, ThumbnailSize } from './types';

// ─── Utilities ────────────────────────────────────────────────────
export { getSafeUploadContentType, isBodyParserFallback, getPublicFullStorageUrl, getPreviewCacheKey, getPreviewUrlConfigSig, getFreshPreviewCacheUrl, generateCropImagePath, resolveStorageUrl } from './utils';

// ─── Other public exports ─────────────────────────────────────────
export * from './adapter';
export { AliyunStorage } from './aliyun';
export { assertPathWithinStorage, validateReadPath, extractLocalFilePath } from './local.helper';
export { LocalStorage } from './local';
export { MinioStorage } from './minio';
export { S3Storage } from './s3';
export { InjectStorageAdapter, storageAdapterProvider } from './storage';
