/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `plugins` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { StorageModule } from './storage.module';

// ─── Types / interfaces ───────────────────────────────────────────
export { IPresignParams } from './types';
export { IPresignRes } from './types';
export { IObjectMeta } from './types';
export { ILocalFileUpload } from './types';
export { IRespHeaders } from './types';
export { IListObjectsOptions } from './types';
export { IListedObject } from './types';
export { IListObjectsResult } from './types';
export { ThumbnailSize } from './types';

// ─── Utilities ────────────────────────────────────────────────────
export { getSafeUploadContentType } from './utils';
export { isBodyParserFallback } from './utils';
export { getPublicFullStorageUrl } from './utils';
export { getPreviewCacheKey } from './utils';
export { getPreviewUrlConfigSig } from './utils';
export { getFreshPreviewCacheUrl } from './utils';
export { generateCropImagePath } from './utils';
export { resolveStorageUrl } from './utils';

// ─── Other public exports ─────────────────────────────────────────
export * from './adapter';
export { AliyunStorage } from './aliyun';
export { assertPathWithinStorage } from './local.helper';
export { validateReadPath } from './local.helper';
export { extractLocalFilePath } from './local.helper';
export { LocalStorage } from './local';
export { MinioStorage } from './minio';
export { S3Storage } from './s3';
export { InjectStorageAdapter } from './storage';
export { storageAdapterProvider } from './storage';
