/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `e2e-guard-smoke` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── Services ─────────────────────────────────────────────────────
export { E2eGuardSmokeAuthService } from './e2e-guard-smoke.auth.service';
export { validateGuardCase, guardOutcomeFor, capGuardCases, guardFailures, guardPassRate, buildCanonicalCases, envelopeForCase, statusForOutcome } from './e2e-guard-smoke.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_GUARD_CASES, MAX_GUARD_RESULTS, GuardSmokeOutcome, IGuardSmokeCase, IGuardSmokeResult, IGuardSmokeReport, IGuardSmokeExecutor } from './e2e-guard-smoke.types';
