/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `im-bridge` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { ImBridgeModule } from './im-bridge.module';

// ─── Controllers ──────────────────────────────────────────────────
export { TeamsConfigController } from './teams-config.controller';

// ─── Services ─────────────────────────────────────────────────────
export { TeamsConfigService, __teamsConfigTest } from './teams-config.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { IBridgeMessage, IBridgeAdapter } from './im-bridge.types';

// ─── Other public exports ─────────────────────────────────────────
export { buildAdapterRegistry, resolveAdapter, IBridgeAdapterRegistry } from './im-bridge.registry';
export { TeamsAdapter } from './teams.adapter';
