/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `login-risk` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { LoginRiskModule } from './login-risk.module';

// ─── Controllers ──────────────────────────────────────────────────
export { LoginRiskAdminController } from './login-risk.controller';

// ─── Services ─────────────────────────────────────────────────────
export { LoginRiskAuthService } from './login-risk.auth.service';
export { validateFingerprint, isKnownDevice, geoDistanceKm, isImpossibleTravel, isFailedBurst, isSuspiciousUserAgent, daysSinceLastSuccess, evaluate, decideOutcome, pushFingerprint } from './login-risk.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { MAX_RECENT_FINGERPRINTS, MAX_FAILED_LOGINS_PER_MIN, IMPOSSIBLE_TRAVEL_KMH, NEW_LOCATION_DISTANCE_KM, FAILED_BURST_WINDOW_MS, LOGIN_RISK_REASON_LABELS, LoginOutcome, ILoginFingerprint, ILoginAttempt, ILoginHistory, ILoginRiskInput, ILoginRiskOutput } from './login-risk.types';
