/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `custom-ai-model` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CustomAiModelModule } from './custom-ai-model.module';

// ─── Controllers ──────────────────────────────────────────────────
export { CustomAiModelController } from './custom-ai-model.controller';

// ─── Services ─────────────────────────────────────────────────────
export { CustomAiModelAuthService } from './custom-ai-model.auth.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { SUPPORTED_CUSTOM_PROVIDERS, CustomAiProvider, CustomAiIsolation, ICustomAiModel, ICreateCustomAiModelInput, IUpdateCustomAiModelInput, ICustomAiModelTestResult, ICustomAiModelUsage } from './custom-ai-model.types';
