/**
 * Notification center — Stage 45.
 *
 * Pure helpers: title/body validation, mention extraction from text,
 * quiet-hours evaluation, channel-filtering by preference, delivery
 * status transitions. All DB-touching work is delegated to
 * NotificationCenterAuthService.
 */

import type {
  DeliveryStatus,
  ICreateNotificationInput,
  INotification,
  INotificationDelivery,
  INotificationPreference,
  NotificationChannel,
  NotificationKind,
} from './notification-center.types';
import { DEFAULT_BODY_MAX_LENGTH, DEFAULT_TITLE_MAX_LENGTH } from './notification-center.types';

export function isValidKind(k: string): k is NotificationKind {
  return (
    k === 'mention' ||
    k === 'comment-reply' ||
    k === 'automation-run' ||
    k === 'approval-request' ||
    k === 'approval-decision' ||
    k === 'system'
  );
}

export function isValidChannel(c: string): c is NotificationChannel {
  return c === 'in-app' || c === 'email' || c === 'desktop' || c === 'webhook';
}

export function isValidDeliveryStatus(s: string): s is DeliveryStatus {
  return s === 'pending' || s === 'sent' || s === 'failed' || s === 'skipped';
}

export function validateCreateInput(input: ICreateNotificationInput): void {
  if (!isValidKind(input.kind)) throw new Error(`invalid kind: ${input.kind}`);
  if (!input.recipientUserId || input.recipientUserId.trim().length === 0) {
    throw new Error('recipientUserId required');
  }
  if (!input.baseId || input.baseId.trim().length === 0) {
    throw new Error('baseId required');
  }
  if (!input.title || input.title.trim().length === 0) {
    throw new Error('title required');
  }
  if (input.title.length > DEFAULT_TITLE_MAX_LENGTH) {
    throw new Error(`title too long (max ${DEFAULT_TITLE_MAX_LENGTH})`);
  }
  if (input.body.length > DEFAULT_BODY_MAX_LENGTH) {
    throw new Error(`body too long (max ${DEFAULT_BODY_MAX_LENGTH})`);
  }
}

/**
 * Pull @mention handles out of free text. Handles are
 * alphanumeric/dot/underscore, max 64 chars, prefixed by @.
 * Returns deduplicated list of handles (without the @).
 */
export function extractMentions(text: string): string[] {
  if (!text) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  const re = /@([\w.]+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const handle = m[1]!;
    if (handle.length > 63) {
      // Bypass this match by advancing lastIndex past the long run.
      re.lastIndex = m.index + 1 + 63;
      continue;
    }
    if (!seen.has(handle)) {
      seen.add(handle);
      out.push(handle);
    }
  }
  return out;
}

/** True if `hour` falls inside the [start,end] quiet window (inclusive). */
export function isInQuietHours(
  hour: number,
  start: number | undefined,
  end: number | undefined
): boolean {
  if (start === undefined || end === undefined) return false;
  if (start === end) return false;
  if (start < end) return hour >= start && hour < end;
  // Wraps midnight (e.g., 22..6): quiet if hour >= start OR hour < end.
  return hour >= start || hour < end;
}

export function defaultPreferences(userId: string): INotificationPreference {
  const allChannels: NotificationChannel[] = ['in-app', 'email'];
  return {
    userId,
    /* eslint-disable @typescript-eslint/naming-convention */
    channels: {
      mention: allChannels,
      'comment-reply': allChannels,
      'automation-run': allChannels,
      'approval-request': allChannels,
      'approval-decision': allChannels,
      system: allChannels,
    },
    /* eslint-enable @typescript-eslint/naming-convention */
  };
}

/**
 * Apply preferences + quiet hours to determine the channels we should
 * actually try. `in-app` is always included (the user's own device).
 * Email/desktop are skipped during quiet hours; webhooks always go through.
 */
export function resolveChannels(
  pref: INotificationPreference,
  kind: NotificationKind,
  hour: number
): NotificationChannel[] {
  const enabled = pref.channels[kind] ?? ['in-app'];
  const quiet = isInQuietHours(hour, pref.quietHoursStart, pref.quietHoursEnd);
  const filtered: NotificationChannel[] = ['in-app'];
  for (const ch of enabled) {
    if (ch === 'in-app') continue;
    if (ch === 'webhook') {
      filtered.push(ch);
      continue;
    }
    if (quiet) continue;
    filtered.push(ch);
  }
  return Array.from(new Set(filtered));
}

/**
 * Build a fresh `Notification` row. The `id` is generated by the caller.
 */
export function buildNotification(id: string, input: ICreateNotificationInput): INotification {
  validateCreateInput(input);
  return {
    id,
    baseId: input.baseId,
    recipientUserId: input.recipientUserId,
    kind: input.kind,
    title: input.title.trim(),
    body: input.body,
    link: input.link,
    sourceId: input.sourceId,
    readAt: null,
    createdTime: new Date(),
  };
}

export function buildDelivery(
  id: string,
  notificationId: string,
  channel: NotificationChannel
): INotificationDelivery {
  return {
    id,
    notificationId,
    channel,
    status: 'pending',
    attempts: 0,
  };
}

/** Mark a delivery as sent after successful channel attempt. */
export function markDeliverySent(d: INotificationDelivery): INotificationDelivery {
  return { ...d, status: 'sent', attempts: d.attempts + 1, sentAt: new Date() };
}

/** Mark a delivery as failed; bumps attempts and captures the error. */
export function markDeliveryFailed(d: INotificationDelivery, err: string): INotificationDelivery {
  return {
    ...d,
    status: 'failed',
    attempts: d.attempts + 1,
    lastError: err.slice(0, 500),
  };
}

/** True if the delivery has hit the attempt cap and should stop retrying. */
export function isDeliveryExhausted(d: INotificationDelivery, maxAttempts = 3): boolean {
  return d.attempts >= maxAttempts;
}

/** Mark a delivery skipped (e.g., preference filter dropped it). */
export function markDeliverySkipped(d: INotificationDelivery): INotificationDelivery {
  return { ...d, status: 'skipped' };
}

/** Mark a notification read. Idempotent. */
export function markRead(n: INotification): INotification {
  if (n.readAt) return n;
  return { ...n, readAt: new Date() };
}

/** Number of unread notifications in a list. */
export function countUnread(notifications: ReadonlyArray<INotification>): number {
  let n = 0;
  for (const x of notifications) if (!x.readAt) n++;
  return n;
}

/** Validate a single preference entry; throw if invalid. */
export function validatePreferences(pref: INotificationPreference): void {
  if (!pref.userId) throw new Error('userId required');
  const kinds: NotificationKind[] = [
    'mention',
    'comment-reply',
    'automation-run',
    'approval-request',
    'approval-decision',
    'system',
  ];
  for (const k of kinds) {
    if (!(k in pref.channels)) {
      throw new Error(`missing channel config for kind: ${k}`);
    }
    for (const ch of pref.channels[k]) {
      if (!isValidChannel(ch)) throw new Error(`invalid channel: ${ch}`);
    }
  }
  if (
    pref.quietHoursStart !== undefined &&
    (pref.quietHoursStart < 0 || pref.quietHoursStart > 23)
  ) {
    throw new Error('quietHoursStart must be 0–23');
  }
  if (pref.quietHoursEnd !== undefined && (pref.quietHoursEnd < 0 || pref.quietHoursEnd > 23)) {
    throw new Error('quietHoursEnd must be 0–23');
  }
}
