/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `risk-event-query` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { RiskEventQueryModule } from './risk-event-query.module';

// ─── Controllers ──────────────────────────────────────────────────
export { RiskEventQueryAdminController } from './risk-event-query.controller';

// ─── Services ─────────────────────────────────────────────────────
export { RiskEventQueryAuthService } from './risk-event-query.auth.service';
export { isRiskDecision, isRiskBand, isRiskEventKind, validateFilter, normalizeFilter, buildQuery, toWhere, cursorWhere, orderBy, nextCursor, matchRow, paginate } from './risk-event-query.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { RISK_DEFAULT_LIMIT, RISK_MAX_LIMIT, RISK_MAX_TERM_LENGTH, RISK_MAX_ORGS_PER_QUERY, RISK_MAX_ACTORS_PER_QUERY, RISK_DECISION_KINDS, RISK_BAND_KINDS, RISK_EVENT_KINDS, RiskDecisionKind, RiskBandKind, RiskEventKind, RiskOrdering, IRiskEventCursor, IRiskEventFilter, IRiskEventQuery, IRiskEventRow } from './risk-event-query.types';
