/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `cross-org-admin` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { CrossOrgAdminModule } from './cross-org-admin.module';

// ─── Controllers ──────────────────────────────────────────────────
export { CrossOrgAdminController } from './cross-org-admin.controller';

// ─── Services ─────────────────────────────────────────────────────
export { CrossOrgAdminService } from './cross-org-admin.service';

// ─── Types / interfaces ───────────────────────────────────────────
export { CROSS_ORG_ADMIN_DEFAULT_SCOPES, ICrossOrgAdminGrant } from './cross-org-admin.types';
