/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `retention` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AutomationRunCleanupModule } from './automation-run-cleanup.module';

// ─── Other public exports ─────────────────────────────────────────
export { AutomationRunCleanupProcessor } from './automation-run-cleanup.processor';
export { AUTOMATION_RUN_CLEANUP_QUEUE } from './automation-run-cleanup.processor';
export { AUTOMATION_RUN_CLEANUP_TICK_JOB } from './automation-run-cleanup.processor';
export { AUTOMATION_RUN_CLEANUP_REPEAT_MS } from './automation-run-cleanup.processor';
export { IAutomationRunCleanupTickResult } from './automation-run-cleanup.processor';
export { getRetentionDaysForPlan } from './retention-policy';
export { getRetentionMsForPlan } from './retention-policy';
export { getRetentionDaysForPlanLike } from './retention-policy';
export { MS_PER_DAY } from './retention-policy';
export { DEFAULT_RETENTION_DAYS } from './retention-policy';
export { RetentionKind } from './retention-policy';
export { RetentionPlan } from './retention-policy';
