/* AUTOGENERATED — DO NOT EDIT.
 *
 * Unified public surface for `retention` feature module.
 *
 * This file is regenerated by `scripts/generate-module-index.py`.
 * To re-export a new public symbol, export it from one of the
 * source files in this directory and re-run the script. Add
 * manual re-exports below the generated block if needed.
 */

// ─── NestJS module ────────────────────────────────────────────────
export { AutomationRunCleanupModule } from './automation-run-cleanup.module';

// ─── Other public exports ─────────────────────────────────────────
export { AutomationRunCleanupProcessor, AUTOMATION_RUN_CLEANUP_QUEUE, AUTOMATION_RUN_CLEANUP_TICK_JOB, AUTOMATION_RUN_CLEANUP_REPEAT_MS, IAutomationRunCleanupTickResult } from './automation-run-cleanup.processor';
export { getRetentionDaysForPlan, getRetentionMsForPlan, getRetentionDaysForPlanLike, MS_PER_DAY, DEFAULT_RETENTION_DAYS, RetentionKind, RetentionPlan } from './retention-policy';
